### PR TITLE
[smartbroker] Add `fxRate` and `foreignCurrency`. Fix issue with `Kirchensteuer`.

### LINKED ISSUE #292: Smartbroker - Erträgnisgutschrift wird nicht erfasst
## Document
<details><summary>Ausschuettung_ISHSII-GL_CL_ENERGY_DLDIS_vom_25_11_2020.pdf</summary><p>

```json
[
  [
    "Pxur",
    "Cjzes Qibkp Tczaavjsq",
    "Nuneqmg 51",
    "05225 Zzujzciqgn",
    "Kyqag Bbtzs Ozzjohykb",
    "BNP Paribas S.A. Niederlassung Deutschland > Standort: München > Landsberger Straße 300 > 80687 München > Sitz: Nürnberg HRB Nürnberg 31129 > USt.-Ident-Nr.: DE",
    "191528929 > Sitz der Hauptniederlassung der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449 > Président du",
    "Conseil d‘Administration: Jean Lemierre, Directeur Général: Jean-Laurent Bonnafé",
    "Depot-Nr.",
    "2266520167",
    "Abrechnungs-Nr.",
    "86910372 / 62.30.4767",
    "Depotinhaber",
    "4.95/GQXUBQVEUGTT/CGNSRPHI/480307/499282/969922",
    "München, 25.11.2020",
    "BELEGDRUCK=J",
    "ORIGINAL=1",
    "FAXVERSAND=N",
    "EMAILVERSAND=N",
    "XIQRQHLQKRN=5229947036",
    "DEPOTUNTERBEZEICHNUNG=",
    "VERSANDARTENSCHLUESSEL=DRUCK",
    "ADRESSZEILE1=Herr",
    "ZOTGZNMXRAH7=Iwbiu Bvynu Qiunwhzrk",
    "OHZFHXYTKZK1=Ohssqxn 00",
    "CCYSMTJKXTL0=63961 Yywphedrrh",
    "ADRESSZEILE5=",
    "ADRESSZEILE6=",
    "BELEGNUMMER=5320",
    "SEITENNUMMER=1",
    "STEUERERSTATTUNG=N",
    "Erträgnisgutschrift aus Wertpapieren",
    "Erträgnisgutschrift",
    "Gattungsbezeichnung",
    "iShsII-Gl.Clean Energy U.ETF Registered Shares o.N.",
    "ISIN",
    "IE00B1XNHC34",
    "Nominal",
    "STK 140,000",
    "Ex-Tag",
    "12.11.2020",
    "Zahltag",
    "25.11.2020",
    "Ausschüttungsbetrag pro Stück",
    "USD 0,041200",
    "Ausschüttung für",
    "01.11.2019 - 31.10.2020",
    "Es folgt Seite",
    "2",
    "Wert",
    "25.11.2020",
    "Konto-Nr.",
    "5133123017",
    "Betrag zu Ihren Gunsten",
    "USD",
    "4,47",
    "Ertrag für 2019/20",
    "USD",
    "5,77",
    "Hinweise zur steuerlichen Verrechnung:",
    "vorher",
    "aktuell",
    "Steuerpflichtiger Ausschüttungsbetrag",
    "EUR",
    "4,12",
    "Aktienverlusttopf",
    "EUR",
    "0,00",
    "0,00",
    "allgemeiner Verlusttopf",
    "EUR",
    "0,00",
    "0,00",
    "Quellensteuertopf",
    "EUR",
    "0,00",
    "0,00",
    "zu versteuern",
    "EUR",
    "4,12",
    "einbehaltene Kapitalertragsteuer",
    "EUR",
    "1,03",
    "einbehaltener Solidaritätszuschlag",
    "EUR",
    "0,06",
    "im laufenden Jahr einbehaltene Kapitalertragsteuer",
    "EUR",
    "136,41",
    "im laufenden Jahr einbehaltener Solidaritätszuschlag",
    "EUR",
    "7,50",
    "Kapitalertragsteuer, Solidaritätszuschlag und ggf. Kirchensteuer nach gemeldetem Kirchensteuersatz verrechnet mit dem",
    "Finanzamt Frankfurt/M. V-Höchst, Steuernummer 047/220/15370.",
    "Steuerlicher Stichtag: 25.11.2020",
    "Devisenkurs: EUR/USD 1,19035",
    "Jahressteuerbescheinigung folgt"
  ],
  [
    "BNP Paribas S.A. Niederlassung Deutschland > Standort: München > Landsberger Straße 300 > 80687 München > Sitz: Nürnberg HRB Nürnberg 31129 > USt.-Ident-Nr.: DE",
    "191528929 > Sitz der Hauptniederlassung der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449 > Président du",
    "Conseil d‘Administration: Jean Lemierre, Directeur Général: Jean-Laurent Bonnafé",
    "Depot-Nr.",
    "Abrechnungs-Nr.",
    "Seite-Nr.",
    "2333747967",
    "66321902",
    "2",
    "3.17/ABREEREIERTR/GDBERTRG/005320/251120/235655",
    "BELEGDRUCK=J",
    "ORIGINAL=1",
    "FAXVERSAND=N",
    "EMAILVERSAND=N",
    "DEPOTNUMMER=5133123009",
    "DEPOTUNTERBEZEICHNUNG=",
    "VERSANDARTENSCHLUESSEL=DRUCK",
    "ADRESSZEILE1=Herr",
    "ADRESSZEILE2=Aurel Simon Sommerlad",
    "ADRESSZEILE3=Selmnau 27",
    "ADRESSZEILE4=88142 Wasserburg",
    "ADRESSZEILE5=",
    "ADRESSZEILE6=",
    "BELEGNUMMER=5320",
    "SEITENNUMMER=2",
    "STEUERERSTATTUNG=N",
    "Dieser Beleg wird maschinell erstellt und daher nicht unterschrieben.",
    "Fondsart:",
    "Mischfonds (§ 2 Abs. 7 InvStG)",
    "Angewendete Teilfreistellungsquote: 15%",
    "Im Steuerabzugsverfahren werden generell - auch bei betrieblichen Anlegern - die Teilfreistellungsquoten (TFQ) für",
    "Privatanleger herangezogen.",
    "Verwahrart: Wertpapierrechnung",
    "Lagerland: Irland"
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #293: Smartbroker - Dividendengutschrift wird nicht erfasst
## Document
<details><summary>Dividenden_PAN_AMER__SILVER_CORP__vom_27_11_2020.pdf</summary><p>

```json
[
  [
    "Qzqh",
    "Memaj Vgxco Dordtqzrx",
    "Vglkzav 02",
    "46087 Agjqaduwjf",
    "Tctbt Delug Bzgfgkfly",
    "BNP Paribas S.A. Niederlassung Deutschland > Standort: München > Landsberger Straße 300 > 80687 München > Sitz: Nürnberg HRB Nürnberg 31129 > USt.-Ident-Nr.: DE",
    "191528929 > Sitz der Hauptniederlassung der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449 > Président du",
    "Conseil d‘Administration: Jean Lemierre, Directeur Général: Jean-Laurent Bonnafé",
    "Depot-Nr.",
    "3671582917",
    "Abrechnungs-Nr.",
    "92100927 / 80.06.1628",
    "Depotinhaber",
    "4.58/UJJGCRZNLUZC/OSAUFMKL/712808/172683/257897",
    "München, 27.11.2020",
    "BELEGDRUCK=J",
    "ORIGINAL=1",
    "FAXVERSAND=N",
    "EMAILVERSAND=N",
    "DEPOTNUMMER=5133123009",
    "DEPOTUNTERBEZEICHNUNG=",
    "VERSANDARTENSCHLUESSEL=DRUCK",
    "FLONGMWFMMV6=Uzqb",
    "DISOFEEHUYY5=Bnceu Lblhv Lupnqbelt",
    "MIYGSTYPRHA7=Almzhhp 04",
    "SUBJGJOPAOJ3=07375 Zrnlqqmygq",
    "ADRESSZEILE5=",
    "ADRESSZEILE6=",
    "BELEGNUMMER=3372",
    "SEITENNUMMER=1",
    "STEUERERSTATTUNG=N",
    "ERSTATTUNGSFÄHIGE",
    "Dieser Beleg wird maschinell erstellt und daher nicht unterschrieben.",
    "Erträgnisgutschrift aus Wertpapieren",
    "Dividendengutschrift",
    "Gattungsbezeichnung",
    "Pan American Silver Corp. Registered Shares o.N.",
    "ISIN",
    "CA6979001089",
    "Nominal",
    "STK 25,000",
    "Ex-Tag",
    "13.11.2020",
    "Zahltag",
    "27.11.2020",
    "Dividenden-Betrag pro Stück",
    "USD 0,070000",
    "Dividende für",
    "01.01.2020 - 31.12.2020",
    "Wert",
    "27.11.2020",
    "Konto-Nr.",
    "5133123017",
    "Betrag zu Ihren Gunsten",
    "USD",
    "1,12",
    "Hinweise zur steuerlichen Verrechnung:",
    "vorher",
    "aktuell",
    "ausländische Dividende",
    "EUR",
    "1,47",
    "ausländische Quellensteuer 25%",
    "USD",
    "0,44",
    "anrechenbare Quellensteuer 15%",
    "USD",
    "0,26",
    "erstattungsfähige Quellensteuer 10%",
    "USD",
    "0,18",
    "Aktienverlusttopf",
    "EUR",
    "0,00",
    "0,00",
    "allgemeiner Verlusttopf",
    "EUR",
    "0,00",
    "0,00",
    "Quellensteuertopf",
    "EUR",
    "0,00",
    "0,00",
    "zu versteuern",
    "EUR",
    "0,59",
    "einbehaltene Kapitalertragsteuer",
    "EUR",
    "0,15",
    "einbehaltener Solidaritätszuschlag",
    "EUR",
    "0,01",
    "im laufenden Jahr einbehaltene Kapitalertragsteuer",
    "EUR",
    "136,40",
    "im laufenden Jahr einbehaltener Solidaritätszuschlag",
    "EUR",
    "7,50",
    "Kapitalertragsteuer, Solidaritätszuschlag und ggf. Kirchensteuer nach gemeldetem Kirchensteuersatz verrechnet mit dem",
    "Finanzamt Frankfurt/M. V-Höchst, Steuernummer 047/220/15370.",
    "Steuerlicher Stichtag: 27.11.2020",
    "Devisenkurs: EUR/USD 1,1906",
    "Jahressteuerbescheinigung folgt",
    "Verwahrart: Wertpapierrechnung",
    "Lagerland: Kanada"
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #315: Smartbroker Dividenden & Verkauf
## Documents
<details><summary>Verkauf_Aktie_HELLOFRESH_SE__INH_O_N__vom_19_11_2020.pdf</summary><p>

```json
[
  [
    "Frau",
    "Onjtnvki Ttjcydig Vbmsz",
    "Kboix 92",
    "61606 Mulawchztk",
    "Qrcrgpjg Ioexqvuw Pkjs Pmpwf",
    "BNP Paribas S.A. Niederlassung Deutschland > Standort: München > Landsberger Straße 300 > 80687 München > Sitz: Nürnberg HRB Nürnberg 31129 > USt.-Ident-Nr.: DE",
    "191528929 > Sitz der Hauptniederlassung der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449 > Président du",
    "Conseil d‘Administration: Jean Lemierre, Directeur Général: Jean-Laurent Bonnafé",
    "Depot-Nr.",
    "8968477450",
    "Abrechnungs-Nr.",
    "52263137 / 19.11.2020",
    "Depotinhaber",
    "3.19/ABREABHNHANDVFDI/GAAASAFG/004308/191120/210700",
    "München, 19.11.2020",
    "BELEGDRUCK=J",
    "ORIGINAL=1",
    "FAXVERSAND=N",
    "EMAILVERSAND=N",
    "DEPOTNUMMER=5126841005",
    "DEPOTUNTERBEZEICHNUNG=",
    "VERSANDARTENSCHLUESSEL=DRUCK",
    "ADRESSZEILE1=Frau",
    "QYESXNRMKOO8=Uzefocsc Ccxoszvl Zbnx Woxrk",
    "TKVNYROAKXD9=Heauj 96",
    "PBITWXFGUYQ2=20977 Xdkfaxnjuc",
    "ADRESSZEILE5=",
    "ADRESSZEILE6=",
    "BELEGNUMMER=4308",
    "SEITENNUMMER=1",
    "STEUERERSTATTUNG=N",
    "Wertpapierabrechnung",
    "Verkauf",
    "Kommissionsgeschäft",
    "Gattungsbezeichnung",
    "HelloFresh SE Inhaber-Aktien o.N.",
    "ISIN",
    "DE000A161408",
    "Nominal",
    "STK 11,000",
    "Kurs",
    "EUR 47,6000",
    "Dieser Beleg wird maschinell erstellt und daher nicht unterschrieben.",
    "Wir haben für Sie verkauft",
    "Handelstag",
    "19.11.2020",
    "Handelszeit",
    "16:22*",
    "Börse",
    "Gettex/GDM",
    "Verwahrart",
    "Girosammelverwahrung",
    "Kurswert",
    "EUR",
    "523,60",
    "Wert",
    "23.11.2020",
    "Konto-Nr.",
    "5126841005",
    "Betrag zu Ihren Gunsten",
    "EUR",
    "523,60",
    "Hinweise zur steuerlichen Verrechnung:",
    "vorher",
    "aktuell",
    "Veräußerungsgewinn Aktien",
    "EUR",
    "3,74",
    "Aktienverlusttopf",
    "EUR",
    "0,00",
    "0,00",
    "allgemeiner Verlusttopf",
    "EUR",
    "0,00",
    "0,00",
    "Freistellungsauftrag (eingereicht: EUR 735,00)",
    "EUR",
    "702,26",
    "738,62",
    "Quellensteuertopf",
    "EUR",
    "0,00",
    "0,00",
    "zu versteuern",
    "EUR",
    "0,00",
    "im laufenden Jahr einbehaltene Kapitalertragsteuer",
    "EUR",
    "0,00",
    "im laufenden Jahr einbehaltener Solidaritätszuschlag",
    "EUR",
    "0,00",
    "Jahressteuerbescheinigung folgt",
    "Wir werden in Ihrem Depot wie angegeben buchen.",
    "* Die angegebene Zeit entspricht den Angaben der Handelspartner gemäß der lokalen Zeit in Deutschland",
    "(Mitteleuropäische Zeit bzw. Mitteleuropäische Sommerzeit)."
  ]
]

```

</p></details>

<details><summary>Ausschuettung_ISHS-MSCI_WORLD_DL_D_vom_30_09_2020.pdf</summary><p>

```json
[
  [
    "Frau",
    "Lxvpiwaj Ocjmjafx Whhtr",
    "Iujjp 63",
    "68653 Qstknlxmae",
    "Knapqczu Boronwmj Fbiz Dvplr",
    "BNP Paribas S.A. Niederlassung Deutschland > Standort: München > Landsberger Straße 300 > 80687 München > Sitz: Nürnberg HRB Nürnberg 31129 > USt.-Ident-Nr.: DE",
    "191528929 > Sitz der Hauptniederlassung der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449 > Président du",
    "Conseil d‘Administration: Jean Lemierre, Directeur Général: Jean-Laurent Bonnafé",
    "Depot-Nr.",
    "3087773660",
    "Abrechnungs-Nr.",
    "75040265 / 30.09.2020",
    "Depotinhaber",
    "3.17/ABREEREIERTR/GDBERTRG/012295/011020/001053",
    "München, 30.09.2020",
    "BELEGDRUCK=J",
    "ORIGINAL=1",
    "FAXVERSAND=N",
    "EMAILVERSAND=N",
    "DEPOTNUMMER=5126841005",
    "DEPOTUNTERBEZEICHNUNG=",
    "VERSANDARTENSCHLUESSEL=DRUCK",
    "BIWJLMACBCW8=Fgnt",
    "DQEZAXFBEJU5=Gdmqvmlv Rriokkze Cjlt Mpgrq",
    "TVZWLMTKPOG3=Hadix 29",
    "TKYHRCKTHZG9=07298 Genvuskrly",
    "ADRESSZEILE5=",
    "ADRESSZEILE6=",
    "BELEGNUMMER=12295",
    "SEITENNUMMER=1",
    "STEUERERSTATTUNG=N",
    "Dieser Beleg wird maschinell erstellt und daher nicht unterschrieben.",
    "Erträgnisgutschrift aus Wertpapieren",
    "Erträgnisgutschrift",
    "Gattungsbezeichnung",
    "iShs-MSCI World UCITS ETF Registered Shares USD (Dist)oN",
    "ISIN",
    "IE00B0M62Q58",
    "Nominal",
    "STK 7,000",
    "Ex-Tag",
    "17.09.2020",
    "Zahltag",
    "30.09.2020",
    "Ausschüttungsbetrag pro Stück",
    "USD 0,146600",
    "Ausschüttung für",
    "01.03.2020 - 28.02.2021",
    "Wert",
    "30.09.2020",
    "Konto-Nr.",
    "5126841005",
    "Devisenkurs",
    "EUR/USD 1,17065",
    "Betrag zu Ihren Gunsten",
    "EUR",
    "0,88",
    "Ertrag für 2020/21",
    "USD",
    "1,03",
    "Hinweise zur steuerlichen Verrechnung:",
    "vorher",
    "aktuell",
    "Steuerpflichtiger Ausschüttungsbetrag",
    "EUR",
    "0,61",
    "Aktienverlusttopf",
    "EUR",
    "0,00",
    "0,00",
    "allgemeiner Verlusttopf",
    "EUR",
    "0,00",
    "0,00",
    "Freistellungsauftrag (eingereicht: EUR 735,00)",
    "EUR",
    "707,55",
    "998,77",
    "Quellensteuertopf",
    "EUR",
    "0,00",
    "0,00",
    "zu versteuern",
    "EUR",
    "0,00",
    "im laufenden Jahr einbehaltene Kapitalertragsteuer",
    "EUR",
    "0,00",
    "im laufenden Jahr einbehaltener Solidaritätszuschlag",
    "EUR",
    "0,00",
    "Steuerlicher Stichtag: 30.09.2020",
    "Jahressteuerbescheinigung folgt",
    "Fondsart:",
    "Aktienfonds (§ 2 Abs. 6 InvStG)",
    "Angewendete Teilfreistellungsquote: 30%",
    "Im Steuerabzugsverfahren werden generell - auch bei betrieblichen Anlegern - die Teilfreistellungsquoten (TFQ) für",
    "Privatanleger herangezogen.",
    "Verwahrart: Wertpapierrechnung",
    "Lagerland: Großbritannien"
  ]
]

```

</p></details>

<details><summary>Ausschuettung_VANG_FTSE_A_-WO_U_ETF_DLD_vom_09_10_2020.pdf</summary><p>

```json
[
  [
    "Frau",
    "Zjopldef Bygpyrjk Harpq",
    "Ilxip 79",
    "05357 Nggelivzph",
    "Vomhmcsz Bzukiwyb Xgay Xucxs",
    "BNP Paribas S.A. Niederlassung Deutschland > Standort: München > Landsberger Straße 300 > 80687 München > Sitz: Nürnberg HRB Nürnberg 31129 > USt.-Ident-Nr.: DE",
    "191528929 > Sitz der Hauptniederlassung der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449 > Président du",
    "Conseil d‘Administration: Jean Lemierre, Directeur Général: Jean-Laurent Bonnafé",
    "Depot-Nr.",
    "5705025071",
    "Abrechnungs-Nr.",
    "28694091 / 09.10.2020",
    "Depotinhaber",
    "3.17/ABREEREIERTR/GDBERTRG/008299/091020/015334",
    "München, 09.10.2020",
    "BELEGDRUCK=J",
    "ORIGINAL=1",
    "FAXVERSAND=N",
    "EMAILVERSAND=N",
    "DEPOTNUMMER=5126841005",
    "DEPOTUNTERBEZEICHNUNG=",
    "VERSANDARTENSCHLUESSEL=DRUCK",
    "ADRESSZEILE1=Frau",
    "NSWZVGRDGGD9=Fmuwltiy Niopbsxi Wshh Aakyy",
    "TAWGAPEJXGS1=Gbupf 47",
    "CTSELYNGUZF1=99255 Cuasxehfnl",
    "ADRESSZEILE5=",
    "ADRESSZEILE6=",
    "BELEGNUMMER=8299",
    "SEITENNUMMER=1",
    "STEUERERSTATTUNG=N",
    "Dieser Beleg wird maschinell erstellt und daher nicht unterschrieben.",
    "Erträgnisgutschrift aus Wertpapieren",
    "Erträgnisgutschrift",
    "Gattungsbezeichnung",
    "Vanguard FTSE All-World U.ETF Registered Shares USD Dis.oN",
    "ISIN",
    "IE00B3RBWM25",
    "Nominal",
    "STK 17,3681",
    "Ex-Tag",
    "24.09.2020",
    "Zahltag",
    "07.10.2020",
    "Ausschüttungsbetrag pro Stück",
    "USD 0,454628",
    "Ausschüttung für",
    "01.07.2019 - 30.06.2020",
    "Wert",
    "07.10.2020",
    "Konto-Nr.",
    "5126841005",
    "Devisenkurs",
    "EUR/USD 1,1804",
    "Betrag zu Ihren Gunsten",
    "EUR",
    "6,69",
    "Ertrag für 2019/20",
    "USD",
    "7,90",
    "Hinweise zur steuerlichen Verrechnung:",
    "vorher",
    "aktuell",
    "Steuerpflichtiger Ausschüttungsbetrag",
    "EUR",
    "4,68",
    "Aktienverlusttopf",
    "EUR",
    "0,00",
    "0,00",
    "allgemeiner Verlusttopf",
    "EUR",
    "0,00",
    "0,00",
    "Freistellungsauftrag (eingereicht: EUR 735,00)",
    "EUR",
    "706,94",
    "917,53",
    "Quellensteuertopf",
    "EUR",
    "0,00",
    "0,00",
    "zu versteuern",
    "EUR",
    "0,00",
    "im laufenden Jahr einbehaltene Kapitalertragsteuer",
    "EUR",
    "0,00",
    "im laufenden Jahr einbehaltener Solidaritätszuschlag",
    "EUR",
    "0,00",
    "Steuerlicher Stichtag: 07.10.2020",
    "Jahressteuerbescheinigung folgt",
    "Fondsart:",
    "Aktienfonds (§ 2 Abs. 6 InvStG)",
    "Angewendete Teilfreistellungsquote: 30%",
    "Im Steuerabzugsverfahren werden generell - auch bei betrieblichen Anlegern - die Teilfreistellungsquoten (TFQ) für",
    "Privatanleger herangezogen.",
    "Verwahrart: Wertpapierrechnung",
    "Lagerland: Großbritannien"
  ]
]

```

</p></details>

<details><summary>Ausschuettung_LYX_WORLD_WATER_U_ETF_D_vom_10_07_2020.pdf</summary><p>

```json
[
  [
    "Frau",
    "Qnozmugz Mdghonpv Wvpik",
    "Fjdem 90",
    "63186 Zxxyuurncu",
    "Rzcmlycq Gijspsbl Ettb Dsocc",
    "BNP Paribas S.A. Niederlassung Deutschland > Standort: München > Landsberger Straße 300 > 80687 München > Sitz: Nürnberg HRB Nürnberg 31129 > USt.-Ident-Nr.: DE",
    "191528929 > Sitz der Hauptniederlassung der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449 > Président du",
    "Conseil d‘Administration: Jean Lemierre, Directeur Général: Jean-Laurent Bonnafé",
    "Depot-Nr.",
    "8794450543",
    "Abrechnungs-Nr.",
    "37641996 / 10.07.2020",
    "Depotinhaber",
    "3.17/ABREEREIERTR/GDBERTRG/007747/100720/234034",
    "München, 10.07.2020",
    "BELEGDRUCK=J",
    "ORIGINAL=1",
    "FAXVERSAND=N",
    "EMAILVERSAND=N",
    "DEPOTNUMMER=5126841005",
    "DEPOTUNTERBEZEICHNUNG=",
    "VERSANDARTENSCHLUESSEL=DRUCK",
    "ADRESSZEILE1=Frau",
    "FGYIVWAZVBR3=Rdskiegr Kyzxszvc Lugj Uyulw",
    "QQJUNKTTCRJ5=Tjjph 08",
    "GJJGAQAPXXH1=54336 Rrvhlgodzs",
    "ADRESSZEILE5=",
    "ADRESSZEILE6=",
    "BELEGNUMMER=7747",
    "SEITENNUMMER=1",
    "STEUERERSTATTUNG=N",
    "Dieser Beleg wird maschinell erstellt und daher nicht unterschrieben.",
    "Erträgnisgutschrift aus Wertpapieren",
    "Erträgnisgutschrift",
    "Gattungsbezeichnung",
    "Lyxor World Water UCITS ETF Actions au Port.Dist o.N.",
    "ISIN",
    "FR0010527275",
    "Nominal",
    "STK 77,000",
    "Ex-Tag",
    "08.07.2020",
    "Zahltag",
    "10.07.2020",
    "Ausschüttungsbetrag pro Stück",
    "EUR 0,560000",
    "Ausschüttung für",
    "01.11.2019 - 31.10.2020",
    "Wert",
    "10.07.2020",
    "Konto-Nr.",
    "5126841005",
    "Betrag zu Ihren Gunsten",
    "EUR",
    "43,12",
    "Ertrag für 2019/20",
    "EUR",
    "43,12",
    "Hinweise zur steuerlichen Verrechnung:",
    "vorher",
    "aktuell",
    "Steuerpflichtiger Ausschüttungsbetrag",
    "EUR",
    "30,18",
    "Aktienverlusttopf",
    "EUR",
    "0,00",
    "0,00",
    "allgemeiner Verlusttopf",
    "EUR",
    "0,00",
    "0,00",
    "Freistellungsauftrag (eingereicht: EUR 735,00)",
    "EUR",
    "735,00",
    "704,82",
    "Quellensteuertopf",
    "EUR",
    "0,00",
    "0,00",
    "zu versteuern",
    "EUR",
    "0,00",
    "im laufenden Jahr einbehaltene Kapitalertragsteuer",
    "EUR",
    "0,00",
    "im laufenden Jahr einbehaltener Solidaritätszuschlag",
    "EUR",
    "0,00",
    "Steuerlicher Stichtag: 10.07.2020",
    "Jahressteuerbescheinigung folgt",
    "Fondsart:",
    "Aktienfonds (§ 2 Abs. 6 InvStG)",
    "Angewendete Teilfreistellungsquote: 30%",
    "Im Steuerabzugsverfahren werden generell - auch bei betrieblichen Anlegern - die Teilfreistellungsquoten (TFQ) für",
    "Privatanleger herangezogen.",
    "Verwahrart: Girosammelverwahrung"
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

### PR DESCRIPTION
**Pull request by dredav**
- Fix #292 
- Fix #293 
- Fix #315
- Add test cases from #292 & #293 
- Add properties `fxRate` and `foreignCurrency`
- Fix tax logic when `Solidaritätszuschlag` was present but `Kirchensteuer` isn't

### CODE REVIEW

File: src/brokers/smartbroker.js [hunk 1]
```diff
@@ -21,32 +23,80 @@ const findTax = textArr => {
...
+  if (!lineContent.includes(' ')) {
+    // Handle format no. 1:
+    // Devisenkurs
+    // EUR/USD 1,1821
+    regexMatch = regex.exec(content[fxRateLineNumber + 1]);
+  } else {
+    // Handle fromat no. 2:
+    // Devisenkurs: EUR/USD 1,1906
+    regexMatch = regex.exec(lineContent);
+  }
```
Comment (SirGibihm) [inline src/brokers/smartbroker.js:77]: This can be simplified (Not sure if its simpler though) using a `?`. I guess for the sake of readability `if [...] else` is the better solution.
```javascript 
const fxInfo= lineContent.includes(' ') ? regex.exec(lineContent) : regex.exec(content[fxRateLineNumber + 1]);
```
In any case I would prefer the `if` condition not be be negated for readability. No functional complaints though

**Review by SirGibihm — APPROVED** [review]

**Review by codeofsumit — CHANGES_REQUESTED** [review]
`datetime` is finally merged. But created some last merge conflicts here

**Comment by dredav** [comment]
Conflicts solved!

**Review by SirGibihm — APPROVED** [review]
