### PR TITLE
[flatex] Support old format / bank name, fix payout from ETFs, ignore order confirmations

### LINKED ISSUE #256: Flatex, Probleme mit alten Rechnungen
## Document
<details><summary>20160518_KaufFondsZertifikate_1008613106_61309192.pdf</summary><p>

```json
[
  [
    "0113202270000102",
    "5737303465812300",
    "biw AG",
    "Hausbroicher Str. 222",
    "47877 Willich",
    "USt-IdNr.: DE 246 786 363",
    "Kundenservice:",
    "Tel.: +49 (0)9221 - 7035898",
    "E-Mail: kunden@flatex.de",
    "biw AG -  Hausbroicher Str. 222 -  47877 Willich",
    "0202272000000613091920",
    "Willich,          18.05.2016",
    "Auftragsdatum     14.05.2016",
    "Schlusstag        17.05.2016",
    "Ausführungszeit   09:04 Uhr",
    "Valuta            19.05.2016",
    "Auftragsnummer    78506084/1",
    "Ausf.platz/-art   XETRA",
    "Xaacc",
    "Tmjychhw Kypsyf",
    "Tus-Pby-Ucm. 58x",
    "65129 Vhqyjkr",
    "Wertpapierabrechnung Kauf Fonds/Zertifikate",
    "Yooi Xovxkabwdqh  6650380999",
    "Ckluzrhqrkml      Uzhryn, Wkicctvy",
    "Nr.78506084/1  Kauf            ISHSIII-C.MSCI W.U.E.ACDL (IE00B4L5Y983/A0RPWH)",
    "Ausgeführt     15 St.",
    "Kurs           36,540000 EUR           Kurswert       EUR               548,10",
    "Devisenkurs                            Provision      EUR                 5,00",
    "Verwahrart     GS-Verwahrung           Eigene Spesen",
    "Lagerstelle    Clearstream Nat.       *Fremde Spesen  EUR                 2,88",
    "Lagerland      Deutschland",
    "Gewinn/Verlust 0,00 EUR              **Einbeh. Steuer EUR                 0,00",
    "Endbetrag      EUR              -555,98",
    "* Enthalten sind folgende Gebühren     Courtage       EUR                 0,00",
    "Tradinggebühr  EUR                 0,82",
    "Regulierung    EUR                 1,99",
    "Schlussnoten   EUR                 0,07",
    "Sonstige       EUR                 0,00",
    "**  Einbehaltene Kapitalertragsteuer zuzüglich Solidaritätszuschlag und ggf.",
    "Kirchensteuer (negative Werte bedeuten Steuererstattung). Evtl. Details dazu",
    "finden Sie im Steuerreport unter der Transaktion-Nr.: 1035091255",
    "Zwischengewinn je Anteil               USD               0,0008",
    "Zwischengewinn Gesamt                  USD               0,0100",
    "ausschüttungsgleiche Erträge je Anteil EUR         2,9042725300",
    "ausschüttungsgleiche Erträge gesamt    EUR                43,56",
    "Die Verrechnung des Endbetrags erfolgt über Ihr Konto Nr.: 1008613106",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Willich  -  Amtsgericht Krefeld  (HRB 10867)",
    "Vorsitzender des Aufsichtsrats: Frank Niehage   -  Vorstand: Lars Lankes, Bernd Würfel"
  ],
  [
    "0113202270000202",
    "2000000613091920",
    "Die Wertpapiere sowie den Gegenwert werden wir entsprechend der Abrechnung mit",
    "dem  angegebenen  Valutatag  buchen.  Bitte prüfen Sie  diese  Abrechnung  auf",
    "Richtigkeit und Vollständigkeit.  Etwaige Einwendungen gegen diese  Abrechnung",
    "müssen unverzüglich  nach Zugang bei der Bank  erhoben werden. Die",
    "Unterlassung rechtzeitiger Einwendung gilt als Genehmigung. Bitte beachten",
    "Sie mögliche Hinweise des Emittenten  hinsichtlich vorzeitiger Fälligstellung,",
    "beispielsweise wegen Knock-Out, in den jeweiligen Optionsscheinbedingungen und",
    "informieren Sie sich rechtzeitig, welche spezielle Fälligkeitsregelung auf die",
    "von Ihnen gehaltenen Wertpapiere zutreffen. Kapitalerträge sind ESt-pflichtig.",
    "Diese  Mitteilung  ist  maschinell  erstellt  und  wird  nicht unterschrieben.",
    "Für weitergehende Fragen wenden Sie sich bitte an Ihr flatex-Service-Team.",
    "Viel Freiheit für wenig Zins - Ihr flatex flex-Kredit zu günstigen",
    "Konditionen: 3,90% p.a.",
    "Weitere Informationen finden Sie unter: www.flatex.de/kredit/",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Willich  -  Amtsgericht Krefeld  (HRB 10867)",
    "Vorsitzender des Aufsichtsrats: Frank Niehage   -  Vorstand: Lars Lankes, Bernd Würfel"
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #267: [flatex] Sammelbestätigung Verkauf
## Document
<details><summary>20200627_Orderbestaetigung_[REDACTED]_156636517.pdf</summary><p>

```json
[
  [
    "0113303470000101",
    "2000001566365170",
    "flatex Bank AG",
    "Postfach 100551",
    "41405 Neuss",
    "USt-IdNr.: DE 246 786 363",
    "Kundenservice:",
    "Tel.: +49 (0)9221 - 7035898",
    "E-Mail: kunden@flatex.de",
    "flatex Bank AG -  Rotfeder-Ring 7 - 60327 Frankfurt am Main",
    "0303472000001566365170",
    "Frankfurt, 27.06.2020",
    "Herrn",
    "[REDACTED]",
    "[REDACTED]",
    "[REDACTED]",
    "Sammelauftragsbestätigung",
    "Ihre Depotnummer: [REDACTED]",
    "Depotinhaber:     [REDACTED]",
    "------------------------------------------------------------------------------",
    "Auftrags-Nr  ISIN           Wertpapierbezeichnung       Ausf.platz/-art",
    "WKN            Geschäftsart/Auftr.Datum    Stücke/Nominale",
    "------------------------------------------------------------------------------",
    "148567117    US88579Y1010   3M CO.             DL-,01   NYSE",
    "851745         Verkauf vom 26.06.2020      42,00 St.",
    "Gültig bis:                 25.09.2020",
    "Limit:                      165,000 USD",
    "------------------------------------------------------------------------------",
    "148567225    US0395871009   ARCIMOTO INC.               NASDAQ",
    "A2JN1H         Verkauf vom 26.06.2020      1.500,00 St.",
    "Gültig bis:                 01.09.2020",
    "Limit:                      6,000 USD",
    "------------------------------------------------------------------------------",
    "148567324    US88160R1014   TESLA INC. DL -,001         NASDAQ",
    "A1CX3T         Verkauf vom 26.06.2020      6,00 St.",
    "Gültig bis:                 01.09.2020",
    "Limit:                      1.000,000 USD",
    "------------------------------------------------------------------------------",
    "______________________________________________________________________________",
    "Seite 1/2",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Frankfurt  -  Amtsgericht Frankfurt am Main (HRB 105687)",
    "Vorsitzender des Aufsichtsrats: Martin Korbmacher  -  Vorstand: Frank Niehage (Vorsitzender), Jörn Engelmann"
  ],
  [
    "2000001566365170",
    "Bitte prüfen Sie diese Auftragsbestätigung auf Richtigkeit und Vollständigkeit",
    "Etwaige Einwendungen gegen diese Auftragsbestätigung müssen unverzüglich nach",
    "Zugang bei der Bank erhoben werden. Die Unterlassung rechtzeitiger Einwendung",
    "gilt als Genehmigung.",
    "Diese  Mitteilung  ist  maschinell  erstellt  und  wird  nicht unterschrieben.",
    "Für weitergehende Fragen wenden Sie sich bitte an Ihr flatex-Service-Team.",
    "______________________________________________________________________________",
    "Seite 2/2",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Frankfurt  -  Amtsgericht Frankfurt am Main (HRB 105687)",
    "Vorsitzender des Aufsichtsrats: Martin Korbmacher  -  Vorstand: Frank Niehage (Vorsitzender), Jörn Engelmann"
  ]
]

```

</p></details>

## Community profile

stefan@sels.com

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #268: [flatex] sammelauftrag
## Document
<details><summary>20200522_Orderbestaetigung_1002064799_153835191.pdf</summary><p>

```json
[
  [
    "0113303470000101",
    "2000001538351910",
    "flatex Bank AG",
    "Postfach 100551",
    "41405 Neuss",
    "USt-IdNr.: DE 246 786 363",
    "Kundenservice:",
    "Tel.: +49 (0)9221 - 7035898",
    "E-Mail: kunden@flatex.de",
    "flatex Bank AG -  Rotfeder-Ring 7 - 60327 Frankfurt am Main",
    "0303472000001538351910",
    "Frankfurt, 22.05.2020",
    "Herrn",
    "Vcigpe Ijkl",
    "Süuvdyuxb. 59",
    "39134 Kjznqa",
    "Sammelauftragsbestätigung",
    "Pasy Wiveersoswv: 3415837666",
    "Cqcyvalgzvfg:     Tridmt Kayd",
    "------------------------------------------------------------------------------",
    "Auftrags-Nr  ISIN           Wertpapierbezeichnung       Ausf.platz/-art",
    "WKN            Geschäftsart/Auftr.Datum    Stücke/Nominale",
    "------------------------------------------------------------------------------",
    "146305841    US88160R1014   TESLA INC. DL -,001         NASDAQ",
    "A1CX3T         Kauf vom 21.05.2020         6,00 St.",
    "Gültig bis:                 29.05.2020",
    "Limit:                      800,000 USD",
    "------------------------------------------------------------------------------",
    "Bitte prüfen Sie diese Auftragsbestätigung auf Richtigkeit und Vollständigkeit",
    "Etwaige Einwendungen gegen diese Auftragsbestätigung müssen unverzüglich nach",
    "Zugang bei der Bank erhoben werden. Die Unterlassung rechtzeitiger Einwendung",
    "gilt als Genehmigung.",
    "Diese  Mitteilung  ist  maschinell  erstellt  und  wird  nicht unterschrieben.",
    "Für weitergehende Fragen wenden Sie sich bitte an Ihr flatex-Service-Team.",
    "______________________________________________________________________________",
    "Seite 1/1",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Frankfurt  -  Amtsgericht Frankfurt am Main (HRB 105687)",
    "Vorsitzender des Aufsichtsrats: Martin Korbmacher  -  Vorstand: Frank Niehage (Vorsitzender), Jörn Engelmann"
  ]
]

```

</p></details>

## Community profile

tronicum

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #291: [flatex] Fondsertrag wird nicht eingelesen
## Document
<details><summary>20201127_Fondsertragsausschuettung_31008997608_173115682.pdf</summary><p>

```json
[
  [
    "8857812154151396",
    "6841919572592320",
    "flatex Bank AG",
    "Kundenservice",
    "Opernring 1 / Top 736",
    "1010 Wien",
    "Tel.: +43 - (0)720 518 777",
    "Mail: info@flatex.at",
    "flatex Bank AG -  Opernring 1 / Top 736 -  A-1010 Wien",
    "0102262000001731156820",
    "Wien, 27.11.2020",
    "Herrn",
    "Ucydccdrl Pacrnsek",
    "Jjtfj Nqgteaof-Fabgt 1",
    "9977 Röeilyg",
    "ÖLZFJVLIOD",
    "Ertragsmitteilung - ausschüttender/teilthesaurierender Fonds",
    "Jrga Ocxucjudeqt: 13654705653",
    "Gofgflflcakl    : Hiicpgua, Ooyuhbkdl",
    "Nr.2099030810                ISHSII-MSCI EU.QUA.DV.EOD (IE00BYYHSM20/A2DRG4)",
    "St.             :           709,25    Bruttoausschüttung",
    "pro Stück          :       0,0824000 EUR",
    "Extag           :       12.11.2020    Bruttoausschüttung :           58,44 EUR",
    "Valuta          :       25.11.2020",
    "Bemessungsgrundlage:            0,00 EUR",
    "*Einbeh. Steuer     :            0,00 EUR",
    "Endbetrag          :           58,44 EUR",
    "* Einbehaltene Kapitalertragsteuer. Details dazu finden Sie im Steuerreport",
    "ajovd tni Pzzhoierqev-Nq.: 1366120877.",
    "Gbb Nmtlqtrobnk cky Ilajqyicw mhhrqal üfgz Wdc Zfrcv Iq.: 04795647788.",
    "Fondsinformationen:",
    "steuerpflichtiger Ertrag                                 :           58,44 EUR",
    "davon ausländische Erträge mit anrechenb. QSt         :            0,00 EUR",
    "anrechenbare ausländische Quellensteuer**                :            0,00 EUR",
    "**  ggf. mit einbeh. Steuer verrechnet",
    "Die  Gutschrift erfolgt  unter Vorbehalt  des  Eingangs.  Einwendungen  müssen",
    "unverzüglich  nach  Zugang  erhoben  werden.  Die  Unterlassung  rechtzeitiger",
    "Einwendung gilt als Genehmigung.",
    "Dieser   Beleg   ist    keine   Steuerbescheinigung.    Kapitalerträge   sind",
    "einkommensteuerpflichtig.",
    "Diese Mitteilung ist maschinell erstellt und wird nicht unterschrieben.",
    "Für weitergehende Fragen wenden Sie sich bitte an Ihr flatex-Service-Team.",
    "flatex Bank AG Niederlassung Österreich | Aktiengesellschaft | Opernring 1 / Top 736 | 1010 Wien | Handelsgericht Wien | FN 334642 x | DVR 4000544 | UID ATU 65140956",
    "Hauptniederlassung: flatex Bank AG | Rotfeder-Ring 7 | 60327 Frankfurt am Main (Deutschland) | Amtsgericht Frankfurt am Main | HRB 105687",
    "- Vorsitzender des Aufsichtsrats: Martin Korbmacher | Vorstand: Frank Niehage (Vors.), Jörn Engelmann, Steffen Jentsch -"
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #296: [flatex] DividendenAbrechnung kann nicht importiert werden
## Documents
<details><summary>20190510_Dividendeinlaend.WP_1012307329_119273080.pdf</summary><p>

```json
[
  [
    "0113102510000101",
    "2000001192730800",
    "flatex Bank AG",
    "Postfach 100551",
    "41405 Neuss",
    "USt-IdNr.: DE 246 786 363",
    "Kundenservice:",
    "Tel.: +49 (0)9221 - 7035898",
    "E-Mail: kunden@flatex.de",
    "flatex Bank AG -  Rotfeder-Ring 7 - 60327 Frankfurt am Main",
    "0102512000001192730800",
    "Frankfurt, 10.05.2019",
    "Herrn",
    "Manuel Wölfelschneider",
    "Hochheimer Str. 35",
    "67549 Worms",
    "Dividendengutschrift für inländische Wertpapiere",
    "Ihre Depotnummer: 1012307336",
    "Depotinhaber    : Wölfelschneider, Manuel",
    "Nr.1626100641         SILTRONIC AG NA O.N.               (DE000WAF3001/WAF300)",
    "St.             :           10,00      Bruttodividende",
    "pro Stück       :          5,0000 EUR",
    "Extag           :      08.05.2019      Bruttodividende :           50,00 EUR",
    "Zahlungstag     :      10.05.2019      Bemessungs-",
    "Valuta          :      10.05.2019      grundlage       :            0,00 EUR",
    "*Einbeh. Steuer  :            0,00 EUR",
    "Endbetrag       :           50,00 EUR",
    "* Enthalten sind folgende Steuern (negative Werte bedeuten Steuererstattung)",
    "Kapitalertragsteuer  :            0,00 EUR",
    "Solidaritätszuschlag :            0,00 EUR",
    "Kirchensteuer        :            0,00 EUR",
    "Details dazu inkl. evtl. angerechneter ausländischer Quellensteuer",
    "finden Sie im Steuerreport unter der Transaktion-Nr. : 1626100641",
    "Die Verrechnung des Endbetrages erfolgt über Ihr Konto Nr.: 1012307329",
    "Die  Gutschrift erfolgt  unter Vorbehalt  des  Eingangs.  Einwendungen  müssen",
    "unverzüglich  nach  Zugang  erhoben  werden.  Die  Unterlassung  rechtzeitiger",
    "Einwendung gilt als Genehmigung.",
    "Dieser   Beleg   ist    keine   Steuerbescheinigung.    Kapitalerträge   sind",
    "einkommensteuerpflichtig.",
    "Diese Mitteilung ist maschinell erstellt und wird nicht unterschrieben.",
    "Für weitergehende Fragen wenden Sie sich bitte an Ihr flatex-Service-Team.",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Frankfurt  -  Amtsgericht Frankfurt am Main (HRB 105687)",
    "Vorsitzender des Aufsichtsrats: Martin Korbmacher  -  Vorstand: Frank Niehage (Vorsitzender), Jörn Engelmann"
  ]
]

```

</p></details>

<details><summary>20200526_Dividendeinlaend.WP_1012307329_154115674.pdf</summary><p>

```json
[
  [
    "0113102510000101",
    "2000001541156740",
    "flatex Bank AG",
    "Postfach 100551",
    "41405 Neuss",
    "USt-IdNr.: DE 246 786 363",
    "Kundenservice:",
    "Tel.: +49 (0)9221 - 7035898",
    "E-Mail: kunden@flatex.de",
    "flatex Bank AG -  Rotfeder-Ring 7 - 60327 Frankfurt am Main",
    "0102512000001541156740",
    "Frankfurt, 26.05.2020",
    "Herrn",
    "Manuel Wölfelschneider",
    "Hochheimer Str. 35",
    "67549 Worms",
    "Dividendengutschrift für inländische Wertpapiere",
    "Ihre Depotnummer: 1012307336",
    "Depotinhaber    : Wölfelschneider, Manuel",
    "Nr.1912599368                  SAP SE O.N.               (DE0007164600/716460)",
    "St.             :           10,00      Bruttodividende",
    "pro Stück       :          1,5800 EUR",
    "Extag           :      21.05.2020      Bruttodividende :           15,80 EUR",
    "Zahlungstag     :      26.05.2020      Bemessungs-",
    "Valuta          :      26.05.2020      grundlage       :            0,00 EUR",
    "*Einbeh. Steuer  :            0,00 EUR",
    "Endbetrag       :           15,80 EUR",
    "* Enthalten sind folgende Steuern (negative Werte bedeuten Steuererstattung)",
    "Kapitalertragsteuer  :            0,00 EUR",
    "Solidaritätszuschlag :            0,00 EUR",
    "Kirchensteuer        :            0,00 EUR",
    "Details dazu inkl. evtl. angerechneter ausländischer Quellensteuer",
    "finden Sie im Steuerreport unter der Transaktion-Nr. : 1912599368",
    "Die Verrechnung des Endbetrages erfolgt über Ihr Konto Nr.: 1012307329",
    "Die  Gutschrift erfolgt  unter Vorbehalt  des  Eingangs.  Einwendungen  müssen",
    "unverzüglich  nach  Zugang  erhoben  werden.  Die  Unterlassung  rechtzeitiger",
    "Einwendung gilt als Genehmigung.",
    "Dieser   Beleg   ist    keine   Steuerbescheinigung.    Kapitalerträge   sind",
    "einkommensteuerpflichtig.",
    "Diese Mitteilung ist maschinell erstellt und wird nicht unterschrieben.",
    "Für weitergehende Fragen wenden Sie sich bitte an Ihr flatex-Service-Team.",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Frankfurt  -  Amtsgericht Frankfurt am Main (HRB 105687)",
    "Vorsitzender des Aufsichtsrats: Martin Korbmacher  -  Vorstand: Frank Niehage (Vorsitzender), Jörn Engelmann"
  ]
]

```

</p></details>

<details><summary>20200701_Dividendeinlaend.WP_1012307329_157570180.pdf</summary><p>

```json
[
  [
    "0113102510000101",
    "2000001575701800",
    "flatex Bank AG",
    "Postfach 100551",
    "41405 Neuss",
    "USt-IdNr.: DE 246 786 363",
    "Kundenservice:",
    "Tel.: +49 (0)9221 - 7035898",
    "E-Mail: kunden@flatex.de",
    "flatex Bank AG -  Rotfeder-Ring 7 - 60327 Frankfurt am Main",
    "0102512000001575701800",
    "Frankfurt, 01.07.2020",
    "Herrn",
    "Manuel Wölfelschneider",
    "Hochheimer Str. 35",
    "67549 Worms",
    "Dividendengutschrift für inländische Wertpapiere",
    "Ihre Depotnummer: 1012307336",
    "Depotinhaber    : Wölfelschneider, Manuel",
    "Nr.1953592560       SILTRONIC AG NA O.N.               (DE000WAF3001/WAF300)",
    "St.             :           10,00      Bruttodividende",
    "pro Stück       :          3,0000 EUR",
    "Extag           :      29.06.2020      Bruttodividende :           30,00 EUR",
    "Zahlungstag     :      01.07.2020      Bemessungs-",
    "Valuta          :      01.07.2020      grundlage       :            0,00 EUR",
    "*Einbeh. Steuer  :            0,00 EUR",
    "Endbetrag       :           30,00 EUR",
    "* Enthalten sind folgende Steuern (negative Werte bedeuten Steuererstattung)",
    "Kapitalertragsteuer  :            0,00 EUR",
    "Solidaritätszuschlag :            0,00 EUR",
    "Kirchensteuer        :            0,00 EUR",
    "Details dazu inkl. evtl. angerechneter ausländischer Quellensteuer",
    "finden Sie im Steuerreport unter der Transaktion-Nr. : 1953592560",
    "Die Verrechnung des Endbetrages erfolgt über Ihr Konto Nr.: 1012307329",
    "Die  Gutschrift erfolgt  unter Vorbehalt  des  Eingangs.  Einwendungen  müssen",
    "unverzüglich  nach  Zugang  erhoben  werden.  Die  Unterlassung  rechtzeitiger",
    "Einwendung gilt als Genehmigung.",
    "Dieser   Beleg   ist    keine   Steuerbescheinigung.    Kapitalerträge   sind",
    "einkommensteuerpflichtig.",
    "Diese Mitteilung ist maschinell erstellt und wird nicht unterschrieben.",
    "Für weitergehende Fragen wenden Sie sich bitte an Ihr flatex-Service-Team.",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Frankfurt  -  Amtsgericht Frankfurt am Main (HRB 105687)",
    "Vorsitzender des Aufsichtsrats: Martin Korbmacher  -  Vorstand: Frank Niehage (Vorsitzender), Jörn Engelmann"
  ]
]

```

</p></details>

<details><summary>20200804_Dividendeinlaend.WP_1012307329_161535388.pdf</summary><p>

```json
[
  [
    "0113102510000101",
    "2000001615353880",
    "flatex Bank AG",
    "Postfach 100551",
    "41405 Neuss",
    "USt-IdNr.: DE 246 786 363",
    "Kundenservice:",
    "Tel.: +49 (0)9221 - 7035898",
    "E-Mail: kunden@flatex.de",
    "flatex Bank AG -  Rotfeder-Ring 7 - 60327 Frankfurt am Main",
    "0102512000001615353880",
    "Frankfurt, 04.08.2020",
    "Herrn",
    "Manuel Wölfelschneider",
    "Hochheimer Str. 35",
    "67549 Worms",
    "Dividendengutschrift für inländische Wertpapiere",
    "Ihre Depotnummer: 1012307336",
    "Depotinhaber    : Wölfelschneider, Manuel",
    "Nr.1984531515          COVESTRO AG  O.N.               (DE0006062144/606214)",
    "St.             :           20,00      Bruttodividende",
    "pro Stück       :          1,2000 EUR",
    "Extag           :      31.07.2020      Bruttodividende :           24,00 EUR",
    "Zahlungstag     :      04.08.2020      Bemessungs-",
    "Valuta          :      04.08.2020      grundlage       :            0,00 EUR",
    "*Einbeh. Steuer  :            0,00 EUR",
    "Endbetrag       :           24,00 EUR",
    "* Enthalten sind folgende Steuern (negative Werte bedeuten Steuererstattung)",
    "Kapitalertragsteuer  :            0,00 EUR",
    "Solidaritätszuschlag :            0,00 EUR",
    "Kirchensteuer        :            0,00 EUR",
    "Details dazu inkl. evtl. angerechneter ausländischer Quellensteuer",
    "finden Sie im Steuerreport unter der Transaktion-Nr. : 1984531515",
    "Die Verrechnung des Endbetrages erfolgt über Ihr Konto Nr.: 1012307329",
    "Die  Gutschrift erfolgt  unter Vorbehalt  des  Eingangs.  Einwendungen  müssen",
    "unverzüglich  nach  Zugang  erhoben  werden.  Die  Unterlassung  rechtzeitiger",
    "Einwendung gilt als Genehmigung.",
    "Dieser   Beleg   ist    keine   Steuerbescheinigung.    Kapitalerträge   sind",
    "einkommensteuerpflichtig.",
    "Diese Mitteilung ist maschinell erstellt und wird nicht unterschrieben.",
    "Für weitergehende Fragen wenden Sie sich bitte an Ihr flatex-Service-Team.",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Frankfurt  -  Amtsgericht Frankfurt am Main (HRB 105687)",
    "Vorsitzender des Aufsichtsrats: Martin Korbmacher  -  Vorstand: Frank Niehage (Vorsitzender), Jörn Engelmann"
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #336: [flatex.at] Kauf in 2017 US3696041033
## Document
<details><summary>20170613_Wertpapierabrechnung_31009945663_78239825.pdf</summary><p>

```json
[
  [
    "7600982882402418",
    "9849584910561468",
    "biw AG Österreich",
    "Kundenservice",
    "Opernring 1 / Top 736",
    "1010 Wien",
    "Tel.: +43 - (0)720 518 777",
    "Mail: info@flatex.at",
    "biw AG -  Opernring 1 / Top 736 -  A-1010 Wien",
    "0303502000000782398250",
    "Wien, den 13.06.2017",
    "Zdsel",
    "Vxxdy Klojam",
    "Xkbnunstmdrnb 81/37",
    "2585 Kgzr",
    "ÖYAORPNRXW",
    "Sammelabrechnung (Wertpapierkauf/-verkauf)",
    "Rrol Lvsfmfymyvk: 60793672942",
    "Jgqjisgzgycn:     Gepyr Frczbx",
    "Nr.95705278/1  Kauf            GENL EL. CO.      DL -,06 (US3696041033/851144)",
    "Ordervolumen  : 90,00 St.               Handelsplatz  :              Tradegate",
    "davon ausgef. : 90,00 St.               Schlusstag    :  12.06.2017, 16:00 Uhr",
    "Kurs          : 25,8010 EUR             Kurswert      :           2.322,09 EUR",
    "Devisenkurs   :                         Provision     :",
    "Bew-Faktor    : 1,0000                  Eigene Spesen :",
    "Verwahrart    : GS-Verwahrung          *Fremde Spesen :",
    "Lagerstelle   : Clearstream Nat.",
    "Lagerland     : USA                   **Einbeh. Steuer:               0,00 EUR",
    "Valuta        : 14.06.2017              Endbetrag     :          -2.322,09 EUR",
    "*   Enthalten sind folgende Gebühren    Courtage      :               0,00 EUR",
    "Tradinggebühr :               0,00 EUR",
    "Regulierung   :               0,00 EUR",
    "Schlussnoten  :               0,00 EUR",
    "Sonstige      :               0,00 EUR",
    "**  Einbehaltene Kapitalertragsteuer. Details dazu finden Sie im Steuerreport",
    "suobs pwr Nrdwwokvuha-Zy.: 8246930569.",
    "Wgz Uwdurkgmvow rzk Hrmxyqfäox vkbslcf üibo Yrp Pnejh Pn.: 74622932256",
    "______________________________________________________________________________",
    "Seite 1/2",
    "biw Bank für Investments und Wertpapiere AG Niederlassung Österreich",
    "Opernring 1 / Top 736 | 1010 Wien | Handelsgericht Wien | FN 334642 x | DVR 4000544 | UID ATU 65140956 | Aktiengesellschaft",
    "Hauptniederlassung: biw Bank für Investments und Wertpapiere AG | Rotfeder-Ring 7 | 60327 Frankfurt am Main (Deutschland) | Amtsgericht Frankfurt am Main | HRB 105687"
  ],
  [
    "5458520489582546",
    "Die Wertpapiere sowie den Gegenwert werden wir entsprechend der Abrechnung mit",
    "dem  angegebenen  Valutatag  buchen.  Bitte prüfen Sie  diese  Abrechnung  auf",
    "Richtigkeit und Vollständigkeit.  Etwaige Einwendungen gegen diese  Abrechnung",
    "müssen unverzüglich  nach Zugang bei der Bank  erhoben werden. Die",
    "Unterlassung rechtzeitiger Einwendung gilt als Genehmigung. Bitte beachten",
    "Sie mögliche Hinweise des Emittenten  hinsichtlich vorzeitiger Fälligstellung,",
    "beispielsweise wegen Knock-Out, in den jeweiligen Optionsscheinbedingungen und",
    "informieren Sie sich rechtzeitig, welche spezielle Fälligkeitsregelung auf die",
    "von Ihnen gehaltenen Wertpapiere zutreffen. Kapitalerträge sind ESt-pflichtig.",
    "Diese  Mitteilung  ist  maschinell  erstellt  und  wird  nicht unterschrieben.",
    "Für weitergehende Fragen wenden Sie sich bitte an Ihr flatex-Service-Team.",
    "______________________________________________________________________________",
    "Seite 2/2",
    "biw Bank für Investments und Wertpapiere AG Niederlassung Österreich",
    "Opernring 1 / Top 736 | 1010 Wien | Handelsgericht Wien | FN 334642 x | DVR 4000544 | UID ATU 65140956 | Aktiengesellschaft",
    "Hauptniederlassung: biw Bank für Investments und Wertpapiere AG | Rotfeder-Ring 7 | 60327 Frankfurt am Main (Deutschland) | Amtsgericht Frankfurt am Main | HRB 105687"
  ]
]

```

</p></details>

## Community profile

https://community.tresor.one/u/929c9d86

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #361: flatex - Einlesen nicht möglich
## Document
<details><summary>20200724_Wertpapierabrechnung_1016015693_160319823.pdf</summary><p>

```json
[
  [
    "0113303500000101",
    "2000001603198230",
    "flatex Bank AG",
    "Postfach 100551",
    "41405 Neuss",
    "USt-IdNr.: DE 246 786 363",
    "Kundenservice:",
    "Tel.: +49 (0)9221 - 7035898",
    "E-Mail: kunden@flatex.de",
    "flatex Bank AG -  Rotfeder-Ring 7 - 60327 Frankfurt am Main",
    "5292874738154930082024",
    "Frankfurt, 24.07.2020",
    "Qiuiq",
    "Hpha Nnnpbov",
    "Hobxrqjwgs 4",
    "2835 Dhwsvzyn",
    "EIKCGNQ",
    "Sammelabrechnung (Wertpapierkauf/-verkauf)",
    "Likk Sljfeagbunf: 7201199266",
    "Cekdemrnwzex:     Ohid Vgkbkoi",
    "Nr.135238876/1    Kauf         NEL ASA            NK-,20 (NO0010081235/A0B733)",
    "Ordervolumen  : 100,00 St.              Handelsplatz  :              Tradegate",
    "davon ausgef. : 100,00 St.              Schlusstag    :      23.07.2020, 16:52",
    "Kurs          : 1,7495 EUR              Kurswert      :             174,95 EUR",
    "Devisenkurs   :                         Provision     :               3,80 EUR",
    "Bew-Faktor    : 1,0000                  Eigene Spesen :",
    "Verwahrart    : Wertpapierrechnung     *Fremde Spesen :               2,00 EUR",
    "Lagerstelle   : Clearstream Lux.",
    "Lagerland     : Norwegen                Bemessungs-",
    "Gewinn/Verlust: 0,00 EUR                grundlage     :               0,00 EUR",
    "Valuta        : 27.07.2020            **Einbeh. Steuer:               0,00 EUR",
    "Endbetrag     :            -180,75 EUR",
    "*   Enthalten sind folgende Gebühren",
    "Courtage                :             0,00 EUR",
    "Tradinggebühr           :             0,00 EUR",
    "Regulierung             :             2,00 EUR",
    "Schlussnoten            :             0,00 EUR",
    "Finanztransaktionssteuer:             0,00 EUR",
    "Sonstige                :             0,00 EUR",
    "**  Enthalten sind folgende Steuern (negative Werte bedeuten Steuererstattung)",
    "Kapitalertragsteuer   :               0,00 EUR",
    "Solidaritätszuschlag  :               0,00 EUR",
    "Kirchensteuer         :               0,00 EUR",
    "Serf. Glkfzdt pnsr cpewqw Lue vy Sibzyiivwzys anhce njl Sktvgmdctyz-Zu.:",
    "8053499504.",
    "Las Sdygsxfvkgh dei Famsphrävp rbgzect üjpc Qqw Mpfcf Ec.: 8183430434",
    "______________________________________________________________________________",
    "Seite 1/2",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Frankfurt  -  Amtsgericht Frankfurt am Main (HRB 105687)",
    "Vorsitzender des Aufsichtsrats: Martin Korbmacher  -  Vorstand: Frank Niehage (Vorsitzender), Jörn Engelmann"
  ],
  [
    "2000001603198230",
    "Die Wertpapiere sowie den Gegenwert werden wir entsprechend der Abrechnung mit",
    "dem angegebenen Valutatag buchen. Bitte prüfen Sie diese Abrechnung auf",
    "Richtigkeit und Vollständigkeit. Etwaige Einwendungen gegen diese Abrechnung",
    "müssen unverzüglich nach Zugang bei der Bank erhoben werden. Die",
    "Unterlassung rechtzeitiger Einwendung gilt als Genehmigung. Bitte beachten",
    "Sie mögliche Hinweise des Emittenten hinsichtlich vorzeitiger Fälligstellung,",
    "beispielsweise wegen Knock-Out, in den jeweiligen Optionsscheinbedingungen und",
    "informieren Sie sich rechtzeitig, welche spezielle Fälligkeitsregelung auf die",
    "von Ihnen gehaltenen Wertpapiere zutreffen. Kapitalerträge sind ESt-pflichtig.",
    "Diese Mitteilung ist maschinell erstellt und wird nicht unterschrieben.",
    "Für weitergehende Fragen wenden Sie sich bitte an Ihr flatex-Service-Team.",
    "______________________________________________________________________________",
    "Seite 2/2",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Frankfurt  -  Amtsgericht Frankfurt am Main (HRB 105687)",
    "Vorsitzender des Aufsichtsrats: Martin Korbmacher  -  Vorstand: Frank Niehage (Vorsitzender), Jörn Engelmann"
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #499: [Broker FlatEx] es kann keine Aktivitäten aus der Abrechnung importiert werden.
## Document
<details><summary>20170904_KaufFondsZertifikate_1009667986_81834724.pdf</summary><p>

```json
[
  [
    "0113202270000102",
    "2000000818347240",
    "FinTech Group Bank AG",
    "Hausbroicher Str. 222",
    "47877 Willich",
    "USt-IdNr.: DE 246 786 363",
    "Kundenservice:",
    "Tel.: +49 (0)9221 - 7035898",
    "E-Mail: kunden@flatex.de",
    "FinTech Group Bank AG -  Rotfeder-Ring 7 - 60327 Frankfurt am Main",
    "0202272000000818347240",
    "Frankfurt,        04.09.2017",
    "Auftragsdatum     01.09.2017",
    "Schlusstag        01.09.2017",
    "Ausführungszeit   00:00 Uhr",
    "Valuta            06.09.2017",
    "Auftragsnummer    97260604/1",
    "Ausf.platz/-art   KAG/außerbörsl.",
    "Lybln",
    "Ew. Zqt Dmbr",
    "Ynwnsxzskob 62",
    "05762 Gswjwkt",
    "Wertpapierabrechnung Kauf Fonds/Zertifikate",
    "Eezl Fjbhngsumwn  2712486125",
    "Cyurxstjcags      Zklc, Tjp",
    "Nr.97260604/1  Kauf             ISHARES TECDAX UCITS ETF (DE0005933972/593397)",
    "Ausgeführt     2,951757 St.            Kurswert       EUR                63,10",
    "Kurs           21,377100 EUR           Provision      EUR                 0,90",
    "Devisenkurs                            Eigene Spesen",
    "Verwahrart     GS-Verwahrung          *Fremde Spesen",
    "Lagerstelle    Clearstream Nat.",
    "Lagerland      Deutschland",
    "Bemessungs-",
    "Gewinn/Verlust 0,00 EUR                grundlage      EUR                 0,00",
    "**Einbeh. Steuer EUR                 0,00",
    "Endbetrag      EUR               -64,00",
    "* Enthalten sind folgende Gebühren     Courtage       EUR                 0,00",
    "Tradinggebühr  EUR                 0,00",
    "Regulierung    EUR                 0,00",
    "Schlussnoten   EUR                 0,00",
    "Sonstige       EUR                 0,00",
    "**  Enthalten sind folgende Steuern (negative Werte bedeuten Steuererstattung)",
    "Kapitalertragsteuer  EUR                 0,00",
    "Solidaritätszuschlag EUR                 0,00",
    "Kirchensteuer        EUR                 0,00",
    "Evtl. Details dazu finden Sie im Steuerreport unter der Transaktion-Nr.:",
    "1271071272.",
    "Der Kurswert enthält 0,000% regulären Ausgabeaufschlag (AA).",
    "Rabattierung   keine                   gezahlter AA   EUR                 0,00",
    "Kurs           21,3771 EUR             Kurswert       EUR                63,10",
    "ausschüttungsgleiche Erträge je Anteil EUR         0,6682708000",
    "ausschüttungsgleiche Erträge gesamt    EUR                 1,97",
    "Die Verrechnung des Endbetrags erfolgt über Ihr Konto Nr.: 1009667986",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Frankfurt  -  Amtsgericht Frankfurt am Main (HRB 105687)",
    "Vorsitzender des Aufsichtsrats: Martin Korbmacher  -  Vorstand: Frank Niehage (Vorsitzender), Bernd Würfel"
  ],
  [
    "0113202270000202",
    "2000000818347240",
    "Die Wertpapiere sowie den Gegenwert werden wir entsprechend der Abrechnung mit",
    "dem angegebenen Valutatag buchen. Bitte prüfen Sie diese Abrechnung auf",
    "Richtigkeit und Vollständigkeit. Etwaige Einwendungen gegen diese Abrechnung",
    "müssen unverzüglich nach Zugang bei der Bank erhoben werden. Die",
    "Unterlassung rechtzeitiger Einwendung gilt als Genehmigung. Bitte beachten",
    "Sie mögliche Hinweise des Emittenten hinsichtlich vorzeitiger Fälligstellung,",
    "beispielsweise wegen Knock-Out, in den jeweiligen Optionsscheinbedingungen und",
    "informieren Sie sich rechtzeitig, welche spezielle Fälligkeitsregelung auf die",
    "von Ihnen gehaltenen Wertpapiere zutreffen. Kapitalerträge sind ESt-pflichtig.",
    "Diese Mitteilung ist maschinell erstellt und wird nicht unterschrieben.",
    "Für weitergehende Fragen wenden Sie sich bitte an Ihr flatex-Service-Team.",
    "Viel Freiheit für wenig Zins - Ihr flatex flex-Kredit zu günstigen",
    "Konditionen: 3,90% p.a.",
    "Weitere Informationen finden Sie unter: www.flatex.de/kredit/",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Frankfurt  -  Amtsgericht Frankfurt am Main (HRB 105687)",
    "Vorsitzender des Aufsichtsrats: Martin Korbmacher  -  Vorstand: Frank Niehage (Vorsitzender), Bernd Würfel"
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #500: [Broke FlatEx] es wurde keinen Wertpapier Kauf/Verkauf aus der Abrechnung importiert.
## Document
<details><summary>20180103_KaufFondsZertifikate_1009667986_87149491.pdf</summary><p>

```json
[
  [
    "0113202270000102",
    "2000000871494910",
    "FinTech Group Bank AG",
    "Hausbroicher Str. 222",
    "47877 Willich",
    "USt-IdNr.: DE 246 786 363",
    "Kundenservice:",
    "Tel.: +49 (0)9221 - 7035898",
    "E-Mail: kunden@flatex.de",
    "FinTech Group Bank AG -  Rotfeder-Ring 7 - 60327 Frankfurt am Main",
    "0202272000000871494910",
    "Frankfurt,        03.01.2018",
    "Auftragsdatum     02.01.2018",
    "Schlusstag        02.01.2018",
    "Ausführungszeit   00:00 Uhr",
    "Valuta            05.01.2018",
    "Auftragsnummer    106023836/1",
    "Ausf.platz/-art   KAG/außerbörsl.",
    "Qvvoc",
    "Fh. Unz Tkei",
    "Gpldywbavyr 73",
    "58876 Ygashae",
    "Wertpapierabrechnung Kauf Fonds/Zertifikate",
    "Syxg Dzdiuwgyggr  4249235413",
    "Ddgqutphnqto      Ilzf, Dbi",
    "Nr.106023836/1 Kauf             ISHARES TECDAX UCITS ETF (DE0005933972/593397)",
    "Ausgeführt     2,649551 St.            Kurswert       EUR                62,50",
    "Kurs           23,588900 EUR           Provision      EUR                 1,50",
    "Devisenkurs                            Eigene Spesen",
    "Verwahrart     GS-Verwahrung          *Fremde Spesen",
    "Lagerstelle    Clearstream Nat.",
    "Lagerland      Deutschland",
    "Bemessungs-",
    "Gewinn/Verlust 0,00 EUR                grundlage      EUR                 0,00",
    "**Einbeh. Steuer EUR                 0,00",
    "Endbetrag      EUR               -64,00",
    "* Enthalten sind folgende Gebühren     Courtage       EUR                 0,00",
    "Tradinggebühr  EUR                 0,00",
    "Regulierung    EUR                 0,00",
    "Schlussnoten   EUR                 0,00",
    "Sonstige       EUR                 0,00",
    "**  Enthalten sind folgende Steuern (negative Werte bedeuten Steuererstattung)",
    "Kapitalertragsteuer  EUR                 0,00",
    "Solidaritätszuschlag EUR                 0,00",
    "Kirchensteuer        EUR                 0,00",
    "Evtl. Details dazu finden Sie im Steuerreport unter der Transaktion-Nr.:",
    "1340898930.",
    "Der Kurswert enthält 0,000% regulären Ausgabeaufschlag (AA).",
    "Rabattierung   keine                   gezahlter AA   EUR                 0,00",
    "Kurs           23,5889 EUR             Kurswert       EUR                62,50",
    "Die Verrechnung des Endbetrags erfolgt über Ihr Konto Nr.: 1009667986",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Frankfurt  -  Amtsgericht Frankfurt am Main (HRB 105687)",
    "Vorsitzender des Aufsichtsrats: Martin Korbmacher  -  Vorstand: Frank Niehage (Vorsitzender), Bernd Würfel"
  ],
  [
    "0113202270000202",
    "2000000871494910",
    "Die Wertpapiere sowie den Gegenwert werden wir entsprechend der Abrechnung mit",
    "dem angegebenen Valutatag buchen. Bitte prüfen Sie diese Abrechnung auf",
    "Richtigkeit und Vollständigkeit. Etwaige Einwendungen gegen diese Abrechnung",
    "müssen unverzüglich nach Zugang bei der Bank erhoben werden. Die",
    "Unterlassung rechtzeitiger Einwendung gilt als Genehmigung. Bitte beachten",
    "Sie mögliche Hinweise des Emittenten hinsichtlich vorzeitiger Fälligstellung,",
    "beispielsweise wegen Knock-Out, in den jeweiligen Optionsscheinbedingungen und",
    "informieren Sie sich rechtzeitig, welche spezielle Fälligkeitsregelung auf die",
    "von Ihnen gehaltenen Wertpapiere zutreffen. Kapitalerträge sind ESt-pflichtig.",
    "Diese Mitteilung ist maschinell erstellt und wird nicht unterschrieben.",
    "Für weitergehende Fragen wenden Sie sich bitte an Ihr flatex-Service-Team.",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Frankfurt  -  Amtsgericht Frankfurt am Main (HRB 105687)",
    "Vorsitzender des Aufsichtsrats: Martin Korbmacher  -  Vorstand: Frank Niehage (Vorsitzender), Bernd Würfel"
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #501: [FlatEx] Fondausschüttung wurde  nicht aus Abrechnung importiert.
## Document
<details><summary>20180824_Fondsertragsausschuettung_1009667986_101444288.pdf</summary><p>

```json
[
  [
    "0113102260000101",
    "2000001014442880",
    "FinTech Group Bank AG",
    "Postfach 100551",
    "41405 Neuss",
    "USt-IdNr.: DE 246 786 363",
    "Kundenservice:",
    "Tel.: +49 (0)9221 - 7035898",
    "E-Mail: kunden@flatex.de",
    "FinTech Group Bank AG -  Rotfeder-Ring 7 - 60327 Frankfurt am Main",
    "0102262000001014442880",
    "Frankfurt,        24.08.2018",
    "Vatfh",
    "Go. Eez Mhhk",
    "Nlfkoxevcyl 62",
    "62788 Ekwrhsq",
    "Ertragsmitteilung - ausschüttender/teilthesaurierender Fonds",
    "Nsmi Rgeklvbwjlu: 5317609550",
    "Nkuwsnfvtcht    : Czaj, Ocw",
    "Nr.1479472553                  COMST.-NASDAQ-100 U.ETF I (LU0378449770/ETF011)",
    "St.             :       25,28          Bruttoausschüttung",
    "pro Stück          :       0,4225 USD",
    "Extag           :  21.08.2018          Bruttoausschüttung :        10,68 USD",
    "Valuta          :  23.08.2018",
    "Bemessungs-",
    "grundlage          :         0,00 EUR",
    "Devisenkurs     :    1,157900         *Einbeh. Steuer     :         0,00 EUR",
    "Teilfreist.-satz:       30,00 %        Teilfreistellung   :         3,20 USD",
    "Endbetrag          :         9,22 EUR",
    "* Enthalten sind folgende Steuern (negative Werte bedeuten Steuererstattung)",
    "Kapitalertragsteuer  :         0,00 EUR",
    "Solidaritätszuschlag :         0,00 EUR",
    "Kirchensteuer        :         0,00 EUR",
    "Details dazu inkl. evtl. angerechneter ausländischer Quellensteuer",
    "finden Sie im Steuerreport unter der Transaktion-Nr.: 1479472553.",
    "Die Verrechnung des Endbetrages erfolgt über Ihr Konto Nr.:  1009667986",
    "Fondsinformationen:",
    "steuerpflichtiger Ertrag                                  :         7,48 USD",
    "davon ausländische Erträge mit anrechenb. QSt          :         0,00 USD",
    "ausländische Erträge mit anrechenb. fikt. QSt    :         0,00 USD",
    "anrechenbare ausländische Quellensteuer**                 :         0,00 USD",
    "**   ggf. mit einbeh. Steuer verrechnet und/oder Quellensteuer-Topf zugeführt",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Frankfurt  -  Amtsgericht Frankfurt am Main (HRB 105687)",
    "Vorsitzender des Aufsichtsrats: Martin Korbmacher  -  Vorstand: Frank Niehage (Vorsitzender), Bernd Würfel"
  ],
  [
    "2000001014442880",
    "Die  Gutschrift erfolgt  unter Vorbehalt  des  Eingangs.  Einwendungen  müssen",
    "unverzüglich  nach  Zugang  erhoben  werden.  Die  Unterlassung  rechtzeitiger",
    "Einwendung gilt als Genehmigung.",
    "Dieser   Beleg   ist    keine   Steuerbescheinigung.    Kapitalerträge   sind",
    "einkommensteuerpflichtig.",
    "Diese Mitteilung ist maschinell erstellt und wird nicht unterschrieben.",
    "Für weitergehende Fragen wenden Sie sich bitte an Ihr flatex-Service-Team.",
    "BLZ 101 308 00 / BIC: BIWBDE33XXX  -  Aktiengesellschaft, Sitz Frankfurt  -  Amtsgericht Frankfurt am Main (HRB 105687)",
    "Vorsitzender des Aufsichtsrats: Martin Korbmacher  -  Vorstand: Frank Niehage (Vorsitzender), Bernd Würfel"
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

### PR DESCRIPTION
**Pull request by dredav**
- Add new document format
  - Fix #499
  - Fix #500
- Fix error with payout from etf in foreign currency
  - Fix #501
- Fix error with payout form etf in EUR
  - Fix #291
- Add support for the old bank name
  - Fix #256
  - Fix #336
- Can parsed with one of the above fixes:
  - Fix #361
  - Fix #296
- Ignore order confirmation documents with status code `7`
  - Fix #267
  - Fix #268

### CODE REVIEW

File: src/brokers/flatex.js [hunk 1]
```diff
@@ -103,35 +128,63 @@ const findPrice = (textArr, startLineNumber) =>
...
+  // In the old format from 2018 the line contains 'Kurswert       EUR                62,50'
+  let value = getTableValueByKey(content, startLineNumber, term, 1);
+
+  if (/[A-Z]{3}/.test(value)) {
+    value = getTableValueByKey(content, startLineNumber, term, 2);
+  }
+
+  return value;
+};
+
```
Comment (SirGibihm) [inline src/brokers/flatex.js:149]: IMO Helper functions such as this should always be the first functions within a .js file but thats just an opionion

**Review by SirGibihm — APPROVED** [review]
Looks good to me!
