### PR TITLE
[ebase] Multiple fixes

### LINKED ISSUE #243: ebase Umsätze werden nicht vollständig übernommen
von den 12 Umsätzen werden nur 3 importiert.

Danke für eine Rückmeldung

## Document
<details><summary>Umsätze 26730333 2020-11-16.pdf</summary><p>

```json
[
  [
    "Umsätze",
    "im Zeitraum: 01.01.2020 -  16.11.2020",
    "16.11.2020 09:24 Uhr",
    "ebase Depot flex standard  99126730333",
    "Depotinhaber: Ulrich Johann",
    "Bestand: 6.235,84 EUR",
    "Umsatzarten:",
    "Zugang",
    "Abgang",
    "Fondsertrag / Vorabpauschale",
    "Sonstige Umsätze",
    "Pos.",
    "Umsatzart / Bezeichnung",
    "ISIN",
    "Buchungsdatum",
    "Anteile",
    "Kurs /",
    "Kursdatum",
    "Devisenkurs",
    "Betrag",
    "19",
    "Kauf",
    "LYXOR World Water (DR) UCITS ETF - Dist",
    "FR0010527275",
    "27.10.2020",
    "0,924609",
    "43,18 EUR",
    "27.10.2020",
    "40,00 EUR",
    "19",
    "Kauf",
    "LYXOR World Water (DR) UCITS ETF - Dist",
    "FR0010527275",
    "25.09.2020",
    "0,962078",
    "41,49 EUR",
    "25.09.2020",
    "40,00 EUR",
    "19",
    "Kauf",
    "LYXOR World Water (DR) UCITS ETF - Dist",
    "FR0010527275",
    "26.08.2020",
    "0,962603",
    "41,47 EUR",
    "26.08.2020",
    "40,00 EUR",
    "19",
    "Kauf",
    "LYXOR World Water (DR) UCITS ETF - Dist",
    "FR0010527275",
    "27.07.2020",
    "0,991801",
    "40,25 EUR",
    "27.07.2020",
    "40,00 EUR",
    "19",
    "Wiederanlage Fondsertrag",
    "LYXOR World Water (DR) UCITS ETF - Dist",
    "FR0010527275",
    "14.07.2020",
    "0,400721",
    "38,83 EUR",
    "14.07.2020",
    "15,56 EUR",
    "19",
    "Kauf",
    "LYXOR World Water (DR) UCITS ETF - Dist",
    "FR0010527275",
    "24.06.2020",
    "1,025404",
    "38,93 EUR",
    "24.06.2020",
    "40,00 EUR",
    "19",
    "Kauf",
    "LYXOR World Water (DR) UCITS ETF - Dist",
    "FR0010527275",
    "27.05.2020",
    "1,011657",
    "39,46 EUR",
    "27.05.2020",
    "40,00 EUR",
    "19",
    "Kauf",
    "LYXOR World Water (DR) UCITS ETF - Dist",
    "FR0010527275",
    "27.04.2020",
    "1,065349",
    "37,47 EUR",
    "27.04.2020",
    "40,00 EUR",
    "19",
    "Kauf",
    "LYXOR World Water (DR) UCITS ETF - Dist",
    "FR0010527275",
    "26.03.2020",
    "1,150844",
    "34,69 EUR",
    "26.03.2020",
    "40,00 EUR",
    "19",
    "Kauf",
    "LYXOR World Water (DR) UCITS ETF - Dist",
    "FR0010527275",
    "20.03.2020",
    "26,175306",
    "33,40 EUR",
    "20.03.2020",
    "876,00 EUR",
    "19",
    "Kauf",
    "LYXOR World Water (DR) UCITS ETF - Dist",
    "FR0010527275",
    "25.02.2020",
    "0,880292",
    "45,35 EUR",
    "25.02.2020",
    "40,00 EUR",
    "19",
    "Kauf",
    "LYXOR World Water (DR) UCITS ETF - Dist",
    "FR0010527275",
    "30.01.2020",
    "0,889077",
    "44,90 EUR",
    "30.01.2020",
    "40,00 EUR",
    "Seite",
    "1 von",
    "1"
  ]
]

```

</p></details>

## Community profile

https://community.tresor.one/u/ab166064

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #339: ebase Umsatz Kauf, Dividende und Wiederanlage der Dividende
## Document
<details><summary>Umsätze ebase.pdf</summary><p>

```json
[
  [
    "Umsätze",
    "im Zeitraum: 03.09.2020 -  03.12.2020",
    "03.12.2020 13:43 Uhr",
    "bgjhw Sdilp advp PF  04030224126",
    "Mhaggxmylirp: Ryna Sahnxmzoi",
    "Pbnblpz: 273,75 GLN",
    "Umsatzarten:",
    "Zugang",
    "Abgang",
    "Fondsertrag / Vorabpauschale",
    "Sonstige Umsätze",
    "Pos.",
    "Umsatzart / Bezeichnung",
    "ISIN",
    "Buchungsdatum",
    "Anteile",
    "Kurs /",
    "Kursdatum",
    "Devisenkurs",
    "Betrag",
    "02",
    "Kauf",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "13.11.2020",
    "0,635652",
    "74,01 USD",
    "12.11.2020",
    "1,178500",
    "EUR/USD",
    "40,00 EUR",
    "02",
    "Kauf",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "15.10.2020",
    "0,644632",
    "72,38 USD",
    "14.10.2020",
    "1,168800",
    "EUR/USD",
    "40,00 EUR",
    "02",
    "Wiederanlage Fondsertrag",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "12.10.2020",
    "0,039737",
    "71,47 USD",
    "09.10.2020",
    "2,84 USD",
    "02",
    "Fondsertrag (Ausschüttung)",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "08.10.2020",
    "02",
    "Kauf",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "15.09.2020",
    "0,671205",
    "70,59 USD",
    "14.09.2020",
    "1,186900",
    "EUR/USD",
    "40,00 EUR",
    "02",
    "Fondsumschichtung (Zugang)",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "11.09.2020",
    "0,515934",
    "70,89 USD",
    "10.09.2020",
    "1,182900",
    "EUR/USD",
    "30,98 EUR",
    "Seite",
    "1 von",
    "1"
  ]
]

```

</p></details>

## Community profile

https://community.tresor.one/u/afd52ae9

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #345: ebase Umsätze Wiederanlage Dividendengutschrift
## Document
<details><summary>Umsätze ebase.pdf</summary><p>

```json
[
  [
    "Umsätze",
    "im Zeitraum: 04.09.2020 -  04.12.2020",
    "04.12.2020 07:45 Uhr",
    "hrztj Xqrom jrqc ZP  81173242651",
    "Ckedgipjaxdu: Lbyo Swkreancz",
    "Bestand: 675,01 EUR",
    "Umsatzarten:",
    "Zugang",
    "Abgang",
    "Fondsertrag / Vorabpauschale",
    "Sonstige Umsätze",
    "Pos.",
    "Umsatzart / Bezeichnung",
    "ISIN",
    "Buchungsdatum",
    "Anteile",
    "Kurs /",
    "Kursdatum",
    "Devisenkurs",
    "Betrag",
    "01",
    "Verkauf",
    "ComStage MSCI World TRN UCITS ETF I",
    "LU0392494562",
    "02.12.2020",
    "-34,760494",
    "73,38 USD",
    "01.12.2020",
    "1,208200",
    "EUR/USD",
    "-2.054,53 EUR",
    "02",
    "Kauf",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "13.11.2020",
    "0,635652",
    "74,01 USD",
    "12.11.2020",
    "1,178500",
    "EUR/USD",
    "40,00 EUR",
    "02",
    "Kauf",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "15.10.2020",
    "0,644632",
    "72,38 USD",
    "14.10.2020",
    "1,168800",
    "EUR/USD",
    "40,00 EUR",
    "02",
    "Wiederanlage Fondsertrag",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "12.10.2020",
    "0,039737",
    "71,47 USD",
    "09.10.2020",
    "2,84 USD",
    "02",
    "Kauf",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "15.09.2020",
    "0,671205",
    "70,59 USD",
    "14.09.2020",
    "1,186900",
    "EUR/USD",
    "40,00 EUR",
    "01",
    "Fondsumschichtung (Abgang)",
    "ComStage MSCI World TRN UCITS ETF I",
    "LU0392494562",
    "11.09.2020",
    "-0,545977",
    "67,58 USD",
    "10.09.2020",
    "1,188900",
    "EUR/USD",
    "-30,98 EUR",
    "02",
    "Fondsumschichtung (Zugang)",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "11.09.2020",
    "0,515934",
    "70,89 USD",
    "10.09.2020",
    "1,182900",
    "EUR/USD",
    "30,98 EUR",
    "Seite",
    "1 von",
    "1"
  ]
]

```

</p></details>

## Community profile

https://community.tresor.one/u/afd52ae9

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #346: ebase Ergänzung zu #345
## Document
<details><summary>Umsätze ebase.pdf</summary><p>

```json
[
  [
    "Umsätze",
    "im Zeitraum: 04.09.2020 -  04.12.2020",
    "04.12.2020 07:51 Uhr",
    "xhnoe Sqitp qzlf YX  72122820590",
    "Xujknffaqgqf: Msxw Rygzgrmoq",
    "Bestand: 675,01 EUR",
    "Umsatzarten:",
    "Zugang",
    "Abgang",
    "Fondsertrag / Vorabpauschale",
    "Sonstige Umsätze",
    "Pos.",
    "Umsatzart / Bezeichnung",
    "ISIN",
    "Buchungsdatum",
    "Anteile",
    "Kurs /",
    "Kursdatum",
    "Devisenkurs",
    "Betrag",
    "01",
    "Verkauf",
    "ComStage MSCI World TRN UCITS ETF I",
    "LU0392494562",
    "02.12.2020",
    "-34,760494",
    "73,38 USD",
    "01.12.2020",
    "1,208200",
    "EUR/USD",
    "-2.054,53 EUR",
    "02",
    "Kauf",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "13.11.2020",
    "0,635652",
    "74,01 USD",
    "12.11.2020",
    "1,178500",
    "EUR/USD",
    "40,00 EUR",
    "02",
    "Kauf",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "15.10.2020",
    "0,644632",
    "72,38 USD",
    "14.10.2020",
    "1,168800",
    "EUR/USD",
    "40,00 EUR",
    "02",
    "Wiederanlage Fondsertrag",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "12.10.2020",
    "0,039737",
    "71,47 USD",
    "09.10.2020",
    "2,84 USD",
    "02",
    "Fondsertrag (Ausschüttung)",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "08.10.2020",
    "02",
    "Kauf",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "15.09.2020",
    "0,671205",
    "70,59 USD",
    "14.09.2020",
    "1,186900",
    "EUR/USD",
    "40,00 EUR",
    "01",
    "Fondsumschichtung (Abgang)",
    "ComStage MSCI World TRN UCITS ETF I",
    "LU0392494562",
    "11.09.2020",
    "-0,545977",
    "67,58 USD",
    "10.09.2020",
    "1,188900",
    "EUR/USD",
    "-30,98 EUR",
    "02",
    "Fondsumschichtung (Zugang)",
    "Vanguard FTSE Developed World UCITS ETF",
    "IE00BKX55T58",
    "11.09.2020",
    "0,515934",
    "70,89 USD",
    "10.09.2020",
    "1,182900",
    "EUR/USD",
    "30,98 EUR",
    "Seite",
    "1 von",
    "1"
  ]
]

```

</p></details>

## Community profile

https://community.tresor.one/u/afd52ae9

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #351: Ebase
## Document
<details><summary>Umsätze 2020-12-04.pdf</summary><p>

```json
[
  [
    "Umsätze",
    "im Zeitraum: 01.01.2020 -  04.12.2020",
    "04.12.2020 11:44 Uhr",
    "ebase Depot standard Trading",
    "Depotinhaber:",
    "Bestand: 2.715,15 EUR",
    "Umsatzarten:",
    "Zugang",
    "Abgang",
    "Fondsertrag / Vorabpauschale",
    "Sonstige Umsätze",
    "Pos.",
    "Umsatzart / Bezeichnung",
    "ISIN",
    "Buchungsdatum",
    "Anteile",
    "Kurs /",
    "Kursdatum",
    "Devisenkurs",
    "Betrag",
    "02",
    "Ansparplan",
    "iShares Core MSCI World UCITS ETF USD (Acc)",
    "IE00B4L5Y983",
    "02.12.2020",
    "0,421277",
    "71,20 USD",
    "01.12.2020",
    "1,202200",
    "EUR/USD",
    "25,00 EUR",
    "05",
    "Ansparplan",
    "SPDR MSCI Emerging Markets Small Cap UCITS ETF",
    "IE00B48X4842",
    "02.12.2020",
    "0,337661",
    "88,83 USD",
    "01.12.2020",
    "1,202200",
    "EUR/USD",
    "25,00 EUR",
    "06",
    "Ansparplan",
    "iShares Global Clean Energy UCITS ETF",
    "IE00B1XNHC34",
    "02.12.2020",
    "2,226313",
    "13,47 USD",
    "01.12.2020",
    "1,202200",
    "EUR/USD",
    "25,00 EUR",
    "03",
    "Ansparplan",
    "Lyxor MSCI All Country World UCITS ETF - Acc EUR",
    "LU1829220216",
    "01.12.2020",
    "0,084413",
    "295,57 EUR",
    "01.12.2020",
    "25,00 EUR",
    "04",
    "Ansparplan",
    "Xtrackers II Eurozone Government Bond UCITS ETF 1C",
    "LU0290355717",
    "01.12.2020",
    "0,097042",
    "257,11 EUR",
    "01.12.2020",
    "25,00 EUR",
    "07",
    "Ansparplan",
    "Lyxor New Energy (DR) UCITS ETF - Dist",
    "FR0010524777",
    "01.12.2020",
    "0,631868",
    "39,49 EUR",
    "01.12.2020",
    "25,00 EUR",
    "06",
    "Wiederanlage Fondsertrag",
    "iShares Global Clean Energy UCITS ETF",
    "IE00B1XNHC34",
    "30.11.2020",
    "0,014730",
    "13,58 USD",
    "27.11.2020",
    "0,20 USD",
    "07",
    "Kauf",
    "Lyxor New Energy (DR) UCITS ETF - Dist",
    "FR0010524777",
    "25.11.2020",
    "12,794511",
    "39,00 EUR",
    "25.11.2020",
    "500,00 EUR",
    "02",
    "Kauf",
    "iShares Core MSCI World UCITS ETF USD (Acc)",
    "IE00B4L5Y983",
    "19.11.2020",
    "4,228710",
    "69,67 USD",
    "18.11.2020",
    "1,180800",
    "EUR/USD",
    "250,00 EUR",
    "05",
    "Kauf",
    "SPDR MSCI Emerging Markets Small Cap UCITS ETF",
    "IE00B48X4842",
    "19.11.2020",
    "3,451543",
    "85,36 USD",
    "18.11.2020",
    "1,180800",
    "EUR/USD",
    "250,00 EUR",
    "03",
    "Kauf",
    "Lyxor MSCI All Country World UCITS ETF - Acc EUR",
    "LU1829220216",
    "18.11.2020",
    "0,851536",
    "293,00 EUR",
    "18.11.2020",
    "250,00 EUR",
    "04",
    "Kauf",
    "Xtrackers II Eurozone Government Bond UCITS ETF 1C",
    "LU0290355717",
    "18.11.2020",
    "0,967826",
    "257,79 EUR",
    "18.11.2020",
    "250,00 EUR",
    "06",
    "Kauf",
    "iShares Global Clean Energy UCITS ETF",
    "IE00B1XNHC34",
    "12.11.2020",
    "2,338603",
    "12,57 USD",
    "11.11.2020",
    "1,178000",
    "EUR/USD",
    "25,00 EUR",
    "02",
    "Ansparplan",
    "iShares Core MSCI World UCITS ETF USD (Acc)",
    "IE00B4L5Y983",
    "03.11.2020",
    "0,459819",
    "63,36 USD",
    "02.11.2020",
    "1,167700",
    "EUR/USD",
    "25,00 EUR",
    "Seite 1 von 4"
  ],
  [
    "Umsätze",
    "im Zeitraum: 01.01.2020 -  04.12.2020",
    "04.12.2020 11:44 Uhr",
    "ebase Depot standard Trading",
    "Depotinhaber:",
    "Bestand: 2.715,15 EUR",
    "Umsatzarten:",
    "Zugang",
    "Abgang",
    "Fondsertrag / Vorabpauschale",
    "Sonstige Umsätze",
    "Pos.",
    "Umsatzart / Bezeichnung",
    "ISIN",
    "Buchungsdatum",
    "Anteile",
    "Kurs /",
    "Kursdatum",
    "Devisenkurs",
    "Betrag",
    "05",
    "Ansparplan",
    "SPDR MSCI Emerging Markets Small Cap UCITS ETF",
    "IE00B48X4842",
    "03.11.2020",
    "0,375295",
    "77,63 USD",
    "02.11.2020",
    "1,167700",
    "EUR/USD",
    "25,00 EUR",
    "03",
    "Ansparplan",
    "Lyxor MSCI All Country World UCITS ETF - Acc EUR",
    "LU1829220216",
    "02.11.2020",
    "0,091644",
    "272,25 EUR",
    "02.11.2020",
    "25,00 EUR",
    "04",
    "Ansparplan",
    "Xtrackers II Eurozone Government Bond UCITS ETF 1C",
    "LU0290355717",
    "02.11.2020",
    "0,096780",
    "257,80 EUR",
    "02.11.2020",
    "25,00 EUR",
    "06",
    "Kauf",
    "iShares Global Clean Energy UCITS ETF",
    "IE00B1XNHC34",
    "14.10.2020",
    "2,441196",
    "11,96 USD",
    "13.10.2020",
    "1,170600",
    "EUR/USD",
    "25,00 EUR",
    "02",
    "Ansparplan",
    "iShares Core MSCI World UCITS ETF USD (Acc)",
    "IE00B4L5Y983",
    "02.10.2020",
    "0,452007",
    "64,49 USD",
    "01.10.2020",
    "1,168300",
    "EUR/USD",
    "25,00 EUR",
    "05",
    "Ansparplan",
    "SPDR MSCI Emerging Markets Small Cap UCITS ETF",
    "IE00B48X4842",
    "02.10.2020",
    "0,372253",
    "78,30 USD",
    "01.10.2020",
    "1,168300",
    "EUR/USD",
    "25,00 EUR",
    "03",
    "Ansparplan",
    "Lyxor MSCI All Country World UCITS ETF - Acc EUR",
    "LU1829220216",
    "01.10.2020",
    "0,091193",
    "273,59 EUR",
    "01.10.2020",
    "25,00 EUR",
    "04",
    "Ansparplan",
    "Xtrackers II Eurozone Government Bond UCITS ETF 1C",
    "LU0290355717",
    "01.10.2020",
    "0,097692",
    "255,39 EUR",
    "01.10.2020",
    "25,00 EUR",
    "02",
    "Ansparplan",
    "iShares Core MSCI World UCITS ETF USD (Acc)",
    "IE00B4L5Y983",
    "02.09.2020",
    "0,442620",
    "66,69 USD",
    "01.09.2020",
    "1,183100",
    "EUR/USD",
    "25,00 EUR",
    "05",
    "Ansparplan",
    "SPDR MSCI Emerging Markets Small Cap UCITS ETF",
    "IE00B48X4842",
    "02.09.2020",
    "0,372609",
    "79,22 USD",
    "01.09.2020",
    "1,183100",
    "EUR/USD",
    "25,00 EUR",
    "03",
    "Ansparplan",
    "Lyxor MSCI All Country World UCITS ETF - Acc EUR",
    "LU1829220216",
    "01.09.2020",
    "0,090017",
    "277,17 EUR",
    "01.09.2020",
    "25,00 EUR",
    "04",
    "Ansparplan",
    "Xtrackers II Eurozone Government Bond UCITS ETF 1C",
    "LU0290355717",
    "01.09.2020",
    "0,099052",
    "251,89 EUR",
    "01.09.2020",
    "25,00 EUR",
    "02",
    "Ansparplan",
    "iShares Core MSCI World UCITS ETF USD (Acc)",
    "IE00B4L5Y983",
    "04.08.2020",
    "0,464646",
    "63,04 USD",
    "03.08.2020",
    "1,174000",
    "EUR/USD",
    "25,00 EUR",
    "05",
    "Ansparplan",
    "SPDR MSCI Emerging Markets Small Cap UCITS ETF",
    "IE00B48X4842",
    "04.08.2020",
    "0,385550",
    "75,97 USD",
    "03.08.2020",
    "1,174000",
    "EUR/USD",
    "25,00 EUR",
    "Seite 2 von 4"
  ],
  [
    "Umsätze",
    "im Zeitraum: 01.01.2020 -  04.12.2020",
    "04.12.2020 11:44 Uhr",
    "ebase Depot standard Trading",
    "Depotinhaber:",
    "Bestand: 2.715,15 EUR",
    "Umsatzarten:",
    "Zugang",
    "Abgang",
    "Fondsertrag / Vorabpauschale",
    "Sonstige Umsätze",
    "Pos.",
    "Umsatzart / Bezeichnung",
    "ISIN",
    "Buchungsdatum",
    "Anteile",
    "Kurs /",
    "Kursdatum",
    "Devisenkurs",
    "Betrag",
    "03",
    "Ansparplan",
    "Lyxor MSCI All Country World UCITS ETF - Acc EUR",
    "LU1829220216",
    "03.08.2020",
    "0,093236",
    "267,60 EUR",
    "03.08.2020",
    "25,00 EUR",
    "04",
    "Ansparplan",
    "Xtrackers II Eurozone Government Bond UCITS ETF 1C",
    "LU0290355717",
    "03.08.2020",
    "0,098379",
    "253,61 EUR",
    "03.08.2020",
    "25,00 EUR",
    "02",
    "Ansparplan",
    "iShares Core MSCI World UCITS ETF USD (Acc)",
    "IE00B4L5Y983",
    "02.07.2020",
    "0,468191",
    "59,95 USD",
    "01.07.2020",
    "1,124900",
    "EUR/USD",
    "25,00 EUR",
    "05",
    "Ansparplan",
    "SPDR MSCI Emerging Markets Small Cap UCITS ETF",
    "IE00B48X4842",
    "02.07.2020",
    "0,400817",
    "70,02 USD",
    "01.07.2020",
    "1,124900",
    "EUR/USD",
    "25,00 EUR",
    "03",
    "Ansparplan",
    "Lyxor MSCI All Country World UCITS ETF - Acc EUR",
    "LU1829220216",
    "01.07.2020",
    "0,094388",
    "264,33 EUR",
    "01.07.2020",
    "25,00 EUR",
    "04",
    "Ansparplan",
    "Xtrackers II Eurozone Government Bond UCITS ETF 1C",
    "LU0290355717",
    "01.07.2020",
    "0,099744",
    "250,14 EUR",
    "01.07.2020",
    "25,00 EUR",
    "02",
    "Ansparplan",
    "iShares Core MSCI World UCITS ETF USD (Acc)",
    "IE00B4L5Y983",
    "03.06.2020",
    "0,471576",
    "59,10 USD",
    "02.06.2020",
    "1,117000",
    "EUR/USD",
    "25,00 EUR",
    "05",
    "Ansparplan",
    "SPDR MSCI Emerging Markets Small Cap UCITS ETF",
    "IE00B48X4842",
    "03.06.2020",
    "0,412388",
    "67,58 USD",
    "02.06.2020",
    "1,117000",
    "EUR/USD",
    "25,00 EUR",
    "03",
    "Ansparplan",
    "Lyxor MSCI All Country World UCITS ETF - Acc EUR",
    "LU1829220216",
    "02.06.2020",
    "0,095466",
    "261,35 EUR",
    "02.06.2020",
    "25,00 EUR",
    "04",
    "Ansparplan",
    "Xtrackers II Eurozone Government Bond UCITS ETF 1C",
    "LU0290355717",
    "02.06.2020",
    "0,100491",
    "248,28 EUR",
    "02.06.2020",
    "25,00 EUR",
    "02",
    "Neuabrechnung Kauf",
    "iShares Core MSCI World UCITS ETF USD (Acc)",
    "IE00B4L5Y983",
    "08.05.2020",
    "1,081765",
    "50,04 USD",
    "06.04.2020",
    "1,084800",
    "EUR/USD",
    "50,00 EUR",
    "05",
    "Neuabrechnung Kauf",
    "SPDR MSCI Emerging Markets Small Cap UCITS ETF",
    "IE00B48X4842",
    "08.05.2020",
    "0,963138",
    "56,20 USD",
    "06.04.2020",
    "1,084800",
    "EUR/USD",
    "50,00 EUR",
    "02",
    "Ansparplan",
    "iShares Core MSCI World UCITS ETF USD (Acc)",
    "IE00B4L5Y983",
    "05.05.2020",
    "0,504284",
    "53,47 USD",
    "04.05.2020",
    "1,080800",
    "EUR/USD",
    "25,00 EUR",
    "05",
    "Ansparplan",
    "SPDR MSCI Emerging Markets Small Cap UCITS ETF",
    "IE00B48X4842",
    "05.05.2020",
    "0,448367",
    "60,14 USD",
    "04.05.2020",
    "1,080800",
    "EUR/USD",
    "25,00 EUR",
    "Seite 3 von 4"
  ],
  [
    "Umsätze",
    "im Zeitraum: 01.01.2020 -  04.12.2020",
    "04.12.2020 11:44 Uhr",
    "ebase Depot standard Trading",
    "Depotinhaber:",
    "Bestand: 2.715,15 EUR",
    "Umsatzarten:",
    "Zugang",
    "Abgang",
    "Fondsertrag / Vorabpauschale",
    "Sonstige Umsätze",
    "Pos.",
    "Umsatzart / Bezeichnung",
    "ISIN",
    "Buchungsdatum",
    "Anteile",
    "Kurs /",
    "Kursdatum",
    "Devisenkurs",
    "Betrag",
    "03",
    "Ansparplan",
    "Lyxor MSCI All Country World UCITS ETF - Acc EUR",
    "LU1829220216",
    "04.05.2020",
    "0,102612",
    "243,15 EUR",
    "04.05.2020",
    "25,00 EUR",
    "04",
    "Ansparplan",
    "Xtrackers II Eurozone Government Bond UCITS ETF 1C",
    "LU0290355717",
    "04.05.2020",
    "0,100762",
    "247,61 EUR",
    "04.05.2020",
    "25,00 EUR",
    "03",
    "Kauf",
    "Lyxor MSCI All Country World UCITS ETF - Acc EUR",
    "LU1829220216",
    "06.04.2020",
    "0,216086",
    "230,93 EUR",
    "06.04.2020",
    "50,00 EUR",
    "04",
    "Kauf",
    "Xtrackers II Eurozone Government Bond UCITS ETF 1C",
    "LU0290355717",
    "06.04.2020",
    "0,202030",
    "246,99 EUR",
    "06.04.2020",
    "50,00 EUR",
    "Seite 4 von 4"
  ]
]

```

</p></details>

## Community profile

https://app.tresor.one/p/5fca12b9030c430031d98ae2/activities

---
Issue submitted with https://import.tresor.one

### PR DESCRIPTION
**Pull request by SirGibihm**
* Fix #243 For some reason reinvests were classified as `Buy` instead of `Sell`
* Fix #243 was a partial duplicate of #254 (which is not completely fixed by this PR)
* Fix #339 is also partially fixed, however there still remains a huge issue with transactions that are conducted completetly in USD for an EUR depot. For the moment they fail loudly with a new `statuscode 6`
* Fix #345 and Fix #346 contained new transactions that are simple `Buy`and `Sell` Operations  under the hood
* Fix #351 Yet another synonym for buy operations

### CODE REVIEW

**Comment by SirGibihm** [comment]
Added a very dirty workaround from discussion of #339  , will need change soon.

**Comment by dredav** [comment]
65 commits 😮 🚀

File: src/brokers/ebase.js [hunk 1]
```diff
@@ -40,7 +62,11 @@ function parseBaseAction(pdfArray, pdfOffset, actionType) {
     pdfArray[pdfOffset + 6],
     undefined
   );
-
+  if (actionType === 'Buy' && pdfArray[pdfOffset] === 'Wiederanlage Fondsertrag') {
+    if (!pdfArray[pdfOffset + 5].endsWith('EUR') && !pdfArray[pdfOffset + 7].endsWith('EUR')) {
+      throw (new ForeignOnlyReinvest('Found a reinvest containing only a non-EUR currency, can not be parsed yet.'))
```
Comment (dredav) [inline src/brokers/ebase.js:67]: Why not `throw new Error('Found a reinvest containing only a non-EUR currency, can not be parsed yet.');`?

File: src/brokers/ebase.js [hunk 2]
```diff
@@ -74,39 +99,32 @@ const parseData = pdfPages => {
...
         }
-        actions.push(action);
-        // An 'Ansparplan'/'Wiederanlage Fondsertrag' entry occupies 7 array entries.
-        i += 6;
-      } else if (pdfPage[i] === 'Wiederanlage Fondsertrag') {
-        const action = parseBaseAction(pdfPage, i, 'Sell');
-        if (action === undefined) {
+        catch ( error ) {
+          if (error instanceof ForeignOnlyReinvest) {
+            console.error(error.message);
```
Comment (dredav) [inline src/brokers/ebase.js:112]: Could you add a comment (from the issue discussion) why we need to return directly here.

File: src/brokers/ebase.js [hunk 3]
```diff
@@ -124,8 +142,12 @@ export const canParsePage = (content, extension) =>
   content.some(line => line.includes('Fondsertrag / Vorabpauschale'));
 
 export const parsePages = contents => {
+  const activities = parseData(contents);
+  const status = parseData(contents) !== undefined ? 0 : 6
```
Comment (dredav) [inline src/brokers/ebase.js:146]: We can reduce the duplicated work to once
```suggestion
  const status = activities !== undefined ? 0 : 6
```

**Review by dredav — COMMENTED** [review]
I'm not sure why the review panel show also other changes. So I only check the ebase related files....

I found only small things - we can merge it if you want without any changes.

File: src/brokers/ebase.js (hunk 1 above)
Comment (SirGibihm) [reply src/brokers/ebase.js:67]: Because I am catching that specific error in line 111 and validate to catch only that error through `instanceof`. Of course I could do an error-message comparison but I have a feeling thats not best practice.

File: src/brokers/ebase.js (hunk 2 above)
Comment (SirGibihm) [reply src/brokers/ebase.js:112]: Sure thing

File: src/brokers/ebase.js (hunk 3 above)
Comment (SirGibihm) [reply src/brokers/ebase.js:146]: Absolutely. Brainfart of mine

**Comment by SirGibihm** [comment]
> 
> 
> I'm not sure why the review panel show also other changes. So I only check the ebase related files....
> 
> I found only small things - we can merge it if you want without any changes.

It is because I 

> 
> 
> I'm not sure why the review panel show also other changes. So I only check the ebase related files....
> 
> I found only small things - we can merge it if you want without any changes.

Puhhh No idea. Should I reopen the PR? I do not know what happened here... In other news, I implemented the changes you requested.

**Comment by dredav** [comment]
>Puhhh No idea. Should I reopen the PR? I do not know what happened here... 

No we are nearly done with this PR and we bring it to and good end here.

**Comment by SirGibihm** [comment]
@dredav Fixes are there, please rereview. I think if we merge this one we should do another release, what do you think?

**Review by dredav — APPROVED** [review]

**Comment by dredav** [comment]
>I think if we merge this one we should do another release

`Rebase and merge` instead of `Squash and merge`? Or would you rebase the branch and then squash? When rebase, do this in a branch depending on this one (`SirGibihm:339_ebase_multiple_fixes`) to prevent some data loos.

**Comment by SirGibihm** [comment]
I strongly suggest going for the squash. I think the random file changes are due to an unclean rebase within my fork. Furthermore, if anything breaks we can simply revert this Pull-Request-Merge
