### PR TITLE
358 dkb failed import

### LINKED ISSUE #358: [dkb] Es kann ein Aktienkauf nicht importiert werden
## Document
<details><summary>Kauf_-_WKN_856958_-_Wertpapierabrechnung_vom_07.07.2020_zu_Depot_503019812_-_Ordernr._4295167700.pdf</summary><p>

```json
[
  [
    "10919 Berlin",
    "Ozbay",
    "Klkxwlj Pkdgidpjyu",
    "Ydpz-Khanroh-Zhmei 5",
    "26747 Höbcorzzk",
    "Depotnummer",
    "815886687",
    "Kundennummer",
    "7554823786",
    "Ebadcap Cebakjpirq",
    "Auftragsnummer",
    "238760/65.85",
    "Datum",
    "07.07.2020",
    "Rechnungsnummer",
    "00883 0003222245 20",
    "Umsatzsteuer-ID",
    "DE137178746",
    "0883.07072127.0008251OR07",
    "Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.",
    "Wertpapier Abrechnung Kauf",
    "Nominale",
    "Wertpapierbezeichnung",
    "ISIN",
    "(WKN)",
    "Stück 8",
    "MC DONALD S CORP.",
    "SHARES",
    "REGISTERED SHARES DL-,01",
    "US5801351017",
    "(856958)",
    "Handels-/Ausführungsplatz",
    "Tradegate (gemäß Weisung)",
    "Börsensegment",
    "XGAT",
    "Market-Orde",
    "r",
    "Limit",
    "billigst",
    "Schlusstag/-Zeit",
    "07.07.2020 18:54:41",
    "Ausführungskurs",
    "165,02 EUR",
    "Auftraggeber",
    "Max Mustermann",
    "Auftragserteilung/ -ort",
    "Online-Banking",
    "Girosammelverw. mehrere Sammelurkunden - kein Stückeausdruck -",
    "Kurswert",
    "1.320,16-",
    "EUR",
    "Provision",
    "10,00-",
    "EUR",
    "Ausmachender Betrag",
    "1.330,16-",
    "EUR",
    "Den Gegenwert buchen wir mit Valuta 09.07.2020 zu Lasten des Kontos 1032954156",
    "(LMOY PD54 3605 9913 1118 9140 25), ZHM 28530023 (CNR ZJYJSZY7701).",
    "Die Wertpapiere schreiben wir Ihrem Depotkonto gut.",
    "Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich um eine umsatzsteuerbefreite Finanzdienstleistung.",
    "Für das Geschäft wurde keine Anlageberatung erbracht.",
    "Initiator der Besprechung war der Kunde."
  ]
]

```

</p></details>

## Community profile

https://community.tresor.one/u/3e5bad40

---
Issue submitted with https://import.tresor.one

### PR DESCRIPTION
**Pull request by SirGibihm**
This is a quick one :D 
* Fix #358 Small bugfix due to an ISIN regex not working. Removed bug by using a helper function. 
* Code optimizations through code depuplication.

### CODE REVIEW

File: src/brokers/dkb.js [hunk 1]
```diff
@@ -168,41 +162,34 @@ export const canParsePage = (content, extension) =>
   (isBuy(content) || isSell(content) || isDividend(content));
 
 export const parsePages = pages => {
-  let type, date, time, isin, company, shares, price, amount, fee, tax;
   const firstPage = pages[0];
 
+  let type, amount, price, date, time;
+  const stueckIdx = firstPage.findIndex(t => t.includes('Stück'));
```
Comment (dredav) [inline src/brokers/dkb.js:168]:
```suggestion
  const pieceIdx = firstPage.findIndex(t => t.includes('Stück'));
```

And other references of `stueckIdx`

Comment (SirGibihm) [reply src/brokers/dkb.js:168]: Fixed

**Review by dredav — APPROVED** [review]
