### PR TITLE
[traderepublic] Fixed a bug where withholding tax was in EUR

### LINKED ISSUE #198: Trade Republic Dividende: Falsche Berechnung der Quellensteuer
## Document
<details><summary>pb1599603133421564628143628438.pdf</summary><p>

```json
[
  [
    "TRADE REPUBLIC BANK GMBH",
    "KASTANIENALLEE 32",
    "10435 BERLIN",
    "Ccjiq Sdiewt Gpehdpkx Lasmyg",
    "Csmbkthr. 8",
    "H 19743 Mzqeubjv QS Ssxmafyosjy",
    "SEITE",
    "1",
    "von",
    "1",
    "DATUM",
    "08.09.2020",
    "DEPOT",
    "972392274",
    "Trade Republic Bank GmbH",
    "Kastanienallee 32",
    "10435 Berlin",
    "www.traderepublic.com",
    "ioihtrr@wcxvrzdhgeeeg.dsd",
    "Sitz der Gesellschaft: Düsseldorf",
    "AG Düsseldorf HRB 85864",
    "USt-ID DE307510626",
    "Geschäftsführer",
    "Andreas Willius",
    "Karsten Müller",
    "ABRE / 2020-09-09 / 44843313 / 7227-29ae",
    "DIVIDENDE",
    "ÜBERSICHT",
    "Dividende mit dem Ex-Tag 06.08.2020.",
    "POSITION",
    "ANZAHL",
    "ERTRÄGNIS",
    "BETRAG",
    "Unilever N.V.",
    "Aandelen op naam EO -,16",
    "ISIN: NL0000388619",
    "5 Stk.",
    "0,41 EUR",
    "2,05 EUR",
    "GESAMT",
    "2,05 EUR",
    "ABRECHNUNG",
    "POSITION",
    "BETRAG",
    "Quellensteuer",
    "-0,31 EUR",
    "GESAMT",
    "1,74 EUR",
    "BUCHUNG",
    "VERRECHNUNGSKONTO",
    "VALUTA",
    "BETRAG",
    "QQ56677346096609025513",
    "09.09.2020",
    "1,74 EUR",
    "Unilever N.V. Aandelen op naam EO -,16 in Girosammelverwahrung.",
    "Diese Abrechnung wird maschinell erstellt und daher nicht unterschrieben.",
    "Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich gem. § 4 Nr. 8 UStG um eine umsatzsteuerfreie",
    "Leistung."
  ]
]

```

</p></details>

## Community profile

https://community.tresor.one/u/200bfdb7

---
Issue submitted with https://import.tresor.one

### PR DESCRIPTION
**Pull request by SirGibihm**
Witholding tax in EUR was parsed twice. Fixed it so that it checks wether the witholding tax is in EUR. If so, it is ignored.

Fix #198

### CODE REVIEW

File: tests/brokers/__mocks__/traderepublic/index.js [hunk 1]
```diff
@@ -45,9 +20,12 @@ export const dividendSamples = [
...
   require('./dividend/realty_income_with_other_withholding_tax_format.json'),
+  require('./dividend/unilever_withholding_tax.json'),
 ];
 
 export const quarterSamples = [
   require('./quarter_statement/without_stocks.json'),
   require('./quarter_statement/with_stocks.json'),
 ];
+
+export const allSamples = buySamples.concat(sellSamples, dividendSamples, quarterSamples);
```
Comment (dredav) [inline tests/brokers/__mocks__/traderepublic/index.js:31]: 😍

**Review by dredav — APPROVED** [review]
Oh that was my fault... Thanks for fixing the bug. The withholding tax is already parsed with `Parse all taxes in the range of relevant line numbers` in block L156-167
