### PR TITLE
[degiro] Fixes a Buy-Sell identification bug. Allowing zero-amount sells as (patch)

### LINKED ISSUE #363: Import funktioniert nicht richtig
## Document
<details><summary>Transactions (3).pdf</summary><p>

```json
[
  [
    "Herr Max Mustermann",
    "Musterstraße 1",
    "55555 Musterstadt",
    "Germany",
    "Benutzername:",
    "*****100",
    "(31000665)",
    "Transaktionsübersicht von 01-01-2014 bis 05-12-2020",
    "Datum",
    "Uhrzeit",
    "Produkt",
    "ISIN",
    "Börse",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährun",
    "Wert",
    "Wechselkur",
    "s",
    "Gebühr",
    "Gesamt",
    "04-12-2020",
    "16:39",
    "REVLON INC. NEW COMMO",
    "US7615256093",
    "NSY",
    "-100",
    "USD",
    "14,25",
    "USD",
    "1.425,00",
    "EUR",
    "1.170,69",
    "1,216",
    "EUR",
    "-0,83",
    "EUR",
    "1.169,86",
    "03-12-2020",
    "19:46",
    "XPO LOGISTICS INC.",
    "US9837931008",
    "NSY",
    "10",
    "USD",
    "117,03",
    "USD",
    "-1.170,30",
    "EUR",
    "-963,95",
    "1,2129",
    "EUR",
    "-0,52",
    "EUR",
    "-964,47",
    "02-12-2020",
    "20:36",
    "REVLON INC. NEW COMMO",
    "US7615256093",
    "NSY",
    "100",
    "USD",
    "12,45",
    "USD",
    "-1.245,00",
    "EUR",
    "-1.029,10",
    "1,2086",
    "EUR",
    "-0,83",
    "EUR",
    "-1.029,93",
    "02-12-2020",
    "20:36",
    "FACEBOOK INC. - CLASS",
    "US30303M1027",
    "NDQ",
    "-4",
    "USD",
    "288,39",
    "USD",
    "1.153,56",
    "EUR",
    "951,61",
    "1,211",
    "EUR",
    "-0,51",
    "EUR",
    "951,10",
    "01-12-2020",
    "19:10",
    "WHOLE EARTH BRANDS INC. -",
    "CLASS A COMMON STOCK",
    "US96684W1009",
    "NDQ",
    "500",
    "USD",
    "9,03",
    "USD",
    "-4.515,00",
    "EUR",
    "-3.747,82",
    "1,2035",
    "EUR",
    "-2,16",
    "EUR",
    "-3.749,98",
    "01-12-2020",
    "17:30",
    "ONESPAN INC",
    "US68287N1000",
    "NDQ",
    "-350",
    "USD",
    "20,20",
    "USD",
    "7.070,00",
    "EUR",
    "5.854,46",
    "1,2064",
    "EUR",
    "-1,66",
    "EUR",
    "5.852,80",
    "30-11-2020",
    "16:00",
    "ONESPAN INC",
    "US68287N1000",
    "NDQ",
    "100",
    "USD",
    "20,28",
    "USD",
    "-2.028,00",
    "EUR",
    "-1.690,56",
    "1,1984",
    "EUR",
    "-0,83",
    "EUR",
    "-1.691,39",
    "30-11-2020",
    "15:58",
    "ONESPAN INC",
    "US68287N1000",
    "NDQ",
    "250",
    "USD",
    "20,30",
    "USD",
    "-5.075,00",
    "EUR",
    "-4.230,22",
    "1,1985",
    "EUR",
    "-1,33",
    "EUR",
    "-4.231,55",
    "30-11-2020",
    "15:45",
    "INSTAL",
    "SE0009664253",
    "OMX",
    "-200",
    "SEK",
    "213,00",
    "SEK",
    "42.600,00",
    "EUR",
    "4.177,34",
    "10,1877",
    "EUR",
    "-6,09",
    "EUR",
    "4.171,25",
    "20-11-2020",
    "12:00",
    "ARGENTEX GROUP.",
    "GB00BJLPH056",
    "LSE",
    "-122",
    "GBX",
    "119,00",
    "GBX",
    "14.518,00",
    "EUR",
    "162,44",
    "89,2857",
    "EUR",
    "-4,07",
    "EUR",
    "158,37",
    "18-11-2020",
    "17:12",
    "MEARS GROUP",
    "GB0005630420",
    "LSE",
    "-600",
    "GBX",
    "152,00",
    "GBX",
    "91.200,00",
    "EUR",
    "1.019,69",
    "89,3495",
    "EUR",
    "-4,51",
    "EUR",
    "1.015,18",
    "18-11-2020",
    "16:19",
    "INSTAL",
    "SE0009664253",
    "OMX",
    "-100",
    "SEK",
    "213,50",
    "SEK",
    "21.350,00",
    "EUR",
    "2.088,24",
    "10,2137",
    "EUR",
    "-5,05",
    "EUR",
    "2.083,19",
    "18-11-2020",
    "15:46",
    "WHOLE EARTH BRANDS INC. -",
    "CLASS A COMMON STOCK",
    "US96684W1009",
    "NDQ",
    "590",
    "USD",
    "8,09",
    "USD",
    "-4.773,10",
    "EUR",
    "-4.021,15",
    "1,1858",
    "EUR",
    "-2,49",
    "EUR",
    "-4.023,64",
    "18-11-2020",
    "09:26",
    "INSTAL",
    "SE0009664253",
    "OMX",
    "-100",
    "SEK",
    "212,50",
    "SEK",
    "21.250,00",
    "EUR",
    "2.078,05",
    "10,2157",
    "EUR",
    "-5,04",
    "EUR",
    "2.073,01",
    "17-11-2020",
    "11:22",
    "ARGENTEX GROUP.",
    "GB00BJLPH056",
    "LSE",
    "300",
    "GBX",
    "114,00",
    "GBX",
    "-34.200,00",
    "EUR",
    "-381,01",
    "89,6708",
    "EUR",
    "-4,19",
    "EUR",
    "-385,20",
    "16-11-2020",
    "16:40",
    "MEARS GROUP",
    "GB0005630420",
    "LSE",
    "600",
    "GBX",
    "146,00",
    "GBX",
    "-87.600,00",
    "EUR",
    "-980,14",
    "89,2857",
    "EUR",
    "-4,49",
    "EUR",
    "-984,63",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "crywlbuyzvkqh@irafdn.bn",
    "I",
    "www.degiro.de",
    "Seite 1 /",
    "13",
    "Konto 2020-12-05"
  ],
  [
    "Herr Max Mustermann",
    "Musterstraße 1",
    "5555 Musterstadt",
    "Germany",
    "Benutzername:",
    "*****100",
    "(31000665)",
    "Datum",
    "Uhrzeit",
    "Produkt",
    "ISIN",
    "Börse",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährun",
    "Wert",
    "Wechselkur",
    "s",
    "Gebühr",
    "Gesamt",
    "05-11-2020",
    "10:18",
    "ROLLS-ROYCE HLG",
    "GB00B63H8491",
    "LSE",
    "-2300",
    "GBX",
    "78,7943",
    "GBX",
    "181.226,88",
    "EUR",
    "2.009,61",
    "90,0901",
    "EUR",
    "-5,00",
    "EUR",
    "2.004,61",
    "28-10-2020",
    "13:14",
    "ROLLS-ROYCE HLG",
    "GB00B63H8491",
    "LSE",
    "2300",
    "GBX",
    "96,94",
    "GBX",
    "-222.962,00",
    "EUR",
    "-2.472,40",
    "90,0901",
    "EUR",
    "-5,23",
    "EUR",
    "-2.477,63",
    "26-10-2020",
    "17:22",
    "EVOLUTION GAMING GROUP AB",
    "SE0012673267",
    "OMX",
    "-100",
    "SEK",
    "678,80",
    "SEK",
    "67.880,00",
    "EUR",
    "6.557,43",
    "10,3413",
    "EUR",
    "-7,27",
    "EUR",
    "6.550,16",
    "14-10-2020",
    "10:50",
    "ARGENTEX GROUP.",
    "GB00BJLPH056",
    "LSE",
    "1000",
    "GBX",
    "103,00",
    "GBX",
    "-103.000,00",
    "EUR",
    "-1.131,99",
    "90,8992",
    "EUR",
    "-4,57",
    "EUR",
    "-1.136,56",
    "12-10-2020",
    "10:28",
    "ARGENTEX GROUP.",
    "GB00BJLPH056",
    "LSE",
    "1000",
    "GBX",
    "107,00",
    "GBX",
    "-107.000,00",
    "EUR",
    "-1.180,75",
    "90,5297",
    "EUR",
    "-4,59",
    "EUR",
    "-1.185,34",
    "12-10-2020",
    "09:58",
    "ARGENTEX GROUP.",
    "GB00BJLPH056",
    "LSE",
    "5300",
    "GBX",
    "109,6456",
    "GBX",
    "-581.121,50",
    "EUR",
    "-6.385,94",
    "90,9091",
    "EUR",
    "-7,21",
    "EUR",
    "-6.393,15",
    "12-10-2020",
    "09:39",
    "GRENKE FIN. 17/22 MTN",
    "XS1678629186",
    "FRA",
    "-13000",
    "EUR",
    "82,70",
    "EUR",
    "10.751,00",
    "EUR",
    "10.751,00",
    "EUR",
    "-10,38",
    "EUR",
    "10.740,62",
    "09-10-2020",
    "17:16",
    "ARGENTEX GROUP.",
    "GB00BJLPH056",
    "LSE",
    "1200",
    "GBX",
    "139,00",
    "GBX",
    "-166.800,00",
    "EUR",
    "-1.835,58",
    "90,7795",
    "EUR",
    "-4,92",
    "EUR",
    "-1.840,50",
    "08-10-2020",
    "09:06",
    "EVOLUTION GAMING GROUP AB",
    "SE0012673267",
    "OMX",
    "20",
    "SEK",
    "712,00",
    "SEK",
    "-14.240,00",
    "EUR",
    "-1.364,91",
    "10,4225",
    "EUR",
    "-4,68",
    "EUR",
    "-1.369,59",
    "06-10-2020",
    "17:12",
    "ARGENTEX GROUP.",
    "GB00BJLPH056",
    "LSE",
    "400",
    "GBX",
    "141,00",
    "GBX",
    "-56.400,00",
    "EUR",
    "-620,46",
    "90,8092",
    "EUR",
    "-4,31",
    "EUR",
    "-624,77",
    "05-10-2020",
    "09:19",
    "EVOLUTION GAMING GROUP AB",
    "SE0012673267",
    "OMX",
    "40",
    "SEK",
    "656,80",
    "SEK",
    "-26.272,00",
    "EUR",
    "-2.513,78",
    "10,4408",
    "EUR",
    "-5,26",
    "EUR",
    "-2.519,04",
    "05-10-2020",
    "09:13",
    "EVOLUTION GAMING GROUP AB",
    "SE0012673267",
    "OMX",
    "40",
    "SEK",
    "650,00",
    "SEK",
    "-26.000,00",
    "EUR",
    "-2.487,75",
    "10,4408",
    "EUR",
    "-5,25",
    "EUR",
    "-2.493,00",
    "01-10-2020",
    "14:04",
    "AFH FINANCIAL",
    "GB00B4W5WQ08",
    "LSE",
    "1800",
    "GBX",
    "320,00",
    "GBX",
    "-576.000,00",
    "EUR",
    "-6.349,17",
    "90,6298",
    "EUR",
    "-7,18",
    "EUR",
    "-6.356,35",
    "30-09-2020",
    "17:45",
    "ARGENTEX GROUP.",
    "GB00BJLPH056",
    "LSE",
    "36",
    "GBX",
    "137,00",
    "GBX",
    "-4.932,00",
    "EUR",
    "-54,20",
    "90,9091",
    "EUR",
    "-4,02",
    "EUR",
    "-58,22",
    "29-09-2020",
    "21:16",
    "TRUPANION INC. - COMM",
    "US8982021060",
    "NDQ",
    "-130",
    "USD",
    "78,53",
    "USD",
    "10.208,90",
    "EUR",
    "8.681,13",
    "1,1748",
    "EUR",
    "-0,95",
    "EUR",
    "8.680,18",
    "23-09-2020",
    "16:04",
    "ARGENTEX GROUP.",
    "GB00BJLPH056",
    "LSE",
    "600",
    "GBX",
    "140,50",
    "GBX",
    "-84.300,00",
    "EUR",
    "-919,60",
    "91,5784",
    "EUR",
    "-4,46",
    "EUR",
    "-924,06",
    "22-09-2020",
    "09:16",
    "ARGENTEX GROUP.",
    "GB00BJLPH056",
    "LSE",
    "650",
    "GBX",
    "144,50",
    "GBX",
    "-93.925,00",
    "EUR",
    "-1.021,92",
    "91,8181",
    "EUR",
    "-4,51",
    "EUR",
    "-1.026,43",
    "21-09-2020",
    "17:29",
    "API GROUP CORPORATION",
    "COMMON STOCK",
    "US00187Y1001",
    "NSY",
    "500",
    "USD",
    "13,15",
    "USD",
    "-6.575,00",
    "EUR",
    "-5.601,55",
    "1,1726",
    "EUR",
    "-2,20",
    "EUR",
    "-5.603,75",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "cuisutdrgwibk@rnejoq.ug",
    "I",
    "www.degiro.de",
    "Seite 2 /",
    "13",
    "Konto 2020-12-05"
  ],
  [
    "Herr Max Mustermann",
    "Musterstraße 1",
    "5555 Musterstadt",
    "Germany",
    "Benutzername:",
    "*****100",
    "(31000665)",
    "Datum",
    "Uhrzeit",
    "Produkt",
    "ISIN",
    "Börse",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährun",
    "Wert",
    "Wechselkur",
    "s",
    "Gebühr",
    "Gesamt",
    "21-09-2020",
    "17:28",
    "API GROUP CORP.",
    "US00187Y1001",
    "FRA",
    "-470",
    "EUR",
    "11,10",
    "EUR",
    "5.217,00",
    "EUR",
    "5.217,00",
    "EUR",
    "-12,20",
    "EUR",
    "5.204,80",
    "18-09-2020",
    "18:56",
    "SHARPSPRING INC. - CO",
    "US8200541048",
    "NDQ",
    "-300",
    "USD",
    "10,383",
    "USD",
    "3.114,90",
    "EUR",
    "2.620,12",
    "1,1876",
    "EUR",
    "-1,52",
    "EUR",
    "2.618,60",
    "17-09-2020",
    "14:18",
    "GRENKE FIN. 17/22 MTN",
    "XS1678629186",
    "FRA",
    "3000",
    "EUR",
    "70,00",
    "EUR",
    "-2.100,00",
    "EUR",
    "-2.100,00",
    "EUR",
    "-6,05",
    "EUR",
    "-2.106,05",
    "17-09-2020",
    "14:17",
    "MEARS GROUP",
    "GB0005630420",
    "LSE",
    "-2000",
    "GBX",
    "107,50",
    "GBX",
    "215.000,00",
    "EUR",
    "2.341,16",
    "91,7431",
    "EUR",
    "-5,18",
    "EUR",
    "2.335,98",
    "17-09-2020",
    "14:16",
    "GRENKE FIN. 17/22 MTN",
    "XS1678629186",
    "FRA",
    "4000",
    "EUR",
    "70,00",
    "EUR",
    "-2.800,00",
    "EUR",
    "-2.800,00",
    "EUR",
    "-6,40",
    "EUR",
    "-2.806,40",
    "17-09-2020",
    "14:16",
    "GRENKE FIN. 17/22 MTN",
    "XS1678629186",
    "FRA",
    "6000",
    "EUR",
    "70,00",
    "EUR",
    "-4.200,00",
    "EUR",
    "-4.200,00",
    "EUR",
    "-7,10",
    "EUR",
    "-4.207,10",
    "17-09-2020",
    "14:09",
    "GRENKE AG",
    "DE000A161N30",
    "XET",
    "-150",
    "EUR",
    "31,60",
    "EUR",
    "4.740,00",
    "EUR",
    "4.740,00",
    "EUR",
    "-2,85",
    "EUR",
    "4.737,15",
    "16-09-2020",
    "12:12",
    "GRENKE AG",
    "DE000A161N30",
    "XET",
    "150",
    "EUR",
    "34,6873",
    "EUR",
    "-5.203,10",
    "EUR",
    "-5.203,10",
    "EUR",
    "-2,93",
    "EUR",
    "-5.206,03",
    "14-09-2020",
    "09:21",
    "ARGENTEX GROUP.",
    "GB00BJLPH056",
    "LSE",
    "700",
    "GBX",
    "149,50",
    "GBX",
    "-104.650,00",
    "EUR",
    "-1.132,81",
    "92,2884",
    "EUR",
    "-4,57",
    "EUR",
    "-1.137,38",
    "11-09-2020",
    "15:59",
    "API GROUP CORP.",
    "US00187Y1001",
    "FRA",
    "-180",
    "EUR",
    "12,00",
    "EUR",
    "2.160,00",
    "EUR",
    "2.160,00",
    "EUR",
    "-9,44",
    "EUR",
    "2.150,56",
    "26-08-2020",
    "18:19",
    "TUCOWS INC. - COMMON S",
    "US8986972060",
    "NDQ",
    "-85",
    "USD",
    "64,194",
    "USD",
    "5.456,49",
    "EUR",
    "4.606,67",
    "1,1833",
    "EUR",
    "-0,78",
    "EUR",
    "4.605,89",
    "26-08-2020",
    "18:12",
    "API GROUP CORPORATION",
    "COMMON STOCK",
    "US00187Y1001",
    "NSY",
    "300",
    "USD",
    "14,55",
    "USD",
    "-4.365,00",
    "EUR",
    "-3.694,46",
    "1,1803",
    "EUR",
    "-1,52",
    "EUR",
    "-3.695,98",
    "25-08-2020",
    "16:06",
    "SHARPSPRING INC. - CO",
    "US8200541048",
    "NDQ",
    "300",
    "USD",
    "10,01",
    "USD",
    "-3.003,00",
    "EUR",
    "-2.539,50",
    "1,1813",
    "EUR",
    "-1,52",
    "EUR",
    "-2.541,02",
    "18-08-2020",
    "19:09",
    "TRUPANION INC. - COMM",
    "US8982021060",
    "NDQ",
    "-20",
    "USD",
    "60,02",
    "USD",
    "1.200,40",
    "EUR",
    "1.004,09",
    "1,1943",
    "EUR",
    "-0,56",
    "EUR",
    "1.003,53",
    "18-08-2020",
    "19:08",
    "TUCOWS INC. - COMMON S",
    "US8986972060",
    "NDQ",
    "-80",
    "USD",
    "63,4204",
    "USD",
    "5.073,63",
    "EUR",
    "4.244,41",
    "1,1942",
    "EUR",
    "-0,77",
    "EUR",
    "4.243,64",
    "18-08-2020",
    "14:20",
    "MEARS GROUP",
    "GB0005630420",
    "LSE",
    "2000",
    "GBX",
    "125,50",
    "GBX",
    "-251.000,00",
    "EUR",
    "-2.774,69",
    "90,3702",
    "EUR",
    "-5,39",
    "EUR",
    "-2.780,08",
    "10-08-2020",
    "12:42",
    "ARGENTEX GROUP.",
    "GB00BJLPH056",
    "LSE",
    "1000",
    "GBX",
    "175,00",
    "GBX",
    "-175.000,00",
    "EUR",
    "-1.939,91",
    "90,1201",
    "EUR",
    "-4,97",
    "EUR",
    "-1.944,88",
    "07-08-2020",
    "17:14",
    "TUCOWS INC. - COMMON S",
    "US8986972060",
    "NDQ",
    "-60",
    "USD",
    "70,30",
    "USD",
    "4.218,00",
    "EUR",
    "3.571,67",
    "1,1798",
    "EUR",
    "-0,70",
    "EUR",
    "3.570,97",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "zfzwbbrzzyubt@obpwgu.ax",
    "I",
    "www.degiro.de",
    "Seite 3 /",
    "13",
    "Konto 2020-12-05"
  ],
  [
    "Herr Max Mustermann",
    "Musterstraße 1",
    "5555 Musterstadt",
    "Germany",
    "Benutzername:",
    "*****100",
    "(31000665)",
    "Datum",
    "Uhrzeit",
    "Produkt",
    "ISIN",
    "Börse",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährun",
    "Wert",
    "Wechselkur",
    "s",
    "Gebühr",
    "Gesamt",
    "07-08-2020",
    "17:04",
    "TRUPANION INC. - COMM",
    "US8982021060",
    "NDQ",
    "-50",
    "USD",
    "69,01",
    "USD",
    "3.450,50",
    "EUR",
    "2.921,53",
    "1,1799",
    "EUR",
    "-0,67",
    "EUR",
    "2.920,86",
    "05-08-2020",
    "12:32",
    "ARGENTEX GROUP.",
    "GB00BJLPH056",
    "LSE",
    "2000",
    "GBX",
    "169,50",
    "GBX",
    "-339.000,00",
    "EUR",
    "-3.753,72",
    "90,2201",
    "EUR",
    "-5,88",
    "EUR",
    "-3.759,60",
    "04-08-2020",
    "16:07",
    "TUCOWS INC. - COMMON S",
    "US8986972060",
    "NDQ",
    "40",
    "USD",
    "69,50",
    "USD",
    "-2.780,00",
    "EUR",
    "-2.368,98",
    "1,1723",
    "EUR",
    "-0,64",
    "EUR",
    "-2.369,62",
    "27-07-2020",
    "15:44",
    "API GROUP CORP.",
    "US00187Y1001",
    "FRA",
    "250",
    "EUR",
    "11,06",
    "EUR",
    "-2.765,00",
    "EUR",
    "-2.765,00",
    "EUR",
    "-9,99",
    "EUR",
    "-2.774,99",
    "27-07-2020",
    "15:43",
    "HEADHUNTER GROUP PLC -",
    "AMERICAN DEPOSITARY SHARES",
    "US42207L1061",
    "NDQ",
    "-100",
    "USD",
    "20,01",
    "USD",
    "2.001,00",
    "EUR",
    "1.699,29",
    "1,1764",
    "EUR",
    "-0,84",
    "EUR",
    "1.698,45",
    "16-07-2020",
    "17:46",
    "TUCOWS INC. - COMMON S",
    "US8986972060",
    "NDQ",
    "35",
    "USD",
    "59,93",
    "USD",
    "-2.097,55",
    "EUR",
    "-1.834,48",
    "1,1423",
    "EUR",
    "-0,62",
    "EUR",
    "-1.835,10",
    "14-07-2020",
    "21:57",
    "TUCOWS INC. - COMMON S",
    "US8986972060",
    "NDQ",
    "40",
    "USD",
    "58,99",
    "USD",
    "-2.359,60",
    "EUR",
    "-2.071,28",
    "1,1381",
    "EUR",
    "-0,64",
    "EUR",
    "-2.071,92",
    "13-07-2020",
    "16:03",
    "TUCOWS INC. - COMMON S",
    "US8986972060",
    "NDQ",
    "40",
    "USD",
    "59,7418",
    "USD",
    "-2.389,67",
    "EUR",
    "-2.104,39",
    "1,1344",
    "EUR",
    "-0,64",
    "EUR",
    "-2.105,03",
    "09-07-2020",
    "16:55",
    "MASTERCARD INCORPORATE",
    "US57636Q1040",
    "NSY",
    "-43",
    "USD",
    "293,06",
    "USD",
    "12.601,58",
    "EUR",
    "11.139,42",
    "1,1301",
    "EUR",
    "-0,65",
    "EUR",
    "11.138,77",
    "02-07-2020",
    "15:50",
    "MASTERCARD INCORPORATE",
    "US57636Q1040",
    "NSY",
    "-7",
    "USD",
    "305,15",
    "USD",
    "2.136,05",
    "EUR",
    "1.891,05",
    "1,1284",
    "EUR",
    "-0,52",
    "EUR",
    "1.890,53",
    "02-07-2020",
    "15:49",
    "TUCOWS INC. - COMMON S",
    "US8986972060",
    "NDQ",
    "20",
    "USD",
    "57,45",
    "USD",
    "-1.149,00",
    "EUR",
    "-1.019,43",
    "1,126",
    "EUR",
    "-0,57",
    "EUR",
    "-1.020,00",
    "15-06-2020",
    "19:00",
    "MASTERCARD INCORPORATE",
    "US57636Q1040",
    "NSY",
    "50",
    "USD",
    "295,00",
    "USD",
    "-14.750,00",
    "EUR",
    "-13.068,13",
    "1,1276",
    "EUR",
    "-0,68",
    "EUR",
    "-13.068,81",
    "15-06-2020",
    "12:21",
    "MEDICAL COLUMBUS AG",
    "DE0006618309",
    "XET",
    "-596",
    "EUR",
    "5,00",
    "EUR",
    "2.980,00",
    "EUR",
    "2.980,00",
    "EUR",
    "-2,54",
    "EUR",
    "2.977,46",
    "15-06-2020",
    "09:27",
    "COMPUTER MODELLING GROUP",
    "CA2052491057",
    "FRA",
    "-410",
    "EUR",
    "3,10",
    "EUR",
    "1.271,00",
    "EUR",
    "1.271,00",
    "EUR",
    "-8,64",
    "EUR",
    "1.262,36",
    "12-06-2020",
    "09:37",
    "COMPUTER MODELLING GROUP",
    "CA2052491057",
    "FRA",
    "-670",
    "EUR",
    "3,18",
    "EUR",
    "2.130,60",
    "EUR",
    "2.130,60",
    "EUR",
    "-9,42",
    "EUR",
    "2.121,18",
    "11-06-2020",
    "20:11",
    "NOW INC. COMMON STOCK",
    "US67011P1003",
    "NSY",
    "-500",
    "USD",
    "8,06",
    "USD",
    "4.030,00",
    "EUR",
    "3.554,53",
    "1,1326",
    "EUR",
    "-2,25",
    "EUR",
    "3.552,28",
    "08-06-2020",
    "15:33",
    "HEADHUNTER GROUP PLC -",
    "AMERICAN DEPOSITARY SHARES",
    "US42207L1061",
    "NDQ",
    "100",
    "USD",
    "22,99",
    "USD",
    "-2.299,00",
    "EUR",
    "-2.033,25",
    "1,1296",
    "EUR",
    "-0,85",
    "EUR",
    "-2.034,10",
    "04-06-2020",
    "15:42",
    "API GROUP CORP.",
    "US00187Y1001",
    "FRA",
    "400",
    "EUR",
    "11,10",
    "EUR",
    "-4.440,00",
    "EUR",
    "-4.440,00",
    "EUR",
    "-11,50",
    "EUR",
    "-4.451,50",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "rxoruvvdswszk@mdygah.hh",
    "I",
    "www.degiro.de",
    "Seite 4 /",
    "13",
    "Konto 2020-12-05"
  ],
  [
    "Herr Max Mustermann",
    "Musterstraße 1",
    "5555 Musterstadt",
    "Germany",
    "Benutzername:",
    "*****100",
    "(31000665)",
    "Datum",
    "Uhrzeit",
    "Produkt",
    "ISIN",
    "Börse",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährun",
    "Wert",
    "Wechselkur",
    "s",
    "Gebühr",
    "Gesamt",
    "04-06-2020",
    "09:06",
    "ROLLS-ROYCE HLG",
    "GB00B63H8491",
    "LSE",
    "1400",
    "GBX",
    "313,60",
    "GBX",
    "-439.040,00",
    "EUR",
    "-4.912,33",
    "89,2857",
    "EUR",
    "-6,45",
    "EUR",
    "-4.918,78",
    "04-06-2020",
    "09:05",
    "ROLLS-ROYCE HLG",
    "GB00B63H8491",
    "LSE",
    "-1400",
    "GBX",
    "313,80",
    "GBX",
    "439.320,00",
    "EUR",
    "4.902,08",
    "89,5295",
    "EUR",
    "-6,46",
    "EUR",
    "4.895,62",
    "04-06-2020",
    "09:04",
    "ROLLS-ROYCE HLG",
    "GB00B63H8491",
    "LSE",
    "-1400",
    "GBX",
    "316,30",
    "GBX",
    "442.820,00",
    "EUR",
    "4.941,13",
    "89,5295",
    "EUR",
    "-6,48",
    "EUR",
    "4.934,65",
    "03-06-2020",
    "20:20",
    "TUCOWS INC. - COMMON S",
    "US8986972060",
    "NDQ",
    "50",
    "USD",
    "62,21",
    "USD",
    "-3.110,50",
    "EUR",
    "-2.768,09",
    "1,1226",
    "EUR",
    "-0,68",
    "EUR",
    "-2.768,77",
    "03-06-2020",
    "20:18",
    "INTERACTIVE BROKERS GR",
    "US45841N1072",
    "NDQ",
    "-150",
    "USD",
    "44,15",
    "USD",
    "6.622,50",
    "EUR",
    "5.880,85",
    "1,125",
    "EUR",
    "-1,04",
    "EUR",
    "5.879,81",
    "03-06-2020",
    "20:05",
    "INTERACTIVE BROKERS GR",
    "US45841N1072",
    "NDQ",
    "150",
    "USD",
    "44,18",
    "USD",
    "-6.627,00",
    "EUR",
    "-5.894,78",
    "1,1231",
    "EUR",
    "-1,04",
    "EUR",
    "-5.895,82",
    "26-05-2020",
    "15:39",
    "SCORPIO TANKERS INC. C",
    "MHY7542C1306",
    "NSY",
    "-40",
    "USD",
    "17,22",
    "USD",
    "688,80",
    "EUR",
    "626,75",
    "1,0979",
    "EUR",
    "-0,65",
    "EUR",
    "626,10",
    "26-05-2020",
    "15:38",
    "TRUPANION INC. - COMM",
    "US8982021060",
    "NDQ",
    "200",
    "USD",
    "32,10",
    "USD",
    "-6.420,00",
    "EUR",
    "-5.853,39",
    "1,0957",
    "EUR",
    "-1,23",
    "EUR",
    "-5.854,62",
    "18-05-2020",
    "09:29",
    "ROLLS-ROYCE HLG",
    "GB00B63H8491",
    "LSE",
    "400",
    "GBX",
    "253,60",
    "GBX",
    "-101.440,00",
    "EUR",
    "-1.135,21",
    "89,2682",
    "EUR",
    "-4,57",
    "EUR",
    "-1.139,78",
    "04-05-2020",
    "10:10",
    "RYANAIR HOLDINGS PLC",
    "IE00BYTBXV33",
    "XET",
    "-400",
    "EUR",
    "9,508",
    "EUR",
    "3.803,20",
    "EUR",
    "3.803,20",
    "EUR",
    "-2,68",
    "EUR",
    "3.800,52",
    "29-04-2020",
    "13:05",
    "EURONAV",
    "BE0003816338",
    "EBR",
    "-300",
    "EUR",
    "10,85",
    "EUR",
    "3.255,00",
    "EUR",
    "3.255,00",
    "EUR",
    "-5,63",
    "EUR",
    "3.249,37",
    "28-04-2020",
    "09:34",
    "ROLLS-ROYCE HLG",
    "GB00B63H8491",
    "LSE",
    "900",
    "GBX",
    "309,6289",
    "GBX",
    "-278.666,00",
    "EUR",
    "-3.201,45",
    "86,9565",
    "EUR",
    "-5,60",
    "EUR",
    "-3.207,05",
    "28-04-2020",
    "09:34",
    "ROLLS-ROYCE HLG",
    "GB00B63H8491",
    "LSE",
    "100",
    "GBX",
    "309,70",
    "GBX",
    "-30.970,00",
    "EUR",
    "-355,65",
    "86,9936",
    "EUR",
    "-4,18",
    "EUR",
    "-359,83",
    "22-04-2020",
    "16:05",
    "SCORPIO TANKERS INC. C",
    "MHY7542C1306",
    "NSY",
    "40",
    "USD",
    "24,139",
    "USD",
    "-965,56",
    "EUR",
    "-889,59",
    "1,0843",
    "EUR",
    "-0,65",
    "EUR",
    "-890,24",
    "22-04-2020",
    "15:19",
    "EURONAV",
    "BE0003816338",
    "EBR",
    "300",
    "EUR",
    "10,8239",
    "EUR",
    "-3.247,18",
    "EUR",
    "-3.247,18",
    "EUR",
    "-5,62",
    "EUR",
    "-3.252,80",
    "01-04-2020",
    "18:16",
    "MASTERCARD INCORPORATE",
    "US57636Q1040",
    "NSY",
    "-20",
    "USD",
    "233,55",
    "USD",
    "4.671,00",
    "EUR",
    "4.264,63",
    "1,0942",
    "EUR",
    "-0,57",
    "EUR",
    "4.264,06",
    "01-04-2020",
    "16:22",
    "MASTERCARD INCORPORATE",
    "US57636Q1040",
    "NSY",
    "20",
    "USD",
    "233,44",
    "USD",
    "-4.668,80",
    "EUR",
    "-4.271,55",
    "1,0919",
    "EUR",
    "-0,57",
    "EUR",
    "-4.272,12",
    "31-03-2020",
    "14:47",
    "LOGO YAZILIM SANAYI VE TICAR",
    "TRALOGOW91U2",
    "ISE",
    "-349",
    "TRY",
    "59,1428",
    "TRY",
    "20.640,85",
    "EUR",
    "2.857,96",
    "7,215",
    "EUR",
    "-14,59",
    "EUR",
    "2.843,37",
    "31-03-2020",
    "12:29",
    "LOGO YAZILIM SANAYI VE TICAR",
    "TRALOGOW91U2",
    "ISE",
    "349",
    "TRY",
    "59,35",
    "TRY",
    "-20.713,15",
    "EUR",
    "-2.870,04",
    "7,2098",
    "EUR",
    "-14,59",
    "EUR",
    "-2.884,63",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "mjthlzkqzujud@txrhbw.sr",
    "I",
    "www.degiro.de",
    "Seite 5 /",
    "13",
    "Konto 2020-12-05"
  ],
  [
    "Herr Max Mustermann",
    "Musterstraße 1",
    "5555 Musterstadt",
    "Germany",
    "Benutzername:",
    "*****100",
    "(31000665)",
    "Datum",
    "Uhrzeit",
    "Produkt",
    "ISIN",
    "Börse",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährun",
    "Wert",
    "Wechselkur",
    "s",
    "Gebühr",
    "Gesamt",
    "30-03-2020",
    "16:23",
    "RYANAIR HOLDINGS PLC",
    "IE00BYTBXV33",
    "XET",
    "400",
    "EUR",
    "9,178",
    "EUR",
    "-3.671,20",
    "EUR",
    "-3.671,20",
    "EUR",
    "-2,66",
    "EUR",
    "-3.673,86",
    "30-03-2020",
    "16:02",
    "COMPUTER MODELLING GROUP",
    "CA2052491057",
    "FRA",
    "500",
    "EUR",
    "2,40",
    "EUR",
    "-1.200,00",
    "EUR",
    "-1.200,00",
    "EUR",
    "-8,58",
    "EUR",
    "-1.208,58",
    "30-03-2020",
    "15:45",
    "NOW INC. COMMON STOCK",
    "US67011P1003",
    "NSY",
    "500",
    "USD",
    "5,15",
    "USD",
    "-2.575,00",
    "EUR",
    "-2.336,45",
    "1,101",
    "EUR",
    "-2,32",
    "EUR",
    "-2.338,77",
    "23-03-2020",
    "15:56",
    "MEDICAL COLUMBUS AG",
    "DE0006618309",
    "XET",
    "-150",
    "EUR",
    "3,50",
    "EUR",
    "525,00",
    "EUR",
    "525,00",
    "EUR",
    "-2,09",
    "EUR",
    "522,91",
    "20-03-2020",
    "16:54",
    "BOOKING HOLDINGS INC",
    "US09857L1089",
    "NDQ",
    "-9",
    "USD",
    "1.245,60",
    "USD",
    "11.210,40",
    "EUR",
    "10.458,03",
    "1,0709",
    "EUR",
    "-0,53",
    "EUR",
    "10.457,50",
    "20-03-2020",
    "15:24",
    "BOOKING HOLDINGS INC",
    "US09857L1089",
    "NDQ",
    "9",
    "USD",
    "1.248,35",
    "USD",
    "-11.235,15",
    "EUR",
    "-10.471,76",
    "1,0718",
    "EUR",
    "-0,53",
    "EUR",
    "-10.472,29",
    "18-03-2020",
    "16:07",
    "INSTAL",
    "SE0009664253",
    "OMX",
    "250",
    "SEK",
    "85,70",
    "SEK",
    "-21.425,00",
    "EUR",
    "-1.932,74",
    "11,0742",
    "EUR",
    "-4,96",
    "EUR",
    "-1.937,70",
    "18-03-2020",
    "15:53",
    "FACEBOOK INC. - CLASS",
    "US30303M1027",
    "NDQ",
    "40",
    "USD",
    "144,53",
    "USD",
    "-5.781,20",
    "EUR",
    "-5.310,19",
    "1,0876",
    "EUR",
    "-0,65",
    "EUR",
    "-5.310,84",
    "04-03-2020",
    "16:27",
    "FACEBOOK INC. - CLASS",
    "US30303M1027",
    "NDQ",
    "15",
    "USD",
    "189,54",
    "USD",
    "-2.843,10",
    "EUR",
    "-2.556,97",
    "1,1108",
    "EUR",
    "-0,55",
    "EUR",
    "-2.557,52",
    "28-02-2020",
    "15:38",
    "INSTAL",
    "SE0009664253",
    "OMX",
    "300",
    "SEK",
    "132,8133",
    "SEK",
    "-39.844,00",
    "EUR",
    "-3.729,65",
    "10,6724",
    "EUR",
    "-5,86",
    "EUR",
    "-3.735,51",
    "28-02-2020",
    "15:36",
    "WIX.COM LTD. - ORDINAR",
    "IL0011301780",
    "NDQ",
    "-40",
    "USD",
    "130,32",
    "USD",
    "5.212,80",
    "EUR",
    "4.743,67",
    "1,0978",
    "EUR",
    "-0,65",
    "EUR",
    "4.743,02",
    "21-02-2020",
    "09:12",
    "MEDICAL COLUMBUS O.N - NON",
    "TRADEABLE",
    "DE0006618309",
    "DEG",
    "-186",
    "EUR",
    "4,75",
    "EUR",
    "883,50",
    "EUR",
    "883,50",
    "EUR",
    "883,50",
    "21-02-2020",
    "09:12",
    "MEDICAL COLUMBUS AG",
    "DE0006618309",
    "XET",
    "186",
    "EUR",
    "4,75",
    "EUR",
    "-883,50",
    "EUR",
    "-883,50",
    "EUR",
    "-883,50",
    "07-02-2020",
    "11:13",
    "MEDICAL COLUMBUS O.N - NON",
    "TRADEABLE",
    "DE000A255FT9",
    "DEG",
    "-2",
    "EUR",
    "0,00",
    "EUR",
    "0,00",
    "EUR",
    "0,00",
    "EUR",
    "0,00",
    "13-01-2020",
    "16:03",
    "WIX.COM LTD. - ORDINAR",
    "IL0011301780",
    "NDQ",
    "10",
    "USD",
    "143,62",
    "USD",
    "-1.436,20",
    "EUR",
    "-1.291,32",
    "1,1111",
    "EUR",
    "-0,54",
    "EUR",
    "-1.291,86",
    "13-01-2020",
    "15:49",
    "WIX.COM LTD. - ORDINAR",
    "IL0011301780",
    "NDQ",
    "30",
    "USD",
    "142,57",
    "USD",
    "-4.277,10",
    "EUR",
    "-3.845,27",
    "1,1112",
    "EUR",
    "-0,61",
    "EUR",
    "-3.845,88",
    "13-01-2020",
    "15:47",
    "NOW INC. COMMON STOCK",
    "US67011P1003",
    "NSY",
    "-532",
    "USD",
    "11,16",
    "USD",
    "5.937,12",
    "EUR",
    "5.326,80",
    "1,1135",
    "EUR",
    "-2,42",
    "EUR",
    "5.324,38",
    "06-01-2020",
    "00:00",
    "MEDICAL COLUMBUS O.N - NON",
    "TRADEABLE",
    "DE0006618309",
    "DEG",
    "186",
    "EUR",
    "4,75",
    "EUR",
    "-883,50",
    "EUR",
    "-883,50",
    "EUR",
    "-883,50",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "ngbpnsexkxbpb@kbfnal.zc",
    "I",
    "www.degiro.de",
    "Seite 6 /",
    "13",
    "Konto 2020-12-05"
  ],
  [
    "Herr Max Mustermann",
    "Musterstraße 1",
    "5555 Musterstadt",
    "Germany",
    "Benutzername:",
    "*****100",
    "(31000665)",
    "Datum",
    "Uhrzeit",
    "Produkt",
    "ISIN",
    "Börse",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährun",
    "Wert",
    "Wechselkur",
    "s",
    "Gebühr",
    "Gesamt",
    "06-01-2020",
    "00:00",
    "MEDICAL COLUMBUS O.N - NON",
    "TRADEABLE",
    "DE000A255FT9",
    "DEG",
    "-558",
    "EUR",
    "0,00",
    "EUR",
    "0,00",
    "EUR",
    "0,00",
    "EUR",
    "0,00",
    "12-12-2019",
    "00:00",
    "MEDICAL COLUMBUS O.N - NON",
    "TRADEABLE",
    "DE000A255FT9",
    "DEG",
    "560",
    "EUR",
    "0,00",
    "EUR",
    "0,00",
    "EUR",
    "0,00",
    "EUR",
    "0,00",
    "24-10-2019",
    "17:17",
    "COMPUTER MODELLING GROUP",
    "CA2052491057",
    "FRA",
    "580",
    "EUR",
    "4,58",
    "EUR",
    "-2.656,40",
    "EUR",
    "-2.656,40",
    "EUR",
    "-10,10",
    "EUR",
    "-2.666,50",
    "18-09-2019",
    "12:20",
    "INSTAL",
    "SE0009664253",
    "OMX",
    "350",
    "SEK",
    "96,40",
    "SEK",
    "-33.740,00",
    "EUR",
    "-3.142,53",
    "10,7259",
    "EUR",
    "-5,82",
    "EUR",
    "-3.148,35",
    "18-09-2019",
    "12:20",
    "DEFAMA DEUTSCHE FACHMARKT",
    "AG",
    "DE000A13SUL5",
    "XET",
    "-250",
    "EUR",
    "15,10",
    "EUR",
    "3.775,00",
    "EUR",
    "3.775,00",
    "EUR",
    "-2,98",
    "EUR",
    "3.772,02",
    "11-09-2019",
    "15:52",
    "DEFAMA DEUTSCHE FACHMARKT",
    "AG - NON TRADEABLE",
    "DE000A2YN736",
    "DEG",
    "-250",
    "EUR",
    "0,00",
    "EUR",
    "0,00",
    "EUR",
    "0,00",
    "EUR",
    "0,00",
    "27-08-2019",
    "00:00",
    "DEFAMA DEUTSCHE FACHMARKT",
    "AG - NON TRADEABLE",
    "DE000A2YN736",
    "DEG",
    "250",
    "EUR",
    "0,00",
    "EUR",
    "0,00",
    "EUR",
    "0,00",
    "EUR",
    "0,00",
    "14-08-2019",
    "11:07",
    "INSTAL",
    "SE0009664253",
    "OMX",
    "130",
    "SEK",
    "87,60",
    "SEK",
    "-11.388,00",
    "EUR",
    "-1.064,85",
    "10,6838",
    "EUR",
    "-4,62",
    "EUR",
    "-1.069,47",
    "02-07-2019",
    "10:00",
    "MEDICAL COLUMBUS AG",
    "DE0006618309",
    "XET",
    "170",
    "EUR",
    "7,20",
    "EUR",
    "-1.224,00",
    "EUR",
    "-1.224,00",
    "EUR",
    "-2,32",
    "EUR",
    "-1.226,32",
    "26-04-2019",
    "14:32",
    "MEDICAL COLUMBUS AG",
    "DE0006618309",
    "XET",
    "100",
    "EUR",
    "6,60",
    "EUR",
    "-660,00",
    "EUR",
    "-660,00",
    "EUR",
    "-2,17",
    "EUR",
    "-662,17",
    "28-02-2019",
    "21:07",
    "WEIGHT WATCHERS INTERN",
    "US9486261061",
    "NDQ",
    "-50",
    "USD",
    "20,61",
    "USD",
    "1.030,50",
    "EUR",
    "903,81",
    "1,139",
    "EUR",
    "-0,68",
    "EUR",
    "903,13",
    "01-02-2019",
    "16:26",
    "MEDICAL COLUMBUS AG",
    "DE0006618309",
    "XET",
    "140",
    "EUR",
    "6,45",
    "EUR",
    "-903,00",
    "EUR",
    "-903,00",
    "EUR",
    "-2,23",
    "EUR",
    "-905,23",
    "01-02-2019",
    "16:22",
    "SHAKE SHACK INC. CLAS",
    "US8190471016",
    "NSY",
    "-50",
    "USD",
    "48,29",
    "USD",
    "2.414,50",
    "EUR",
    "2.103,16",
    "1,1469",
    "EUR",
    "-0,67",
    "EUR",
    "2.102,49",
    "01-02-2019",
    "16:16",
    "MEDICAL COLUMBUS AG",
    "DE0006618309",
    "XET",
    "150",
    "EUR",
    "6,40",
    "EUR",
    "-960,00",
    "EUR",
    "-960,00",
    "EUR",
    "-2,25",
    "EUR",
    "-962,25",
    "27-12-2018",
    "16:17",
    "WEIGHT WATCHERS INTERN",
    "US9486261061",
    "NDQ",
    "50",
    "USD",
    "41,42",
    "USD",
    "-2.071,00",
    "EUR",
    "-1.813,57",
    "1,1408",
    "EUR",
    "-0,68",
    "EUR",
    "-1.814,25",
    "27-12-2018",
    "16:16",
    "WEIGHT WATCHERS INTERN",
    "US9486261061",
    "NDQ",
    "-50",
    "USD",
    "41,37",
    "USD",
    "2.068,50",
    "EUR",
    "1.807,97",
    "1,143",
    "EUR",
    "-0,68",
    "EUR",
    "1.807,29",
    "27-12-2018",
    "16:15",
    "NOW INC. COMMON STOCK",
    "US67011P1003",
    "NSY",
    "532",
    "USD",
    "11,29",
    "USD",
    "-6.006,28",
    "EUR",
    "-5.261,04",
    "1,1405",
    "EUR",
    "-2,36",
    "EUR",
    "-5.263,40",
    "27-12-2018",
    "16:15",
    "NOW INC. COMMON STOCK",
    "US67011P1003",
    "NSY",
    "-532",
    "USD",
    "11,25",
    "USD",
    "5.985,00",
    "EUR",
    "5.231,04",
    "1,143",
    "EUR",
    "-2,36",
    "EUR",
    "5.228,68",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "nmiymmzprcuou@xaqisn.vs",
    "I",
    "www.degiro.de",
    "Seite 7 /",
    "13",
    "Konto 2020-12-05"
  ],
  [
    "Herr Max Mustermann",
    "Musterstraße 1",
    "5555 Musterstadt",
    "Germany",
    "Benutzername:",
    "*****100",
    "(31000665)",
    "Datum",
    "Uhrzeit",
    "Produkt",
    "ISIN",
    "Börse",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährun",
    "Wert",
    "Wechselkur",
    "s",
    "Gebühr",
    "Gesamt",
    "17-12-2018",
    "16:53",
    "ALPHABET INC. - CLASS C",
    "US02079K1079",
    "NDQ",
    "-2",
    "USD",
    "1.037,60",
    "USD",
    "2.075,20",
    "EUR",
    "1.827,08",
    "1,1347",
    "EUR",
    "-0,51",
    "EUR",
    "1.826,57",
    "03-12-2018",
    "17:36",
    "WEIGHT WATCHERS INTERN",
    "US9486261061",
    "NDQ",
    "50",
    "USD",
    "50,86",
    "USD",
    "-2.543,00",
    "EUR",
    "-2.239,87",
    "1,1353",
    "EUR",
    "-2.239,87",
    "03-12-2018",
    "17:36",
    "WEIGHT WATCHERS INTERN",
    "US9486261061",
    "NSY",
    "-50",
    "USD",
    "50,86",
    "USD",
    "2.543,00",
    "EUR",
    "2.239,87",
    "1,1353",
    "EUR",
    "2.239,87",
    "12-11-2018",
    "16:42",
    "ALPHABET INC. - CLASS C",
    "US02079K1079",
    "NDQ",
    "-1",
    "USD",
    "1.044,44",
    "USD",
    "1.044,44",
    "EUR",
    "925,19",
    "1,1278",
    "EUR",
    "-0,50",
    "EUR",
    "924,69",
    "12-11-2018",
    "16:26",
    "WEIGHT WATCHERS INTERN",
    "US9486261061",
    "NSY",
    "15",
    "USD",
    "49,41",
    "USD",
    "-741,15",
    "EUR",
    "-657,77",
    "1,1256",
    "EUR",
    "-0,55",
    "EUR",
    "-658,32",
    "12-11-2018",
    "16:22",
    "WEIGHT WATCHERS INTERN",
    "US9486261061",
    "NSY",
    "35",
    "USD",
    "49,48",
    "USD",
    "-1.731,80",
    "EUR",
    "-1.536,62",
    "1,1259",
    "EUR",
    "-0,62",
    "EUR",
    "-1.537,24",
    "15-10-2018",
    "18:20",
    "SPOTIFY TECHNOLOGY S.A",
    "LU1778762911",
    "NSY",
    "-16",
    "USD",
    "160,50",
    "USD",
    "2.568,00",
    "EUR",
    "2.211,25",
    "1,1602",
    "EUR",
    "-0,56",
    "EUR",
    "2.210,69",
    "02-07-2018",
    "15:33",
    "SPOTIFY TECHNOLOGY S.A",
    "LU1778762911",
    "NSY",
    "16",
    "USD",
    "163,5825",
    "USD",
    "-2.617,32",
    "EUR",
    "-2.255,97",
    "1,159",
    "EUR",
    "-0,55",
    "EUR",
    "-2.256,52",
    "02-07-2018",
    "15:31",
    "ITURAN LOCATION AND CO",
    "IL0010818685",
    "NDQ",
    "-60",
    "USD",
    "30,25",
    "USD",
    "1.815,00",
    "EUR",
    "1.561,23",
    "1,1614",
    "EUR",
    "-0,71",
    "EUR",
    "1.560,52",
    "02-07-2018",
    "09:06",
    "RYMAN HEALTHCARE GRP LTD",
    "NZRYME0001S4",
    "FRA",
    "-230",
    "EUR",
    "6,81",
    "EUR",
    "1.566,30",
    "EUR",
    "1.566,30",
    "EUR",
    "-8,75",
    "EUR",
    "1.557,55",
    "27-06-2018",
    "10:10",
    "DEFAMA DEUTSCHE FACHMARKT",
    "AG",
    "DE000A13SUL5",
    "XET",
    "70",
    "EUR",
    "12,40",
    "EUR",
    "-868,00",
    "EUR",
    "-868,00",
    "EUR",
    "-2,07",
    "EUR",
    "-870,07",
    "25-06-2018",
    "15:42",
    "DEFAMA DEUTSCHE FACHMARKT",
    "AG",
    "DE000A13SUL5",
    "XET",
    "80",
    "EUR",
    "12,40",
    "EUR",
    "-992,00",
    "EUR",
    "-992,00",
    "EUR",
    "-2,08",
    "EUR",
    "-994,08",
    "25-06-2018",
    "15:41",
    "ITURAN LOCATION AND CO",
    "IL0010818685",
    "NDQ",
    "-40",
    "USD",
    "30,80",
    "USD",
    "1.232,00",
    "EUR",
    "1.051,87",
    "1,1701",
    "EUR",
    "-0,64",
    "EUR",
    "1.051,23",
    "25-06-2018",
    "15:40",
    "VIPSHOP HOLDINGS LIMIT",
    "US92763W1036",
    "NSY",
    "-87",
    "USD",
    "10,76",
    "USD",
    "936,12",
    "EUR",
    "799,34",
    "1,1699",
    "EUR",
    "-0,80",
    "EUR",
    "798,54",
    "25-06-2018",
    "11:02",
    "DEFAMA DEUTSCHE FACHMARKT",
    "AG",
    "DE000A13SUL5",
    "XET",
    "100",
    "EUR",
    "12,50",
    "EUR",
    "-1.250,00",
    "EUR",
    "-1.250,00",
    "EUR",
    "-2,10",
    "EUR",
    "-1.252,10",
    "15-05-2018",
    "18:57",
    "FUSION CONNECT INC",
    "US36116X1028",
    "NDQ",
    "-733",
    "USD",
    "5,09",
    "USD",
    "3.730,98",
    "EUR",
    "3.136,48",
    "1,1884",
    "EUR",
    "-2,97",
    "EUR",
    "3.133,51",
    "10-05-2018",
    "15:37",
    "TURBOS O.END RIB SOFT 23,371",
    "DE000PP62AS3",
    "FRA",
    "-300",
    "EUR",
    "0,19",
    "EUR",
    "57,00",
    "EUR",
    "57,00",
    "EUR",
    "-2,06",
    "EUR",
    "54,94",
    "09-05-2018",
    "14:40",
    "TRACSIS",
    "GB00B28HSF71",
    "LSE",
    "-160",
    "GBX",
    "550,00",
    "GBX",
    "88.000,00",
    "EUR",
    "1.004,79",
    "87,4929",
    "EUR",
    "-4,40",
    "EUR",
    "1.000,39",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "wqvpljsehqrli@sksccj.yl",
    "I",
    "www.degiro.de",
    "Seite 8 /",
    "13",
    "Konto 2020-12-05"
  ],
  [
    "Herr Max Mustermann",
    "Musterstraße 1",
    "5555 Musterstadt",
    "Germany",
    "Benutzername:",
    "*****100",
    "(31000665)",
    "Datum",
    "Uhrzeit",
    "Produkt",
    "ISIN",
    "Börse",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährun",
    "Wert",
    "Wechselkur",
    "s",
    "Gebühr",
    "Gesamt",
    "08-05-2018",
    "19:25",
    "ITURAN LOCATION AND CO",
    "IL0010818685",
    "NDQ",
    "50",
    "USD",
    "31,15",
    "USD",
    "-1.557,50",
    "EUR",
    "-1.311,42",
    "1,1865",
    "EUR",
    "-0,67",
    "EUR",
    "-1.312,09",
    "08-05-2018",
    "15:54",
    "WEIGHT WATCHERS INTERN",
    "US9486261061",
    "NSY",
    "-18",
    "USD",
    "66,95",
    "USD",
    "1.205,10",
    "EUR",
    "1.014,95",
    "1,1862",
    "EUR",
    "-0,56",
    "EUR",
    "1.014,39",
    "07-05-2018",
    "00:00",
    "FUSION TELECOMMUNICATI",
    "US36113B4005",
    "NDQ",
    "-1100",
    "USD",
    "3,30",
    "USD",
    "3.630,00",
    "EUR",
    "3.044,48",
    "1,1923",
    "EUR",
    "3.044,48",
    "07-05-2018",
    "00:00",
    "FUSION CONNECT INC",
    "US36116X1028",
    "NDQ",
    "733",
    "USD",
    "4,95",
    "USD",
    "-3.628,35",
    "EUR",
    "-3.043,10",
    "1,1923",
    "EUR",
    "-3.043,10",
    "27-04-2018",
    "13:58",
    "TURBOS O.END RIB SOFT 23,371",
    "DE000PP62AS3",
    "FRA",
    "300",
    "EUR",
    "0,41",
    "EUR",
    "-123,00",
    "EUR",
    "-123,00",
    "EUR",
    "-2,12",
    "EUR",
    "-125,12",
    "23-04-2018",
    "11:07",
    "PALADIN ONE ANLAGE-AKTI.F",
    "DE000A1W1PH8",
    "FRA",
    "-5",
    "EUR",
    "147,989",
    "EUR",
    "739,95",
    "EUR",
    "739,95",
    "EUR",
    "-8,09",
    "EUR",
    "731,86",
    "20-04-2018",
    "20:03",
    "ALPHABET INC. - CLASS C",
    "US02079K1079",
    "NDQ",
    "1",
    "USD",
    "1.079,01",
    "USD",
    "-1.079,01",
    "EUR",
    "-878,21",
    "1,2274",
    "EUR",
    "-0,50",
    "EUR",
    "-878,71",
    "20-04-2018",
    "20:02",
    "ALPHABET INC. - CLASS C",
    "US02079K1079",
    "NDQ",
    "1",
    "USD",
    "1.077,50",
    "USD",
    "-1.077,50",
    "EUR",
    "-876,98",
    "1,2274",
    "EUR",
    "-0,50",
    "EUR",
    "-877,48",
    "20-04-2018",
    "20:01",
    "ALPHABET INC. - CLASS C",
    "US02079K1079",
    "NDQ",
    "1",
    "USD",
    "1.077,16",
    "USD",
    "-1.077,16",
    "EUR",
    "-876,70",
    "1,2274",
    "EUR",
    "-0,50",
    "EUR",
    "-877,20",
    "17-04-2018",
    "15:38",
    "FACEBOOK INC. - CLASS",
    "US30303M1027",
    "NDQ",
    "10",
    "USD",
    "166,61",
    "USD",
    "-1.666,10",
    "EUR",
    "-1.348,54",
    "1,2342",
    "EUR",
    "-0,53",
    "EUR",
    "-1.349,07",
    "03-04-2018",
    "16:20",
    "ITURAN LOCATION AND CO",
    "IL0010818685",
    "NDQ",
    "50",
    "USD",
    "31,20",
    "USD",
    "-1.560,00",
    "EUR",
    "-1.272,34",
    "1,2249",
    "EUR",
    "-0,66",
    "EUR",
    "-1.273,00",
    "28-03-2018",
    "15:42",
    "FACEBOOK INC. - CLASS",
    "US30303M1027",
    "NDQ",
    "12",
    "USD",
    "152,53",
    "USD",
    "-1.830,36",
    "EUR",
    "-1.482,41",
    "1,2335",
    "EUR",
    "-0,54",
    "EUR",
    "-1.482,95",
    "28-03-2018",
    "15:40",
    "SHAKE SHACK INC. CLAS",
    "US8190471016",
    "NSY",
    "-23",
    "USD",
    "40,63",
    "USD",
    "934,49",
    "EUR",
    "755,42",
    "1,2358",
    "EUR",
    "-0,57",
    "EUR",
    "754,85",
    "28-03-2018",
    "15:40",
    "RYMAN HEALTHCARE GRP LTD",
    "NZRYME0001S4",
    "FRA",
    "-120",
    "EUR",
    "6,20",
    "EUR",
    "744,00",
    "EUR",
    "744,00",
    "EUR",
    "-8,10",
    "EUR",
    "735,90",
    "20-03-2018",
    "16:11",
    "FUSION TELECOMMUNICATI",
    "US36113B4005",
    "NDQ",
    "500",
    "USD",
    "2,63",
    "USD",
    "-1.315,00",
    "EUR",
    "-1.070,67",
    "1,227",
    "EUR",
    "-2,13",
    "EUR",
    "-1.072,80",
    "20-03-2018",
    "16:10",
    "MEDIOS AG",
    "DE000A1MMCC8",
    "XET",
    "-60",
    "EUR",
    "20,90",
    "EUR",
    "1.254,00",
    "EUR",
    "1.254,00",
    "EUR",
    "-2,10",
    "EUR",
    "1.251,90",
    "20-03-2018",
    "15:08",
    "FUSION TELECOMMUNICATI",
    "US36113B4005",
    "NDQ",
    "600",
    "USD",
    "2,6583",
    "USD",
    "-1.595,00",
    "EUR",
    "-1.299,74",
    "1,2259",
    "EUR",
    "-2,46",
    "EUR",
    "-1.302,20",
    "20-03-2018",
    "15:06",
    "GYM GRP (WI)",
    "GB00BZBX0P70",
    "LSE",
    "-600",
    "GBX",
    "251,62",
    "GBX",
    "150.972,00",
    "EUR",
    "1.719,36",
    "87,7193",
    "EUR",
    "-4,68",
    "EUR",
    "1.714,68",
    "30-01-2018",
    "15:33",
    "WEIGHT WATCHERS INTERN",
    "US9486261061",
    "NSY",
    "-16",
    "USD",
    "62,03",
    "USD",
    "992,48",
    "EUR",
    "795,86",
    "1,2458",
    "EUR",
    "-0,55",
    "EUR",
    "795,31",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "eosiakwyrkdmx@lgwfxr.un",
    "I",
    "www.degiro.de",
    "Seite 9 /",
    "13",
    "Konto 2020-12-05"
  ],
  [
    "Herr Max Mustermann",
    "Musterstraße 1",
    "5555 Musterstadt",
    "Germany",
    "Benutzername:",
    "*****100",
    "(31000665)",
    "Datum",
    "Uhrzeit",
    "Produkt",
    "ISIN",
    "Börse",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährun",
    "Wert",
    "Wechselkur",
    "s",
    "Gebühr",
    "Gesamt",
    "26-01-2018",
    "15:49",
    "TRACSIS",
    "GB00B28HSF71",
    "LSE",
    "160",
    "GBX",
    "540,00",
    "GBX",
    "-86.400,00",
    "EUR",
    "-987,13",
    "87,4393",
    "EUR",
    "-4,40",
    "EUR",
    "-991,53",
    "26-01-2018",
    "15:40",
    "WEIGHT WATCHERS INTERN",
    "US9486261061",
    "NSY",
    "-12",
    "USD",
    "65,35",
    "USD",
    "784,20",
    "EUR",
    "630,02",
    "1,2435",
    "EUR",
    "-0,54",
    "EUR",
    "629,48",
    "26-01-2018",
    "15:39",
    "VIPSHOP HOLDINGS LIMIT",
    "US92763W1036",
    "NSY",
    "-30",
    "USD",
    "17,65",
    "USD",
    "529,50",
    "EUR",
    "425,34",
    "1,2436",
    "EUR",
    "-0,60",
    "EUR",
    "424,74",
    "22-01-2018",
    "14:41",
    "RYMAN HEALTHCARE GRP LTD",
    "NZRYME0001S4",
    "FRA",
    "350",
    "EUR",
    "6,50",
    "EUR",
    "-2.275,00",
    "EUR",
    "-2.275,00",
    "EUR",
    "-9,32",
    "EUR",
    "-2.284,32",
    "18-01-2018",
    "15:30",
    "WEIGHT WATCHERS INTERN",
    "US9486261061",
    "NSY",
    "46",
    "USD",
    "61,79",
    "USD",
    "-2.842,34",
    "EUR",
    "-2.321,34",
    "1,2232",
    "EUR",
    "-0,65",
    "EUR",
    "-2.321,99",
    "18-01-2018",
    "13:32",
    "IWG",
    "JE00BYVQYS01",
    "LSE",
    "-170",
    "GBX",
    "269,90",
    "GBX",
    "45.883,00",
    "EUR",
    "518,86",
    "88,3416",
    "EUR",
    "-4,21",
    "EUR",
    "514,65",
    "18-01-2018",
    "11:28",
    "TGS-NOPEC GEOPHYSICAL",
    "NO0003078800",
    "OSL",
    "-91",
    "NOK",
    "208,60",
    "NOK",
    "18.982,60",
    "EUR",
    "1.968,42",
    "9,6339",
    "EUR",
    "-4,79",
    "EUR",
    "1.963,63",
    "16-01-2018",
    "16:53",
    "NOW INC. COMMON STOCK",
    "US67011P1003",
    "NSY",
    "104",
    "USD",
    "12,93",
    "USD",
    "-1.344,72",
    "EUR",
    "-1.099,96",
    "1,2213",
    "EUR",
    "-0,84",
    "EUR",
    "-1.100,80",
    "09-01-2018",
    "10:37",
    "IWG",
    "JE00BYVQYS01",
    "LSE",
    "-260",
    "GBX",
    "260,00",
    "GBX",
    "67.600,00",
    "EUR",
    "764,58",
    "88,326",
    "EUR",
    "-4,31",
    "EUR",
    "760,27",
    "04-01-2018",
    "15:37",
    "IWG",
    "JE00BYVQYS01",
    "LSE",
    "430",
    "GBX",
    "259,50",
    "GBX",
    "-111.585,00",
    "EUR",
    "-1.252,20",
    "89,0218",
    "EUR",
    "-4,50",
    "EUR",
    "-1.256,70",
    "04-01-2018",
    "15:33",
    "CHIPOTLE MEXICAN GRILL",
    "US1696561059",
    "NSY",
    "-4",
    "USD",
    "309,70",
    "USD",
    "1.238,80",
    "EUR",
    "1.024,79",
    "1,2076",
    "EUR",
    "-0,51",
    "EUR",
    "1.024,28",
    "19-12-2017",
    "15:30",
    "VIPSHOP HOLDINGS LIMIT",
    "US92763W1036",
    "NSY",
    "117",
    "USD",
    "11,80",
    "USD",
    "-1.380,60",
    "EUR",
    "-1.168,13",
    "1,1819",
    "EUR",
    "-0,90",
    "EUR",
    "-1.169,03",
    "19-12-2017",
    "12:52",
    "MOTORPOINT (WI)",
    "GB00BD0SFR60",
    "LSE",
    "-400",
    "GBX",
    "223,4519",
    "GBX",
    "89.380,75",
    "EUR",
    "1.010,00",
    "88,4956",
    "EUR",
    "-4,41",
    "EUR",
    "1.005,59",
    "11-12-2017",
    "16:16",
    "GYM GRP (WI)",
    "GB00BZBX0P70",
    "LSE",
    "600",
    "GBX",
    "216,0533",
    "GBX",
    "-129.632,00",
    "EUR",
    "-1.464,84",
    "88,4956",
    "EUR",
    "-4,59",
    "EUR",
    "-1.469,43",
    "11-12-2017",
    "16:15",
    "NATIONAL OILWELL VARCO",
    "US6370711011",
    "NSY",
    "-43",
    "USD",
    "33,24",
    "USD",
    "1.429,32",
    "EUR",
    "1.214,49",
    "1,1769",
    "EUR",
    "-0,65",
    "EUR",
    "1.213,84",
    "06-12-2017",
    "17:25",
    "NOW INC. COMMON STOCK",
    "US67011P1003",
    "NSY",
    "80",
    "USD",
    "10,25",
    "USD",
    "-820,00",
    "EUR",
    "-695,93",
    "1,1783",
    "EUR",
    "-0,77",
    "EUR",
    "-696,70",
    "30-11-2017",
    "16:09",
    "NOW INC. COMMON STOCK",
    "US67011P1003",
    "NSY",
    "50",
    "USD",
    "10,62",
    "USD",
    "-531,00",
    "EUR",
    "-446,09",
    "1,1903",
    "EUR",
    "-0,67",
    "EUR",
    "-446,76",
    "30-11-2017",
    "16:08",
    "SALESFORCE.COM INC COM",
    "US79466L3024",
    "NSY",
    "-12",
    "USD",
    "103,95",
    "USD",
    "1.247,40",
    "EUR",
    "1.047,94",
    "1,1903",
    "EUR",
    "-0,54",
    "EUR",
    "1.047,40",
    "24-11-2017",
    "15:35",
    "SALESFORCE.COM INC COM",
    "US79466L3024",
    "NSY",
    "12",
    "USD",
    "107,13",
    "USD",
    "-1.285,56",
    "EUR",
    "-1.079,23",
    "1,1912",
    "EUR",
    "-0,54",
    "EUR",
    "-1.079,77",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "fuunrxewbbqwm@ilwsas.uc",
    "I",
    "www.degiro.de",
    "Seite 10 /",
    "13",
    "Konto 2020-12-05"
  ],
  [
    "Herr Max Mustermann",
    "Musterstraße 1",
    "5555 Musterstadt",
    "Germany",
    "Benutzername:",
    "*****100",
    "(31000665)",
    "Datum",
    "Uhrzeit",
    "Produkt",
    "ISIN",
    "Börse",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährun",
    "Wert",
    "Wechselkur",
    "s",
    "Gebühr",
    "Gesamt",
    "24-11-2017",
    "15:34",
    "ADMIRAL GROUP PLC LS-,001",
    "GB00B02J6398",
    "XET",
    "-50",
    "EUR",
    "21,205",
    "EUR",
    "1.060,25",
    "EUR",
    "1.060,25",
    "EUR",
    "-2,08",
    "EUR",
    "1.058,17",
    "06-11-2017",
    "15:30",
    "NOW INC. COMMON STOCK",
    "US67011P1003",
    "NSY",
    "100",
    "USD",
    "10,93",
    "USD",
    "-1.093,00",
    "EUR",
    "-943,37",
    "1,1586",
    "EUR",
    "-0,85",
    "EUR",
    "-944,22",
    "27-10-2017",
    "15:43",
    "NOW INC. COMMON STOCK",
    "US67011P1003",
    "NSY",
    "50",
    "USD",
    "11,94",
    "USD",
    "-597,00",
    "EUR",
    "-515,15",
    "1,1589",
    "EUR",
    "-0,67",
    "EUR",
    "-515,82",
    "23-10-2017",
    "15:55",
    "SHAKE SHACK INC. CLAS",
    "US8190471016",
    "NSY",
    "40",
    "USD",
    "35,10",
    "USD",
    "-1.404,00",
    "EUR",
    "-1.195,37",
    "1,1745",
    "EUR",
    "-0,64",
    "EUR",
    "-1.196,01",
    "23-10-2017",
    "15:52",
    "WESTINGHOUSE AIR BRAKE",
    "US9297401088",
    "NSY",
    "-9",
    "USD",
    "76,27",
    "USD",
    "686,43",
    "EUR",
    "584,36",
    "1,1747",
    "EUR",
    "-0,53",
    "EUR",
    "583,83",
    "10-10-2017",
    "16:59",
    "CARVANA CO. CLASS A CO",
    "US1468691027",
    "NSY",
    "-57",
    "USD",
    "14,04",
    "USD",
    "800,28",
    "EUR",
    "677,76",
    "1,1808",
    "EUR",
    "-0,69",
    "EUR",
    "677,07",
    "06-10-2017",
    "16:47",
    "SHAKE SHACK INC. CLAS",
    "US8190471016",
    "NSY",
    "33",
    "USD",
    "34,29",
    "USD",
    "-1.131,57",
    "EUR",
    "-965,12",
    "1,1725",
    "EUR",
    "-0,61",
    "EUR",
    "-965,73",
    "06-10-2017",
    "16:43",
    "AUTOMATIC DATA PROCESS",
    "US0530151036",
    "NDQ",
    "-10",
    "USD",
    "112,99",
    "USD",
    "1.129,90",
    "EUR",
    "963,58",
    "1,1726",
    "EUR",
    "-0,53",
    "EUR",
    "963,05",
    "05-10-2017",
    "09:44",
    "ADMIRAL GROUP PLC LS-,001",
    "GB00B02J6398",
    "XET",
    "13",
    "EUR",
    "20,47",
    "EUR",
    "-266,11",
    "EUR",
    "-266,11",
    "EUR",
    "-2,02",
    "EUR",
    "-268,13",
    "05-10-2017",
    "09:43",
    "ADMIRAL GROUP PLC LS-,001",
    "GB00B02J6398",
    "XET",
    "37",
    "EUR",
    "20,47",
    "EUR",
    "-757,39",
    "EUR",
    "-757,39",
    "EUR",
    "-2,06",
    "EUR",
    "-759,45",
    "04-10-2017",
    "15:57",
    "AUTOMATIC DATA PROCESS",
    "US0530151036",
    "NDQ",
    "10",
    "USD",
    "109,76",
    "USD",
    "-1.097,60",
    "EUR",
    "-933,40",
    "1,1759",
    "EUR",
    "-0,53",
    "EUR",
    "-933,93",
    "29-09-2017",
    "16:19",
    "EDUCATIONAL DEVELOPMEN",
    "US2814791057",
    "NDQ",
    "-100",
    "USD",
    "9,60",
    "USD",
    "960,00",
    "EUR",
    "813,31",
    "1,1804",
    "EUR",
    "-0,84",
    "EUR",
    "812,47",
    "27-09-2017",
    "16:35",
    "NOW INC. COMMON STOCK",
    "US67011P1003",
    "NSY",
    "40",
    "USD",
    "13,22",
    "USD",
    "-528,80",
    "EUR",
    "-451,07",
    "1,1723",
    "EUR",
    "-0,64",
    "EUR",
    "-451,71",
    "22-09-2017",
    "17:17",
    "WESTINGHOUSE AIR BRAKE",
    "US9297401088",
    "NSY",
    "9",
    "USD",
    "76,15",
    "USD",
    "-685,35",
    "EUR",
    "-573,50",
    "1,195",
    "EUR",
    "-0,53",
    "EUR",
    "-574,03",
    "15-09-2017",
    "19:47",
    "CARVANA CO. CLASS A CO",
    "US1468691027",
    "NSY",
    "-60",
    "USD",
    "17,80",
    "USD",
    "1.068,00",
    "EUR",
    "894,56",
    "1,1939",
    "EUR",
    "-0,70",
    "EUR",
    "893,86",
    "13-09-2017",
    "19:52",
    "CARVANA CO. CLASS A CO",
    "US1468691027",
    "NSY",
    "52",
    "USD",
    "18,59",
    "USD",
    "-966,68",
    "EUR",
    "-813,27",
    "1,1886",
    "EUR",
    "-0,68",
    "EUR",
    "-813,95",
    "13-09-2017",
    "19:30",
    "CARVANA CO. CLASS A CO",
    "US1468691027",
    "NSY",
    "65",
    "USD",
    "18,86",
    "USD",
    "-1.225,90",
    "EUR",
    "-1.031,35",
    "1,1886",
    "EUR",
    "-0,72",
    "EUR",
    "-1.032,07",
    "13-09-2017",
    "16:12",
    "CHIPOTLE MEXICAN GRILL",
    "US1696561059",
    "NSY",
    "2",
    "USD",
    "309,99",
    "USD",
    "-619,98",
    "EUR",
    "-521,59",
    "1,1886",
    "EUR",
    "-0,51",
    "EUR",
    "-522,10",
    "13-09-2017",
    "10:10",
    "MOTORPOINT (WI)",
    "GB00BD0SFR60",
    "LSE",
    "400",
    "GBX",
    "133,50",
    "GBX",
    "-53.400,00",
    "EUR",
    "-593,59",
    "89,9604",
    "EUR",
    "-4,24",
    "EUR",
    "-597,83",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "hlokqblkeijjs@znfzlg.sa",
    "I",
    "www.degiro.de",
    "Seite 11 /",
    "13",
    "Konto 2020-12-05"
  ],
  [
    "Herr Max Mustermann",
    "Musterstraße 1",
    "5555 Musterstadt",
    "Germany",
    "Benutzername:",
    "*****100",
    "(31000665)",
    "Datum",
    "Uhrzeit",
    "Produkt",
    "ISIN",
    "Börse",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährun",
    "Wert",
    "Wechselkur",
    "s",
    "Gebühr",
    "Gesamt",
    "12-09-2017",
    "19:14",
    "THE JOINT CORP. - COMM",
    "US47973J1025",
    "NDQ",
    "-300",
    "USD",
    "4,9673",
    "USD",
    "1.490,18",
    "EUR",
    "1.245,49",
    "1,1965",
    "EUR",
    "-1,49",
    "EUR",
    "1.244,00",
    "11-09-2017",
    "13:14",
    "TEVA PHARMACEUT. SP.ADR",
    "US8816242098",
    "FRA",
    "-40",
    "EUR",
    "14,312",
    "EUR",
    "572,48",
    "EUR",
    "572,48",
    "EUR",
    "-7,96",
    "EUR",
    "564,52",
    "11-09-2017",
    "11:57",
    "TEVA PHARMACEUT. SP.ADR",
    "US8816242098",
    "FRA",
    "40",
    "EUR",
    "14,636",
    "EUR",
    "-585,44",
    "EUR",
    "-585,44",
    "EUR",
    "-7,97",
    "EUR",
    "-593,41",
    "05-09-2017",
    "14:11",
    "888 HLDGS",
    "GI000A0F6407",
    "LSE",
    "-190",
    "GBX",
    "253,00",
    "GBX",
    "48.070,00",
    "EUR",
    "525,89",
    "91,4077",
    "EUR",
    "-4,21",
    "EUR",
    "521,68",
    "28-08-2017",
    "20:37",
    "THE JOINT CORP. - COMM",
    "US47973J1025",
    "NDQ",
    "300",
    "USD",
    "4,00",
    "USD",
    "-1.200,00",
    "EUR",
    "-1.001,76",
    "1,1979",
    "EUR",
    "-1,50",
    "EUR",
    "-1.003,26",
    "02-08-2017",
    "11:23",
    "MEDIOS AG",
    "DE000A1MMCC8",
    "XET",
    "60",
    "EUR",
    "9,638",
    "EUR",
    "-578,28",
    "EUR",
    "-578,28",
    "EUR",
    "-2,05",
    "EUR",
    "-580,33",
    "23-06-2017",
    "14:38",
    "PALADIN ONE ANLAGE-AKTI.F",
    "DE000A1W1PH8",
    "FRA",
    "5",
    "EUR",
    "137,565",
    "EUR",
    "-687,83",
    "EUR",
    "-687,83",
    "EUR",
    "-8,05",
    "EUR",
    "-695,88",
    "22-06-2017",
    "16:17",
    "IFA SYSTEMS AG",
    "DE0007830788",
    "XET",
    "-50",
    "EUR",
    "12,70",
    "EUR",
    "635,00",
    "EUR",
    "635,00",
    "EUR",
    "-2,05",
    "EUR",
    "632,95",
    "22-06-2017",
    "16:17",
    "CHIPOTLE MEXICAN GRILL",
    "US1696561059",
    "NSY",
    "2",
    "USD",
    "419,84",
    "USD",
    "-839,68",
    "EUR",
    "-753,02",
    "1,1151",
    "EUR",
    "-0,51",
    "EUR",
    "-753,53",
    "22-06-2017",
    "16:15",
    "NOW INC. COMMON STOCK",
    "US67011P1003",
    "NSY",
    "70",
    "USD",
    "15,28",
    "USD",
    "-1.069,60",
    "EUR",
    "-959,22",
    "1,1151",
    "EUR",
    "-0,75",
    "EUR",
    "-959,97",
    "22-06-2017",
    "16:15",
    "NOVO NORDISK B A/S",
    "DK0060534915",
    "OMK",
    "-30",
    "DKK",
    "290,90",
    "DKK",
    "8.727,00",
    "EUR",
    "1.173,78",
    "7,4349",
    "EUR",
    "-4,47",
    "EUR",
    "1.169,31",
    "21-06-2017",
    "19:52",
    "NATIONAL OILWELL VARCO",
    "US6370711011",
    "NSY",
    "20",
    "USD",
    "32,03",
    "USD",
    "-640,60",
    "EUR",
    "-574,49",
    "1,1151",
    "EUR",
    "-0,57",
    "EUR",
    "-575,06",
    "21-06-2017",
    "19:50",
    "AMERICAN SHARED HOSPITAL SER",
    "US0295951059",
    "ASE",
    "-220",
    "USD",
    "3,80",
    "USD",
    "836,00",
    "EUR",
    "749,72",
    "1,1151",
    "EUR",
    "-1,29",
    "EUR",
    "748,43",
    "20-06-2017",
    "19:10",
    "AMERICAN SHARED HOSPITAL SER",
    "US0295951059",
    "ASE",
    "-10",
    "USD",
    "3,90",
    "USD",
    "39,00",
    "EUR",
    "35,06",
    "1,1123",
    "EUR",
    "-0,54",
    "EUR",
    "34,52",
    "13-06-2017",
    "21:42",
    "AMERICAN SHARED HOSPITAL SER",
    "US0295951059",
    "ASE",
    "55",
    "USD",
    "4,10",
    "USD",
    "-225,50",
    "EUR",
    "-201,19",
    "1,1208",
    "EUR",
    "-0,70",
    "EUR",
    "-201,89",
    "12-06-2017",
    "16:06",
    "AMERICAN SHARED HOSPITAL SER",
    "US0295951059",
    "ASE",
    "175",
    "USD",
    "4,10",
    "USD",
    "-717,50",
    "EUR",
    "-640,44",
    "1,1203",
    "EUR",
    "-1,13",
    "EUR",
    "-641,57",
    "12-06-2017",
    "16:05",
    "SMT SCHARF AG",
    "DE0005751986",
    "XET",
    "-56",
    "EUR",
    "12,551",
    "EUR",
    "702,86",
    "EUR",
    "702,86",
    "EUR",
    "-2,06",
    "EUR",
    "700,80",
    "13-03-2017",
    "19:16",
    "NOW INC. COMMON STOCK",
    "US67011P1003",
    "NSY",
    "38",
    "USD",
    "17,02",
    "USD",
    "-646,76",
    "EUR",
    "-607,11",
    "1,0653",
    "EUR",
    "-0,64",
    "EUR",
    "-607,75",
    "13-03-2017",
    "19:15",
    "BARNES & NOBLE EDUCATI",
    "US06777U1016",
    "NSY",
    "-59",
    "USD",
    "9,34",
    "USD",
    "551,06",
    "EUR",
    "517,28",
    "1,0653",
    "EUR",
    "-0,72",
    "EUR",
    "516,56",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "pbufwgtxlevuw@evgsxa.id",
    "I",
    "www.degiro.de",
    "Seite 12 /",
    "13",
    "Konto 2020-12-05"
  ],
  [
    "Herr Max Mustermann",
    "Musterstraße 1",
    "5555 Musterstadt",
    "Germany",
    "Benutzername:",
    "*****100",
    "(31000665)",
    "Datum",
    "Uhrzeit",
    "Produkt",
    "ISIN",
    "Börse",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährun",
    "Wert",
    "Wechselkur",
    "s",
    "Gebühr",
    "Gesamt",
    "01-02-2017",
    "15:31",
    "EDUCATIONAL DEVELOPMEN",
    "US2814791057",
    "NDQ",
    "100",
    "USD",
    "7,55",
    "USD",
    "-755,00",
    "EUR",
    "-701,85",
    "1,0757",
    "EUR",
    "-0,87",
    "EUR",
    "-702,72",
    "01-02-2017",
    "15:28",
    "AGGREKO",
    "GB00BK1PTB77",
    "LSE",
    "-33",
    "GBX",
    "1.000,00",
    "GBX",
    "33.000,00",
    "EUR",
    "389,40",
    "84,7458",
    "EUR",
    "-4,15",
    "EUR",
    "385,25",
    "01-02-2017",
    "15:28",
    "SHARP",
    "JP3359600008",
    "FRA",
    "-86",
    "EUR",
    "2,505",
    "EUR",
    "215,43",
    "EUR",
    "215,43",
    "EUR",
    "-7,67",
    "EUR",
    "207,76",
    "05-09-2016",
    "13:03",
    "IFA SYSTEMS AG",
    "DE0007830788",
    "XET",
    "50",
    "EUR",
    "11,095",
    "EUR",
    "-554,75",
    "EUR",
    "-554,75",
    "EUR",
    "-2,04",
    "EUR",
    "-556,79",
    "15-08-2016",
    "09:03",
    "NOVO NORDISK B A/S",
    "DK0060534915",
    "OMK",
    "10",
    "DKK",
    "308,70",
    "DKK",
    "-3.087,00",
    "EUR",
    "-414,89",
    "7,4405",
    "EUR",
    "-4,17",
    "EUR",
    "-419,06",
    "22-07-2016",
    "09:42",
    "NOVO NORDISK B A/S",
    "DK0060534915",
    "OMK",
    "20",
    "DKK",
    "371,30",
    "DKK",
    "-7.426,00",
    "EUR",
    "-998,05",
    "7,4405",
    "EUR",
    "-4,40",
    "EUR",
    "-1.002,45",
    "01-04-2016",
    "13:45",
    "TGS-NOPEC GEOPHYSICAL",
    "NO0003078800",
    "OSL",
    "54",
    "NOK",
    "124,40",
    "NOK",
    "-6.717,60",
    "EUR",
    "-711,39",
    "9,4429",
    "EUR",
    "-4,28",
    "EUR",
    "-715,67",
    "08-03-2016",
    "12:08",
    "AGGREKO",
    "GB00BK1PTB77",
    "LSE",
    "33",
    "GBX",
    "1.062,00",
    "GBX",
    "-35.046,00",
    "EUR",
    "-452,79",
    "77,3994",
    "EUR",
    "-4,18",
    "EUR",
    "-456,97",
    "08-03-2016",
    "09:25",
    "888 HLDGS",
    "GI000A0F6407",
    "LSE",
    "190",
    "GBX",
    "176,00",
    "GBX",
    "-33.440,00",
    "EUR",
    "-432,08",
    "77,3934",
    "EUR",
    "-4,17",
    "EUR",
    "-436,25",
    "07-03-2016",
    "19:53",
    "DOLBY LABORATORIES COM",
    "US25659T1079",
    "NSY",
    "-22",
    "USD",
    "40,23",
    "USD",
    "885,06",
    "EUR",
    "804,17",
    "1,1006",
    "EUR",
    "-0,58",
    "EUR",
    "803,59",
    "01-02-2016",
    "15:29",
    "SHARP",
    "JP3359600008",
    "FRA",
    "86",
    "EUR",
    "1,10",
    "EUR",
    "-94,60",
    "EUR",
    "-94,60",
    "EUR",
    "-7,58",
    "EUR",
    "-102,18",
    "11-01-2016",
    "15:52",
    "BARNES & NOBLE EDUCATI",
    "US06777U1016",
    "NSY",
    "59",
    "USD",
    "9,29",
    "USD",
    "-548,11",
    "EUR",
    "-504,75",
    "1,0859",
    "EUR",
    "-0,72",
    "EUR",
    "-505,47",
    "31-12-2015",
    "15:44",
    "NATIONAL OILWELL VARCO",
    "US6370711011",
    "NSY",
    "23",
    "USD",
    "33,74",
    "USD",
    "-776,02",
    "EUR",
    "-714,71",
    "1,0858",
    "EUR",
    "-0,58",
    "EUR",
    "-715,29",
    "05-11-2015",
    "09:02",
    "SMT SCHARF AG",
    "DE0005751986",
    "XET",
    "56",
    "EUR",
    "11,50",
    "EUR",
    "-644,00",
    "EUR",
    "-644,00",
    "EUR",
    "-2,05",
    "EUR",
    "-646,05",
    "08-05-2015",
    "15:01",
    "TGS-NOPEC GEOPHYSICAL",
    "NO0003078800",
    "OSL",
    "37",
    "NOK",
    "185,50",
    "NOK",
    "-6.863,50",
    "EUR",
    "-819,50",
    "8,3752",
    "EUR",
    "-4,33",
    "EUR",
    "-823,83",
    "28-01-2015",
    "15:18",
    "DOLBY LABORATORIES COM",
    "US25659T1079",
    "NSY",
    "22",
    "USD",
    "39,62",
    "USD",
    "-871,64",
    "EUR",
    "-772,27",
    "1,1287",
    "EUR",
    "-0,58",
    "EUR",
    "-772,85",
    "27-01-2015",
    "11:54",
    "SNOWBIRD AG",
    "DE000A1PHEL8",
    "XET",
    "-196",
    "EUR",
    "4,10",
    "EUR",
    "803,60",
    "EUR",
    "803,60",
    "EUR",
    "-2,06",
    "EUR",
    "801,54",
    "02-01-2015",
    "11:49",
    "SNOWBIRD AG",
    "DE000A1PHEL8",
    "XET",
    "196",
    "EUR",
    "5,10",
    "EUR",
    "-999,60",
    "EUR",
    "-999,60",
    "EUR",
    "-2,08",
    "EUR",
    "-1.001,68",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "cqqnpaqtqltzb@ajxbhy.pp",
    "I",
    "www.degiro.de",
    "Seite 13 /",
    "13",
    "Konto 2020-12-05"
  ]
]

```

</p></details>

## Community profile

https://app.tresor.one/p/5fcb9617b4312b0031332377

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #464: Broker Degiro; Verkäufe werden als Kauf dargestellt.
Perspektivisch wäre es noch cool, wenn auch der Börsenplatz Nasdaq und New York Stock Exchange zur Auswahl stünden inkl. USD Kurs. Aber ich kann natürlich verstehen, dass dies keine Prio 1 hat. 

## Document
<details><summary>Transactions-Degiro.pdf</summary><p>

```json
[
  [
    "Ygmj Pljjwem Rexobb Aöcx",
    "Epgz.-Xijsmm-Xxw. 6",
    "96306 Kzhosiwojrzn",
    "Rdauysc",
    "Ionvdielhcbj:",
    "****whj",
    "(09302658)",
    "Transaktionsübersicht von 07-12-2020 bis 13-12-2020",
    "Datum",
    "Uhrzeit",
    "Produkt",
    "ISIN",
    "Börse",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährun",
    "Wert",
    "Wechselkur",
    "s",
    "Gebühr",
    "Gesamt",
    "11-12-2020",
    "17:25",
    "TRIPADVISOR INC. - CO",
    "US8969452015",
    "NDQ",
    "-47",
    "USD",
    "28,72",
    "USD",
    "1.349,84",
    "EUR",
    "1.112,23",
    "1,2124",
    "EUR",
    "-0,66",
    "EUR",
    "1.111,57",
    "11-12-2020",
    "17:25",
    "CANADIAN SOLAR INC. -",
    "CA1366351098",
    "NDQ",
    "-32",
    "USD",
    "38,34",
    "USD",
    "1.226,88",
    "EUR",
    "1.011,01",
    "1,2123",
    "EUR",
    "-0,61",
    "EUR",
    "1.010,40",
    "11-12-2020",
    "17:25",
    "BLOOM ENERGY CORPORATI",
    "US0937121079",
    "NSY",
    "-70",
    "USD",
    "24,571",
    "USD",
    "1.719,97",
    "EUR",
    "1.417,33",
    "1,2123",
    "EUR",
    "-0,73",
    "EUR",
    "1.416,60",
    "11-12-2020",
    "14:41",
    "TURBOC O.END",
    "SOFTWARE23,858047",
    "DE000UD6C6X7",
    "FRA",
    "970",
    "EUR",
    "1,03",
    "EUR",
    "-999,10",
    "EUR",
    "-999,10",
    "EUR",
    "-3,10",
    "EUR",
    "-1.002,20",
    "11-12-2020",
    "13:20",
    "HVB MINIBE O.END DAIMLER 63,8",
    "DE000HR3BFL9",
    "FRA",
    "819",
    "EUR",
    "1,23",
    "EUR",
    "-1.007,37",
    "EUR",
    "-1.007,37",
    "EUR",
    "-3,11",
    "EUR",
    "-1.010,48",
    "11-12-2020",
    "12:35",
    "FORMYCON AG",
    "DE000A1EWVY8",
    "XET",
    "-12",
    "EUR",
    "55,00",
    "EUR",
    "660,00",
    "EUR",
    "660,00",
    "EUR",
    "-2,12",
    "EUR",
    "657,88",
    "11-12-2020",
    "11:48",
    "TURBOC O.END DAX 11939,474489",
    "DE000UE38JY6",
    "FRA",
    "85",
    "EUR",
    "11,71",
    "EUR",
    "-995,35",
    "EUR",
    "-995,35",
    "EUR",
    "-3,09",
    "EUR",
    "-998,44",
    "11-12-2020",
    "11:15",
    "WESTWING GROUP AG",
    "DE000A2N4H07",
    "XET",
    "32",
    "EUR",
    "31,50",
    "EUR",
    "-1.008,00",
    "EUR",
    "-1.008,00",
    "EUR",
    "-2,18",
    "EUR",
    "-1.010,18",
    "10-12-2020",
    "16:23",
    "RIOT BLOCKCHAIN INC",
    "US7672921050",
    "NDQ",
    "134",
    "USD",
    "8,85",
    "USD",
    "-1.185,90",
    "EUR",
    "-977,26",
    "1,2123",
    "EUR",
    "-0,94",
    "EUR",
    "-978,20",
    "10-12-2020",
    "09:43",
    "FORMYCON AG",
    "DE000A1EWVY8",
    "XET",
    "-13",
    "EUR",
    "53,40",
    "EUR",
    "694,20",
    "EUR",
    "694,20",
    "EUR",
    "-2,12",
    "EUR",
    "692,08",
    "09-12-2020",
    "18:56",
    "TURBOC",
    "O.ENDQUALCOMM119,914819",
    "DE000UE10W85",
    "FRA",
    "-408",
    "EUR",
    "3,17",
    "EUR",
    "1.293,36",
    "EUR",
    "1.293,36",
    "EUR",
    "-3,42",
    "EUR",
    "1.289,94",
    "09-12-2020",
    "15:30",
    "CALL 15.09.21 MICROSO. 220",
    "DE000TT09BU2",
    "FRA",
    "370",
    "EUR",
    "1,64",
    "EUR",
    "-606,80",
    "EUR",
    "-606,80",
    "EUR",
    "-2,67",
    "EUR",
    "-609,47",
    "09-12-2020",
    "09:05",
    "FORMYCON AG",
    "DE000A1EWVY8",
    "XET",
    "25",
    "EUR",
    "40,90",
    "EUR",
    "-1.022,50",
    "EUR",
    "-1.022,50",
    "EUR",
    "-2,18",
    "EUR",
    "-1.024,68",
    "08-12-2020",
    "19:50",
    "CALL 17.12.21 DANAHER 240",
    "DE000SB2XH23",
    "FRA",
    "280",
    "EUR",
    "2,11",
    "EUR",
    "-590,80",
    "EUR",
    "-590,80",
    "EUR",
    "-2,65",
    "EUR",
    "-593,45",
    "08-12-2020",
    "16:56",
    "CALL 17.09.21 SALESFOR 240",
    "DE000VP9PSP4",
    "FRA",
    "270",
    "EUR",
    "2,25",
    "EUR",
    "-607,50",
    "EUR",
    "-607,50",
    "EUR",
    "-2,67",
    "EUR",
    "-610,17",
    "08-12-2020",
    "16:55",
    "CALL 16.12.21 NEXTERA 75",
    "DE000KB9J0M8",
    "FRA",
    "970",
    "EUR",
    "0,62",
    "EUR",
    "-601,40",
    "EUR",
    "-601,40",
    "EUR",
    "-2,66",
    "EUR",
    "-604,06",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "yjiwjjsbxyuzd@xcprqh.lt",
    "I",
    "www.degiro.de",
    "Seite 1 /",
    "1",
    "Jhcxn 0458-99-14"
  ]
]

```

</p></details>

## Community profile

https://community.tresor.one/u/bf011a53

---
Issue submitted with https://import.tresor.one

### LINKED ISSUE #465: DEGIRO Einlesen Käufe und Verkäufe
## Document
<details><summary>Transactions.pdf</summary><p>

```json
[
  [
    "Dkli Qiors Gbfdga",
    "Umcfl-Siyp-Uin 4",
    "0154 Güesie",
    "Axljvutyjhe",
    "Benutzername:",
    "****jtu",
    "(843769915)",
    "Transaktionsübersicht von 01-01-2020 bis 13-12-2020",
    "Datum",
    "Uhrzeit",
    "Produkt",
    "ISIN",
    "Börse",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährun",
    "Wert",
    "Wechselkur",
    "s",
    "Gebühr",
    "Gesamt",
    "10-12-2020",
    "17:14",
    "GLADSTONE COMMERCIAL C",
    "US3765361080",
    "NDQ",
    "2",
    "USD",
    "18.25",
    "USD",
    "-36.50",
    "CHF",
    "-32.41",
    "1.1252",
    "CHF",
    "-0.55",
    "CHF",
    "-32.96",
    "10-12-2020",
    "16:25",
    "TURMALINA METALS",
    "CA90022K1003",
    "FRA",
    "-100",
    "EUR",
    "0.471",
    "EUR",
    "47.10",
    "CHF",
    "50.57",
    "0.9305",
    "CHF",
    "-8.13",
    "CHF",
    "42.44",
    "18-08-2020",
    "12:13",
    "WIRECARD AG",
    "DE0007472060",
    "XET",
    "-4",
    "EUR",
    "1.3622",
    "EUR",
    "5.45",
    "CHF",
    "5.86",
    "0.9285",
    "CHF",
    "-4.32",
    "CHF",
    "1.54",
    "22-06-2020",
    "11:38",
    "NEL ASA NK-,20",
    "NO0010081235",
    "FRA",
    "25",
    "EUR",
    "1.7645",
    "EUR",
    "-44.11",
    "CHF",
    "-47.00",
    "0.9377",
    "CHF",
    "-8.04",
    "CHF",
    "-55.04",
    "22-06-2020",
    "10:57",
    "TURMALINA METALS",
    "CA90022K1003",
    "FRA",
    "100",
    "EUR",
    "0.836",
    "EUR",
    "-83.60",
    "CHF",
    "-89.10",
    "0.9373",
    "CHF",
    "-8.08",
    "CHF",
    "-97.18",
    "16-06-2020",
    "00:00",
    "NEL ASA            NK-,20 - NON",
    "TRADEABLE",
    "NO0010892722",
    "DEG",
    "0",
    "EUR",
    "0.00",
    "EUR",
    "0.00",
    "CHF",
    "0.00",
    "0.9332",
    "CHF",
    "0.00",
    "11-05-2020",
    "12:52",
    "NEXI",
    "IT0005366767",
    "MIL",
    "3",
    "EUR",
    "13.95",
    "EUR",
    "-41.85",
    "CHF",
    "-44.03",
    "0.9496",
    "CHF",
    "-4.23",
    "CHF",
    "-48.26",
    "11-05-2020",
    "09:00",
    "BLACKROCK ISHARES S&P 500",
    "INFORMATION TECHNOLOGY SEC...",
    "IE00B3WJKG14",
    "SWX",
    "-3",
    "USD",
    "11.988",
    "USD",
    "35.96",
    "CHF",
    "34.85",
    "1.0308",
    "CHF",
    "-2.12",
    "CHF",
    "32.73",
    "28-04-2020",
    "10:51",
    "VANECK VECTORS",
    "VIDEOGAMING&ESPORTS UCITS",
    "ETF USD A",
    "IE00BYWQWR46",
    "XET",
    "4",
    "EUR",
    "24.425",
    "EUR",
    "-97.70",
    "CHF",
    "-103.49",
    "0.9431",
    "CHF",
    "-2.15",
    "CHF",
    "-105.64",
    "28-04-2020",
    "10:50",
    "WIRECARD AG",
    "DE0007472060",
    "XET",
    "1",
    "EUR",
    "114.80",
    "EUR",
    "-114.80",
    "CHF",
    "-121.57",
    "0.9433",
    "CHF",
    "-4.30",
    "CHF",
    "-125.87",
    "27-04-2020",
    "16:22",
    "AYTU BIOSCIENCE INC.",
    "US0547547002",
    "NDQ",
    "-30",
    "USD",
    "1.85",
    "USD",
    "55.50",
    "CHF",
    "54.04",
    "1.026",
    "CHF",
    "-0.65",
    "CHF",
    "53.39",
    "23-04-2020",
    "09:04",
    "VANECK VECTORS",
    "VIDEOGAMING&ESPORTS UCITS",
    "ETF USD A",
    "IE00BYWQWR46",
    "XET",
    "1",
    "EUR",
    "23.83",
    "EUR",
    "-23.83",
    "CHF",
    "-25.06",
    "0.95",
    "CHF",
    "-2.12",
    "CHF",
    "-27.18",
    "22-04-2020",
    "14:56",
    "XIAOMI CORP. CL.B",
    "KYG9830T1067",
    "FRA",
    "80",
    "EUR",
    "1.2098",
    "EUR",
    "-96.78",
    "CHF",
    "-101.88",
    "0.949",
    "CHF",
    "-7.99",
    "CHF",
    "-109.87",
    "20-04-2020",
    "16:11",
    "WIRECARD AG",
    "DE0007472060",
    "XET",
    "2",
    "EUR",
    "120.60",
    "EUR",
    "-241.20",
    "CHF",
    "-253.67",
    "0.9499",
    "CHF",
    "-4.34",
    "CHF",
    "-258.01",
    "20-04-2020",
    "16:05",
    "AYTU BIOSCIENCE INC.",
    "US0547547002",
    "NDQ",
    "15",
    "USD",
    "1.45",
    "USD",
    "-21.75",
    "CHF",
    "-21.05",
    "1.0322",
    "CHF",
    "-0.59",
    "CHF",
    "-21.64",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "tcxxajidweaxq@osccts.yr",
    "I",
    "www.degiro.ch",
    "Seite 1 /",
    "2",
    "Konto 2020-12-13"
  ],
  [
    "Fdvj Kmpru Ogbtsp",
    "Rvhek-Lcfn-Ihx 9",
    "9218 Qürvwh",
    "Ztcxiyrqdhq",
    "Xdueztntqspt:",
    "****mue",
    "(695134299)",
    "Datum",
    "Uhrzeit",
    "Produkt",
    "ISIN",
    "Börse",
    "Anzahl",
    "Kurs",
    "Wert in",
    "Lokalwährun",
    "Wert",
    "Wechselkur",
    "s",
    "Gebühr",
    "Gesamt",
    "17-04-2020",
    "18:53",
    "CO-DIAGNOSTICS CM",
    "US1897631057",
    "NDQ",
    "-10",
    "USD",
    "13.50",
    "USD",
    "135.00",
    "CHF",
    "130.37",
    "1.0345",
    "CHF",
    "-0.57",
    "CHF",
    "129.80",
    "31-03-2020",
    "11:04",
    "ISHARES WHCS",
    "IE00BJ5JNZ06",
    "EAM",
    "10",
    "USD",
    "5.0362",
    "USD",
    "-50.36",
    "CHF",
    "-48.57",
    "1.0358",
    "CHF",
    "-2.13",
    "CHF",
    "-50.70",
    "31-03-2020",
    "10:59",
    "ISHARES WITS",
    "IE00BJ5JNY98",
    "EAM",
    "10",
    "USD",
    "5.0219",
    "USD",
    "-50.22",
    "CHF",
    "-48.41",
    "1.0363",
    "CHF",
    "-2.13",
    "CHF",
    "-50.54",
    "20-03-2020",
    "10:06",
    "ISHARES DIGITAL SECURITY UCITS",
    "ETF USD ACC",
    "IE00BG0J4C88",
    "XET",
    "10",
    "EUR",
    "3.882",
    "EUR",
    "-38.82",
    "CHF",
    "-40.93",
    "0.9475",
    "CHF",
    "-2.12",
    "CHF",
    "-43.05",
    "16-03-2020",
    "18:56",
    "AYTU BIOSCIENCE INC.",
    "US0547547002",
    "NDQ",
    "15",
    "USD",
    "1.69",
    "USD",
    "-25.35",
    "CHF",
    "-24.00",
    "1.0552",
    "CHF",
    "-0.59",
    "CHF",
    "-24.59",
    "16-03-2020",
    "14:30",
    "CO-DIAGNOSTICS CM",
    "US1897631057",
    "NDQ",
    "2",
    "USD",
    "9.79",
    "USD",
    "-19.58",
    "CHF",
    "-18.56",
    "1.0541",
    "CHF",
    "-0.54",
    "CHF",
    "-19.10",
    "13-03-2020",
    "10:33",
    "TELEFONAKTIEBOLAGET LM",
    "ERICSSON",
    "SE0000108656",
    "XET",
    "5",
    "EUR",
    "5.85",
    "EUR",
    "-29.25",
    "CHF",
    "-30.87",
    "0.9465",
    "CHF",
    "-4.25",
    "CHF",
    "-35.12",
    "13-03-2020",
    "10:30",
    "WIRECARD AG",
    "DE0007472060",
    "XET",
    "1",
    "EUR",
    "96.60",
    "EUR",
    "-96.60",
    "CHF",
    "-101.99",
    "0.9462",
    "CHF",
    "-4.28",
    "CHF",
    "-106.27",
    "10-03-2020",
    "14:30",
    "CO-DIAGNOSTICS CM",
    "US1897631057",
    "NDQ",
    "4",
    "USD",
    "8.91",
    "USD",
    "-35.64",
    "CHF",
    "-33.20",
    "1.0724",
    "CHF",
    "-0.54",
    "CHF",
    "-33.74",
    "10-03-2020",
    "14:11",
    "NEL ASA NK-,20",
    "NO0010081235",
    "FRA",
    "20",
    "EUR",
    "0.9445",
    "EUR",
    "-18.89",
    "CHF",
    "-20.01",
    "0.9429",
    "CHF",
    "-7.97",
    "CHF",
    "-27.98",
    "10-03-2020",
    "14:07",
    "XIAOMI CORP. CL.B",
    "KYG9830T1067",
    "FRA",
    "10",
    "EUR",
    "1.3996",
    "EUR",
    "-14.00",
    "CHF",
    "-14.83",
    "0.9429",
    "CHF",
    "-7.96",
    "CHF",
    "-22.79",
    "27-02-2020",
    "15:35",
    "CO-DIAGNOSTICS CM",
    "US1897631057",
    "NDQ",
    "4",
    "USD",
    "15.90",
    "USD",
    "-63.60",
    "CHF",
    "-61.60",
    "1.0315",
    "CHF",
    "-0.55",
    "CHF",
    "-62.15",
    "27-02-2020",
    "09:13",
    "XIAOMI CORP. CL.B",
    "KYG9830T1067",
    "FRA",
    "10",
    "EUR",
    "1.504",
    "EUR",
    "-15.04",
    "CHF",
    "-15.99",
    "0.9395",
    "CHF",
    "-7.99",
    "CHF",
    "-23.98",
    "27-02-2020",
    "09:12",
    "NOKIA OYJ",
    "FI0009000681",
    "HSE",
    "5",
    "EUR",
    "3.717",
    "EUR",
    "-18.59",
    "CHF",
    "-19.76",
    "0.9396",
    "CHF",
    "-4.27",
    "CHF",
    "-24.03",
    "11-02-2020",
    "09:42",
    "BLACKROCK ISHARES S&P 500",
    "INFORMATION TECHNOLOGY SEC...",
    "IE00B3WJKG14",
    "SWX",
    "3",
    "USD",
    "12.684",
    "USD",
    "-38.05",
    "CHF",
    "-37.21",
    "1.0217",
    "CHF",
    "-2.15",
    "CHF",
    "-39.36",
    "DEGIRO B.V. ist als",
    "Investmentgesellschaft bei der",
    "niederländischen",
    "Finanzaufsichtsbehörde (AFM)",
    "registriert.",
    "DEGIRO B.V.",
    "Amstelplein 1",
    "1096 HA Amsterdam",
    "E",
    "tcplyznnbmybl@tcvkwn.pb",
    "I",
    "www.degiro.ch",
    "Seite 2 /",
    "2",
    "Konto 2020-12-13"
  ]
]

```

</p></details>

## Community profile

https://app.tresor.one/p/5fcf542b0619f3003824e9df

---
Issue submitted with https://import.tresor.one

### PR DESCRIPTION
**Pull request by SirGibihm**
Due to a little Bug `Sell`s are identified as `Buy`s. Fixed that
* Fixes #464 and Fixes #363 
* Partial fix for #388 

Prepared support for the swiss variant of degiro, which will require only miniscule change of the code once the backend accepts other base currencies.
* On swiss documents the swiss number format (-13.37) instead of the german (-13,37) number format is used
* no further format changes

### CODE REVIEW

**Comment by dredav** [comment]
One question: The activities from degiro.ch are in `CHF`. So the base currency is not `EUR` which is currently not supported by T1, right?

**Comment by SirGibihm** [comment]
> 
> 
> One question: The activities from degiro.ch are in `CHF`. So the base currency is not `EUR` which is currently not supported by T1, right?

Yeah I did not think about that but thats completely True... The user would see his or her transactions in the wrong currency;  now that I think about it I should revert the change. What do you think @codeofsumit ?

**Comment by dredav** [comment]
But we can made `canParsePage` more open. So that all degiro countries with `EUR` are supported, what did you think @SirGibihm? (all degiros are listed here: https://www.degiro.eu)

**Comment by SirGibihm** [comment]
> 
> 
> But we can made `canParsePage` more open. So that all degiro countries with `EUR` are supported, what did you think @SirGibihm? (all degiros are listed here: https://www.degiro.eu)

Awesome idea! Implemented all € countries where degiro operates!

File: src/brokers/degiro.js [hunk 1]
```diff
@@ -68,12 +101,18 @@ const parseActivity = (content, index) => {
     activity.foreignCurrency = currency;
   }
 
+  if (validateActivity(activity) === undefined) {
+    console.log(activity);
+  }
```
Comment (dredav) [inline src/brokers/degiro.js:106]: Could you remove the debug part?

**Review by dredav — CHANGES_REQUESTED** [review]
Found one little debug thing which should removed before merging.

File: src/brokers/degiro.js (hunk 1 above)
Comment (SirGibihm) [reply src/brokers/degiro.js:106]: Thats no debug part; I use Debuggers, I promise! I am a competent programmer!! (Removed the debugging part).

**Comment by SirGibihm** [comment]
@dredav Ready to go

**Review by dredav — APPROVED** [review]
